### ISSUE TITLE
Can Suites be run across multiple test files?

### ISSUE THREAD

**Issue by shashank-g172** [stretchr/testify#1007]
Hi, 
 I'm still quite a noob at this, but can the suite be extended across multiple files? Is there an example anyone could point me to please?

I have 2 classes a_test and b_test. a_test has the suite, which does the necessary setup. I'd like to know if there's a way I could always make a_test's suite.setUp run, run all the tests in it, run the tests in b_test, and then return back to a_test and call Suite.TearDown. 

My other choice is to implement TestMain to force the equivalent of SuiteSetup in one class, and then figure out a way to do the necessary teardown. 

Has anyone faced this issue before? 

Thanks

**Comment by gavwu** [comment]
Hi @shashank-g172  

I still have some confusions about the question:
1. Do you mean different files or different package? AFAIK, you can write test code on different file within the same package
2. Why do you need a_test SetupSuite() in b_test?  If you do, make one testSuite class, and test these two class

**Comment by shashank-g172** [comment]
Thank you for your response @gavwu. 

1. I mean in the same package.
2. How would one testSuite class work with the other two classes?

Perhaps I should detail out my use case a bit more: 

This is the current implementation: 

a_test sets up a couple of docker containers in the SetUpSuite method and runs some tests against some endpoints. (healthcheck etc.) 
b_test runs tests against other endpoints, with the expectation that the containers are already up and running. (actual business logic with Request bodies etc.) 

Once b_test is done executing, TearDown suite needs to be invoked (in a_test) to tear down the containers. 

I guess I'm asking for the equivalent of a BaseTestClass' @Before and @After in JUnit (with other test classes extending them) using the TestSuite in Go.

**Comment by gavwu** [comment]
That seems straight forward now, so my understanding is:
1. you want to setup docker containers first
2. do the testing(no matter whether they are healthcheck or business logic)
3. tear down the containers after all this

I will do the code like this:

```go
type YourTestSuite struct {
    a_test_instance a_test
    b_test_instance b_test
}

// this is the @before
func (s *YourTestSuite)SetupSuite() {
    s.a_class_instance = new_a_class()
    s.b_class_instance = new_b_class()

    s.a_class_instance.SetupDockerContainer()

    // you can run the healthcheck here or treat it as a testcase
}

// this is the @after
func (s *YourTestSuite)TearDownSuite(){
    // tear down the containers
}

func (s *YourTestSuite) TestBusinessLogic1() {
    
}

func (s *YourTestSuite) TestBusinessLogic2() {
    
}
```

**Comment by shashank-g172** [comment]
Thank you very much for the suggestion @gavwu! I will give it a shot and update the issue if that works for me.

**Comment by shashank-g172** [comment]
I was able to solve the problem by using a combination of TestMain and struct to split my tests into different files. 

Thanks!

**Comment by SamiAlsubhi** [comment]
> I was able to solve the problem by using a combination of TestMain and struct to split my tests into different files.
> 
> Thanks!

Can you please elaborate more on how you did it?

**Comment by SamiAlsubhi** [comment]
@shashank-g172

**Comment by shashank-g172** [comment]
I did something like this: 

Base Class A:
```

type ProdTestSuite struct {
	suite.Suite
	logger zapper.SugaredLogger
}

func TestIntegrationSuite(t *testing.T) {
	if environment == "dev" {
		suite.Run(t, new(DevTestSuite))
	} else {
	suite.Run(t, new(ProdTestSuite))
	}
}

func TestMain(m *testing.M) {
	readAndValidateFlags()
	os.Exit(m.Run())
}
```

Class B: 
```
func (suite *ProdTestSuite ) Test_AboutEndpoint() {
... 
}
```

Everything that started with a Test* in a different class and was implicitly associated with the struct, and it ran as expected. I hope that helps.
