### ISSUE TITLE
Mocking Variadic Functions

### ISSUE THREAD

**Issue by mveytsman** [stretchr/testify#101]
Hi there,

I get a strange error when mocking out a variadic function and calling it with a empty arguments list:

```
--- FAIL: TestStash (0.00 seconds)
panic:

mock: Unexpected Method Call
-----------------------------

Send(string,[]interface {})
		0: MULTI
		1: []

The closest call I have is:

Send(string,[]interface {})
		0: MULTI
		1: []
 [recovered]
	panic:
```

For context, I'm trying to mock out [redigo](https://github.com/garyburd/redigo).

```go
type MockRedisConn struct {
	mock.Mock
}

func (m *MockRedisConn) Close() error {
	return nil
}

func (m *MockRedisConn) Err() error {
	return nil
}

func (m *MockRedisConn) Do(commandName string, argsList ...interface{}) (interface{}, error) {
	args := m.Mock.Called(commandName, argsList)
	return args.Get(0), args.Error(1)
}

func (m *MockRedisConn) Send(commandName string, argsList ...interface{}) error {
	args := m.Mock.Called(commandName, argsList)
	return args.Error(0)
}

func (m *MockRedisConn) Flush() error {
	return nil
}

func (m *MockRedisConn) Receive() (interface{}, error) {
	return nil, nil

}
```

I then declare an expectation for a method call with an empty argslist:

```go
mockRedis.On("Send", "MULTI", []interface{}{}).Return(nil)
```

Is there a bug in how testify/mock handles variadic functions?

**Comment by robdaemon** [comment]
I've been looking at this - the issue happens around here: https://github.com/stretchr/testify/blob/master/assert/assertions.go#L40

Specifically, you end up with an expected of: `[]interface {}(nil)` and an actual of `[]interface {}{}`

I'll look and see if I can figure out why, but my initial instinct is that this is a Go issue.

I did find a workaround, which seems particularly nasty:

`
mockRedis.On("Send", "MULTI", reflect.Zero(reflect.TypeOf([]interface{}{})).Interface()).Return(nil)
`

**Comment by mveytsman** [comment]
Thanks for looking into this @robdaemon, I hope you figure it out. And yeah, that's a nasty workaround :)

**Comment by vladimirvivien** [comment]
Any update on this possible variadic issue ?

**Comment by ernesto-jimenez** [comment]
@vladimirvivien I'll look into it.

In the mean time, if the actual value is not important, a posible workaround would be using `AnythingOfType`.

An example working around the fact that we cannot compare anonymous funcs: https://github.com/stretchr/testify/issues/159#issuecomment-99838827

**Comment by ernesto-jimenez** [comment]
Everything seems to work OK.

I've added some tests in PR #175 

@robdaemon, @robdaemon:

Here's the solution:
```go
var expected []interface{}
mockRedis.On("Send", "MULTI", expected).Return(nil)
```

No need for the reflect workaround.

Do you have any other use cases failing? Otherwise we'll just close this issue

Best,
Ernesto

**Comment by ernesto-jimenez** [comment]
@mveytsman @robdaemon @vladimirvivien any comments? or can I close the issue? :)

**Comment by vladimirvivien** [comment]
@ernesto-jimenez please close, I got around using the Any type in my assertion.  Thanks for looking into this.

**Comment by ernesto-jimenez** [comment]
closing, thanks!
