### ISSUE TITLE
Point release

### ISSUE THREAD

**Issue by dag-erling** [stretchr/testify#1015]
My apologies for putting this in an issue, but it's the only way I could find to contact you without signing up for yet another messaging service.

Would you be willing to tag the current state of the tree as v1.6.2? I could really use 95a9d90 and 415d892, but policy prevents me from importing an unreleased version.

**Comment by tmaczukin** [comment]
Same here! Can't wait to have the `errors.Is()` and `errors.As()` available as regular assertions!

Currently it can be used only by calls like `assert.True(t, errors.Is(err, target), "expected ...")` which is just ugly :slightly_smiling_face:

**Comment by bconway** [comment]
This would be greatly appreciated.

**Comment by Antonboom** [comment]
+1

**Comment by brackendawson** [comment]
No longer required.
