### ISSUE TITLE
JSONEq returning error due to difference in ordering

### ISSUE THREAD

**Issue by NamanJain8** [stretchr/testify#1025]
The following snippet returns error:
```go
require.JSONEq(t, `[
		{"uid":"0x2","name@en":"pho\ton"},
		{"uid":"0x1","name":"pho\ton"}
		]`, `[
			{"uid":"0x1","name":"pho\ton"},
			{"uid":"0x2","name@en":"pho\ton"}
			]`
	)
```
Is there any work-around for this? This seems like a bug to me.

**Comment by roppa** [comment]
Json is unordered collection (see [json.org](https://www.json.org/))

**Comment by yulicrunchy** [comment]
Anyone have a workaround for this? This would be a really nice feature.

**Comment by joshcarp** [comment]
@yulicrunchy I've been working on a workaround for equating proto objects that have lists without a guaranteed order:

https://github.com/anz-bank/equals

it takes a generic interface, and converts it to json before doing any comparisons:

```go
func TestStruct(t *testing.T) {
	type Bar struct {
		Arr []int
	}
	type Foo struct {
		A Bar
	}
	ElementsMatchRec(t,
		Foo{A: Bar{Arr: []int{1, 2, 3}}},
		Foo{A: Bar{Arr: []int{3, 2, 1}}})
}
```

**Comment by black-desk** [comment]
> Json is unordered collection (see [json.org](https://www.json.org/))

> In JSON, they take on these forms:
> An object is an unordered set ...
> An array is an ordered collection ...

from https://www.json.org/json-en.html

**Comment by fugkco** [comment]
@roppa @black-desk maybe I'm misunderstanding your messages, but exactly because objects are unordered, OPs test should pass.

**Comment by brackendawson** [comment]
> @roppa @black-desk maybe I'm misunderstanding your messages, but exactly because objects are unordered, OPs test should pass.

The OP's JSON blobs are both arrays, which are ordered, and the elements are in different orders, this is [correctly failing](https://go.dev/play/p/cUzKMFScEIL).

I don't know why we're mentioning that JSON objects are unordered, it's not relevant to the OP's question. Perhaps we've all answered "that question" too many times and we missed that this is not an instance of "that question".

Anyone that would like to assert that two JSON arrays contain the same elements will need to first unmarshal them, like [this](https://go.dev/play/p/k1UOC_G5s5R):
```go
func TestJSON(t *testing.T) {
	var expected, actual []interface{}
	require.NoError(t, json.Unmarshal([]byte(`[
		{"uid":"0x2","name@en":"pho\ton"},
		{"uid":"0x1","name":"pho\ton"}
		]`), &expected))
	require.NoError(t, json.Unmarshal([]byte(`[
		{"uid":"0x1","name":"pho\ton"},
		{"uid":"0x2","name@en":"pho\ton"}
		]`), &actual))
	require.ElementsMatch(t, expected, actual)
}
```

This is not a bug.

**Comment by Edward601** [comment]
String  everything back to the normal

**Comment by Edward601** [comment]
I don't want anything to fail

**Comment by goyzhang** [comment]
at least provide an option to ignore orders..

**Comment by brackendawson** [comment]
> I don't want anything to fail

You and me both, buddy.

> at least provide an option to ignore orders..

What would you call it? `assert.JSONElementsMatch` I'd say no because [ElementsMatch](https://pkg.go.dev/github.com/stretchr/testify/assert#ElementsMatch) can only be called on slices and arrays. `assert.JSONEqExeptWithArraysInAnyOrder` I'd say no because it's deliberately silly.

I did provide a [sane example](https://github.com/stretchr/testify/issues/1025#issuecomment-1139478645). I don't think this issue warrants any change. If you can describe a good change that would address this need then comment and I'll re-open.

**Comment by ProgramCpp** [comment]
@brackendawson can you share an example why the array is embedded?

**Comment by Antonboom** [comment]
@brackendawson hi!

If JSON array is an ordered collection by design, then why does `JSONEq` take into account the order of the elements? 🤔 
This results in either flacky tests or additional testing code.

**Comment by brackendawson** [comment]
> If JSON array is unordered collection by design

But JSON array *is* an ordered collection.

If a given user's isn't ordered by their design, then they should expect to need some acrobatics when reasoning with their JSON data. I think that JSONEq should expect to work with JSON.

**Comment by Antonboom** [comment]
> But JSON array is an ordered collection.

My bad, I read it wrong.

https://www.rfc-editor.org/rfc/rfc7159.html

>  An array is an **ordered** sequence of zero or more values.
