### ISSUE TITLE
JSONEq not comparing empty string

### ISSUE THREAD

**Issue by EvansJahja** [stretchr/testify#1028]
```go
assert.JSONEq(t, "", "")
```

Expected: assertion should be true, as empty string is valid JSON.

Reality: (underlying`encoding/json`) does not unmarshall empty string.

Proposed solution:

JSONEq should check if `expected` and `actual` are both empty string before performing unmarshall

thoughts?

**Comment by nbaztec** [comment]
An empty string `` ` ` `` / `""` is _not_ valid JSON. The following however is:

* `` `""` ``
* `` `"foo"` ``
* `8`


```go
        var s string
	_ = json.Unmarshal([]byte(`"foo"`), &s)
	fmt.Println(s)         // prints foo
	_ = json.Unmarshal([]byte(`""`), &s)
	fmt.Printf(">%s<\n", s)         // prints ><
```

**Comment by EvansJahja** [comment]
> An empty string `` ` ` `` / `""` is _not_ valid JSON. The following however is:
> 
> * `` `""` ``
> * `` `"foo"` ``
> * `8`
> 
> ```go
>         var s string
> 	_ = json.Unmarshal([]byte(`"foo"`), &s)
> 	fmt.Println(s)         // prints foo
> 	_ = json.Unmarshal([]byte(`""`), &s)
> 	fmt.Printf(">%s<\n", s)         // prints ><
> ```

Ah you are correct. Quotation marks are required to define a string. 
Thank you for clarifying.

**Comment by ofabricio** [comment]
I was about to create a new issue about this.

I think this assert `assert.JSONEq(t, "", "")` should not fail, not because it is an invalid json, but because the assertion of two empty strings is true. That would make code simpler, otherwise I have to add an `if` to test that specific case all the time (which happens a lot for me when testing response from a http handler).

Example (see the comment in the code):

```go
func TestExample(t *testing.T) {

    tt := []struct {
        Desc     string
        GiveBody bool
        ThenBody string
    }{
        {
            Desc:     "With Content",
            GiveBody: true,
            ThenBody: `{ "a": "b" }`,
        },
        {
            Desc:     "No Content",
            GiveBody: false,
            ThenBody: "",
        },
    }

    for _, tc := range tt {

        r := httptest.NewRequest(http.MethodGet, "/", nil)
        w := httptest.NewRecorder()

        MyHandler := func(w http.ResponseWriter, r *http.Request) {
            if tc.GiveBody {
                w.Write([]byte(`{ "a": "b" }`))
            }
        }
        MyHandler(w, r)

        // I could remove this if check if JSONEq asserts the two empty values as true.

        if w.Body.String() != "" {
            assert.JSONEq(t, tc.ThenBody, w.Body.String())
        } else {
            assert.Equal(t, tc.ThenBody, w.Body.String())
        }
    }
}
```

**Comment by brackendawson** [comment]
I would say your API design is the problem here, if you have no keys to return and you aren't using a 404 return code, then your returned body should probably be empty object:
```javascript
{}
```

**Comment by ofabricio** [comment]
@brackendawson Maybe, but suppose this usecase:

The endpoint is a `PUT`. When successful, it returns `204 no content`. But if a error occurrs it returns a both with the error message: `{ "message": "Oops, <this> happened" }`. Would this be a bad design?

**Comment by brackendawson** [comment]
That's not a bad design, so long as you're setting a content type. But I don't think it justifies making `JSONEq` test things that aren't JSON. I think in such a case the explicit conditional is better; "this should either be no body at all or JSON which is equivalent to x". If you allow emptystring to be the "expected JSON" then how should these examples evaluate:
```go
assert.JSONEq(t, "", "")
assert.JSONEq(t, "", " ")
assert.JSONEq(t, "", "\n")
assert.JSONEq(t, "", "this is invalid json therefore it is equivalent to the expectation")
```

**Comment by ofabricio** [comment]
I think you have a fair point, but isn't an empty string a special case for being a zero value? I mean only when both expected and actual are empty. Isn't a zero value json equal to a zero value json? At least in terms of assertions wouldn't it mean just "I wait for a nonexistent json" and not for an invalid one.
