### ISSUE TITLE
test async functions

### ISSUE THREAD

**Issue by mmdaz** [stretchr/testify#1030]
Hey,

I have a scenario that a function is called n times with different variables, I know these variables but I don't know the order of them and it's not important for me.
So, before function calls, I have a for loop to say the variables.
 

```
for i := 1; i <= 1000; i++ {
    // bytes depands on the variable **i**
    mockKafkaPubsub.On("Publish", "service_name", bytes).Return(nil)
}
```
after the for loop, I expected that the Publish function is called 1000 times with the below values. but the order is not important for me and actually, I don't know it, because they are called in a worker pool.

How can I test this scenario with testify mocks?

**Comment by maratori** [comment]
@mmdaz, you can use `Once` and `AssertExpectations`:
```go
for i := 1; i <= 1000; i++ {
    // bytes depands on the variable **i**
    mockKafkaPubsub.On("Publish", "service_name", bytes).Return(nil).Once()
}
// act
mockKafkaPubsub.AssertExpectations(t)
```

**Comment by maratori** [comment]
@brackendawson Have you tried [EventuallyWithT](https://pkg.go.dev/github.com/stretchr/testify/assert#EventuallyWithT)? I think you can call `m.AssertExpectations` inside condition.

**Comment by brackendawson** [comment]
I have not seen that before, it would work but `assert.CollectT` doesn't satisfy `mock.TestingT` (missing method Logf). That should be easy to remedy.
