### ISSUE TITLE
Inconsistency parameters

### ISSUE THREAD

**Issue by reindert-vetter** [stretchr/testify#1040]
I am quite surprised that many methods are not consistent. I switch between `Regexp` and `Contains`, `Equal` and `Len` quite often. See the following examples:

``` go
	require.Len(t, actual, expected)
	require.Equal(t, expected, actual)
	require.Contains(t, actual, expected)
	require.Regexp(t, expected, actual)
```
Is there a reason for this?

**Comment by brackendawson** [comment]
I think this is a duplicate of #146 which is in the v2.0.0 milestone.
