### ISSUE TITLE
NotImplements

### ISSUE THREAD

**Issue by talglobus** [stretchr/testify#1065]
A useful pattern is to have a function take a `thing` that doesn't implement an interface and return `anotherThing` that does. These glue functions work really well to connect different parts of an application, and create a useful abstraction across interfaces.

The way I test these functions is with `assert.Implements(t, interface, anotherThing)` on the result of the function, and `_, ok := thing.(interface); assert.False(ok)` on the input for good measure.

It would be _oh so convenient_ if there were an `assert.NotImplements(t, interface, thing)` I could run instead, and it would be fairly trivial to add to the API as it stands. If this isn't the kind of change that's likely to happen, is there a more semantically reasonable way of doing this?

**Comment by mitar** [comment]
i would also love to see `NotImplements`.
