### ISSUE TITLE
Assert pointer panic

### ISSUE THREAD

**Issue by fengxuway** [stretchr/testify#1071]
I want compare two string pointer's value, but got panic. This is my testcase:
```
func TestAssertPointer(t *testing.T) {

	foo := "foo"
	bar := "bar"
	assert.EqualValues(t, &foo, &bar)
}
```

Panic info:
```
$ go test -v -run TestAssertPointer                                                                                                            
=== RUN   TestAssertPointer
--- FAIL: TestAssertPointer (0.00s)
panic: interface conversion: interface {} is *string, not string [recovered]
        panic: interface conversion: interface {} is *string, not string
```

The reason why compare pointer because the foo and bar package as interface{}.

**Comment by brackendawson** [comment]
What version of go and testify are you using? I can't reproduce this.

Also I think you want to use `assert.Equal()` for this, from the documentation; *"Pointer variable equality is determined based on the equality of the referenced values (as opposed to the memory addresses)."*

**Comment by fengxuway** [comment]
I can't reproduce this too. Maybe my environment was wrong.
