### ISSUE TITLE
Is this repo dead/abandoned?

### ISSUE THREAD

**Issue by mvrahden** [stretchr/testify#1095]
As the title suggests, there seems to be very low maintainer activity.
Even after tagging some of the maintainers, nothing happens.

Can the status for this repo be clarified?

**Comment by glesica** [comment]
@boyan-soubachov is the primary maintainer. The repo is lightly maintained. If you'd like to help, there is a channel on the Gophers Slack workspace.

**Comment by mvrahden** [comment]
@glesica: yeah, I actually wanted to help with my two PRs (and their corresponding Issues) which are soon a month old, without any maintainer reaction/response.

In contrast, this issue was closed in under half an hour.

So what do I need to do, to get my PRs passed?

**Comment by glesica** [comment]
As I said above, you could tag the actual maintainer (I see you tagged someone currently uninvolved in the project on your PRs). You could also reach out on Slack.

**Comment by mvrahden** [comment]
Alright, thanks for your feedback then. I'll give it a try
