### ISSUE TITLE
ReturnOnce undefined for *mock.Call

### ISSUE THREAD

**Issue by lonevetad** [stretchr/testify#1098]
After creating an instance of a struct implementing `StartSession() (mongo.Session, error)` called "foo" for short, the following piece of code `foo.On("StartSession").ReturnOnce( .. stuffs .. )` produces the error: `foo.On("StartSession").ReturnOnce undefined (type *mock.Call has no field or method ReturnOnce)`

**Comment by brackendawson** [comment]
```go
foo.On("StartSession").Return(stuffs...).Once()
```

**Comment by lonevetad** [comment]
Thank you so much
