### ISSUE TITLE
When using fmt.Printf ,no test were run

### ISSUE THREAD

**Issue by catbugdemo** [stretchr/testify#1099]
![image](https://user-images.githubusercontent.com/87176800/125220921-f8923e80-e2f9-11eb-8e7e-d7ad24ae208f.png)

**Comment by catbugdemo** [comment]
May I ask a question,  when using fmt.Printf and others like fmt.Sprintf will occurr this error

**Comment by brackendawson** [comment]
As your editor shows from the terminal view, the test did run. I can confirm this by running the same code locally:

kata_test.go:
```go
package kata

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestTest(t *testing.T) {
	assert.Equal(t, true, true)
	fmt.Printf("%v", 1)
}
```

```
% go test -v
=== RUN   TestTest
1--- PASS: TestTest (0.00s)
PASS
ok      github.com/brackendawson/kata   0.185s
```

The "No tests were run" is part of your editor or one of its plugins. The author of that will be best placed to triage this issue. This is almost certainly not an issue with testify.

**Comment by catbugdemo** [comment]
thank you
