### ISSUE TITLE
support timeout per test function

### ISSUE THREAD

**Issue by tisonkun** [stretchr/testify#1101]
`-timeout` provided by go testing only timeout per test binary, i.e., per pkg. I'd like to setup a timeout per test function. How to achieve it?

**Comment by brackendawson** [comment]
The [requirement](https://pkg.go.dev/testing#T.FailNow) to call `t.FailNow()` or `t.SkipNow()` from the same goroutine running the test makes it impossible for testify to implement this timeout feature gracefully.

This is something you'd have to raise in [github.com/golang/go](https://github.com/golang/go) if you really want it.

The closest I can manage ungracefully is [this test helper function](https://play.golang.org/p/7wMaETlagbt) but it will stop all your tests on timeout. Maybe the folks on StackOverflow can do better if you ask them?

```go
package main

import (
	"os"
	"testing"
	"time"
)

func TestSleep(t *testing.T) {
	withTimeout(t, time.Second)

	time.Sleep(time.Minute)
}

func withTimeout(t *testing.T, timeout time.Duration) {
	t.Helper()

	testFinished := make(chan struct{})
	t.Cleanup(func() { close(testFinished) })

	select {
	case <-testFinished:
	case <-time.After(timeout):
		t.Errorf("test timed out after %s", timeout)
		os.Exit(1)
	}
}
```

**Comment by tisonkun** [comment]
Closed as information delivered.

**Comment by dolmen** [comment]
@tisonkun  We now have [`assert.Eventually`](https://pkg.go.dev/github.com/stretchr/testify/assert#Eventually) and [`assert.EventuallyWithT`](https://pkg.go.dev/github.com/stretchr/testify/assert#EventuallyWithT).

**Comment by tisonkun** [comment]
Thank you! I already use Eventually in https://github.com/apache/kvrocks/tree/unstable/tests/gocase :D

**Comment by samber** [comment]
The example above has 2 limits:
- `t.Errorf` writes the error into a buffer, which is not flushed to stderr when the `-v` flag is missing in `go test`
- Removing the call to `os.Exit` prevents stopping the test when the execution time goes to infinity

I suggest a different syntax using `panic` that writes immediately to stderr and exits. I also print the error path into the error message because `panic` is called from a goroutine.

```go
func withTimeout(t *testing.T, timeout time.Duration) {
	t.Helper()

	testFinished := make(chan struct{})

	t.Cleanup(func() {
		close(testFinished)
	})

	invokedAt := ""
	funcName := ""

	var pc [1]uintptr
	n := runtime.Callers(2, pc[:])
	if n > 0 {
		frames := runtime.CallersFrames(pc[:])
		frame, _ := frames.Next()
		invokedAt = frame.File + ":" + strconv.Itoa(frame.Line)
		funcName = frame.Function
	}

	go func() {
		select {
		case <-testFinished:
		case <-time.After(timeout):
			if line == "" || funcName == "" {
				panic(fmt.Sprintf("Test timed out after: %v", timeout))
			}
			panic(fmt.Sprintf("%s: Test timed out after: %v\n%s", funcName, timeout, invokedAt))
		}
	}()
}
```
