### ISSUE TITLE
Test passed in goroutine but failed when it not running in goroutine

### ISSUE THREAD

**Issue by RuiyuShan** [stretchr/testify#1131]
A test passed when it running in goroutine:
```
=== RUN   TestTrafficLogicTestSuite
--- PASS: TestTrafficLogicTestSuite (0.00s)
PASS
```
![image](https://user-images.githubusercontent.com/67950682/145195073-97009058-bc55-4281-a08b-5cd4945207b5.png)

But it failed when it not running in goroutine:
```
=== RUN   TestTrafficLogicTestSuite
--- FAIL: TestTrafficLogicTestSuite (0.00s)
=== RUN   TestTrafficLogicTestSuite/TestTrafficAlarmLogic_JudgeMessage
    suite.go:63: test panicked: runtime error: invalid memory address or nil pointer dereference
```
![image](https://user-images.githubusercontent.com/67950682/145194944-3ca99260-ec93-4423-9310-e79e62cde0ca.png)

**Comment by brackendawson** [comment]
`TestTrafficLogicTestSuite ` passed and then the main testing goroutine exited almost immediately, causing all other goroutines to exit. Your test does always fail but if you run it in a goroutine like this then it never has time to fail. [See this example](https://go.dev/play/p/Du9VfglcsES).

**Comment by brackendawson** [comment]
If you are attempting to make the suite run in parallel with other testing, use `t.Parallel()`:
```go
func TestTrafficLogicTestSuite(t *testing.T) {
    t.Parallel()
    suite.Run(t, new(TrafficLogicTestSuite))
}
```

**Comment by RuiyuShan** [comment]
Thank you for your reply! 
I just found that the test error was caused by another reason, and I'm sorry for asking this stupid question.
The reason of `suite.go:63: test panicked: runtime error: invalid memory address or nil pointer dereference` is that I run `go test` command without adding `-gcflags=-l` flag when replacing two functions with [bouk/monkey](https://github.com/bouk/monkey).

**Comment by quocbang** [comment]
> Thank you for your reply! I just found that the test error was caused by another reason, and I'm sorry for asking this stupid question. The reason of `suite.go:63: test panicked: runtime error: invalid memory address or nil pointer dereference` is that I run `go test` command without adding `-gcflags=-l` flag when replacing two functions with [bouk/monkey](https://github.com/bouk/monkey).

how can you set up those flags in vscode?
