### ISSUE TITLE
(on go1.18beta1) testing package's some method's param type changed from 'interface{}' to 'any'(new type on builtin.go)

### ISSUE THREAD

**Issue by AnJaeSeongS2** [stretchr/testify#1138]
I think need convert TestingT interface's Errorf function's param type for go1.18beta1
and need check other codes about using 'interface{}'.

![image](https://user-images.githubusercontent.com/9591027/147380249-dd0c5125-3eeb-40ad-a576-90c1e97ee17a.png)
![image](https://user-images.githubusercontent.com/9591027/147380319-ad63acf3-9d30-4c2e-8b35-8a41afa202d1.png)

**Comment by brackendawson** [comment]
`any` [is an alias](https://tip.golang.org/doc/go1.18#generics) for `interface{}` so this should [just work](https://go.dev/play/p/mL2TxR8g-xa?v=gotip). Referencing `any` anywhere in the testify code base would break compatibility with all previous versions of go, currently everything back to v1.14 is supported.

Does this fail when running `go test ./...` or is it just your editor reporting the error?

**Comment by brackendawson** [comment]
Using the 1.18beta1 release I can't recreate this:

```
root@0c354fbbd53a:~# go version
go version go1.18beta1 linux/amd64
root@0c354fbbd53a:~# cat main_test.go 
package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestTestify(t *testing.T) {
	assert.Equal(t, 10, 10)
	assert.NotEqual(t, 1, 10)
}
root@0c354fbbd53a:~# go test -v ./...
=== RUN   TestTestify
--- PASS: TestTestify (0.00s)
PASS
ok  	example.com/testy	0.009s
```

I think your editor or language server is the issue here.

**Comment by AnJaeSeongS2** [comment]
> `any` [is an alias](https://tip.golang.org/doc/go1.18#generics) for `interface{}` so this should [just work](https://go.dev/play/p/mL2TxR8g-xa?v=gotip). Referencing `any` anywhere in the testify code base would break compatibility with all previous versions of go, currently everything back to v1.14 is supported.
> 
> Does this fail when running `go test ./...` or is it just your editor reporting the error?

I'm sorry for the hasty posting of the issue.
Like your caring answer, it was an issue only on Intellij. As you suggested, I confirmed that it will be tested normally when proceeding to the CLI.
In order not to waste your time on next, we will prioritize checking whether it is normal in the CLI and then registering the issue...

**Comment by tisonkun** [comment]
This should be a GoLand issue as tracked here https://youtrack.jetbrains.com/issue/GO-12171 .
