### ISSUE TITLE
require.New(t) would be useful

### ISSUE THREAD

**Issue by willfaught** [stretchr/testify#114]
Similar to assert.New(t)

**Comment by nelsam** [comment]
There's a PR for that functionality; give me a little bit, I've got a really busy week on my hands.  I'll set reminders for this weekend to go over all the PRs and issues.

**Comment by nelsam** [comment]
Okay, the PR in question was #113 and I went over it today.  It looked good, so I merged it.  Feel free to reopen this issue or open another if it doesn't cover what you were asking (or if it doesn't work right).

**Comment by willfaught** [comment]
Looks good!
