### ISSUE TITLE
Is it possible to ignore function arguments number check?

### ISSUE THREAD

**Issue by egolearner** [stretchr/testify#1148]
In our scenario, grpc middleware may append extra arguments to function call on certain conditions. We have to add extra `mock.Anything` to address those arguments. 

How to make testify less harsh about the number arguments passed? Any help is appreciated.

**Comment by brackendawson** [comment]
This isn't possible today but it could be an enhancement, maybe:
```go
myDouble.On("FuncX", mock.AnyNumberOfCalls).Return("things")
```
I think it would end up superseding all other argument matching, and I'm not sure if it would mix well with defined arguments in the same call. I'd also question its value given that the number of arguments is static, can you be more specific about the case where this is a pain point for you?

**Comment by egolearner** [comment]
```golang
func (_m *XXXClient) hello(ctx context.Context, message *proto.SomeProtobufMessage, opts ...grpc.CallOption)
```
We are mocking GRPC client stub, and the interface is like the above one. 
Maybe `mock.AnyNumberOfCalls` is too much as we lost the ability to check other arguments. Better if we could ignore 
 only the vadradic arguments number check. 

> I'd also question its value given that the number of arguments is static, can you be more specific about the case where this is a pain point for you?

For non vadradic functions, there is no much pain as we can provide exactly some number of `mock.Anything`, while it's painful to provide exactly number of `mock.Anything` for vadradic functions.

**Comment by brackendawson** [comment]
Variadic arguments are always a slice of that type inside the function, this is true for a mock as long as you don't expand the slice back out in your stub. You can ignore all of the variadic arguments with a single `mock.Anything`:
```go
myXXXClient.On("hello", mock.Anything, expectedProtobufMessage, mock.Anything)
```

Testing some of the variadic arguments is harder, you'd need to use a `mock.MatchedBy()` function:
```go
package kata

import (
	"context"
	"testing"

	"github.com/stretchr/testify/mock"
)

type myMock struct {
	mock.Mock
}

func (m *myMock) hello(ctx context.Context, arg string, options ...string) {
	m.Called(ctx, arg, options) // Do not use `options...`
}

func TestAssert(t *testing.T) {
	m := &myMock{}
	m.Test(t)
	m.On("hello", mock.Anything, "hello", mock.MatchedBy(func(args []string) bool {
		return len(args) >= 1 && args[0] == "from"
	})).Return().Once()
	m.hello(context.Background(), "hello", "from", "the", "other", "side")
}
```

**Comment by egolearner** [comment]
We use mockery to generate mock struct. After add `--unroll-variadic=False`, it works as expected.
Thanks for your kind help! @brackendawson
