### ISSUE TITLE
Cut a new release for `require.ErrorContains`?

### ISSUE THREAD

**Issue by tisonkun** [stretchr/testify#1151]
It's implemented about one year ago and not yet released.

**Comment by tisonkun** [comment]
cc @boyan-soubachov @torkelrogstad

**Comment by torkelrogstad** [comment]
I don't have any rights on this repo, sadlyy

**Comment by tisonkun** [comment]
FWIW, I create a fork on [github.com/tisonkun/assert/v1.0.0](https://github.com/tisonkun/assert) and publishing:

* `(*Assertion).ErrorContains`
* `(*Assertion).ErrorRegexp`

I clean up all `mock` and `suite` stuff and keep only assertions so that the package is a supplement of Golang's `testing` for convenient assertions. And thus I don't want to implement anything like `suite` or `mock`.

* `suite` can be simply implemented leveraging [Golang's Subtests](https://go.dev/blog/subtests).
* `mock` is not a good practice as it's hard to sync logics between the mock and the real object.

If only the upstream gets revived I'm glad to see whether I can switch to the upstream again.

**Comment by obalunenko** [comment]
Ping @boyan-soubachov @matryer @ernesto-jimenez

**Comment by tisonkun** [comment]
Closed as no more activities. I will use [github.com/tisonkun/assert/v1.0.0](https://github.com/tisonkun/assert) when necessary.

**Comment by boyan-soubachov** [comment]
Excuse me, I've been away for a while. Is this not included in the v1.7.1 release?

**Comment by tisonkun** [comment]
@boyan-soubachov you're right. I just notice that new tag. Thank you!
