### ISSUE TITLE
1.18: assertions non-functional

### ISSUE THREAD

**Issue by jtagcat** [stretchr/testify#1153]
```
$ go version
go version go1.18beta1 linux/amd64
```
with
```
func TestSomething(t *testing.T) {
	assert.Nil(t, nil)
}
```
```
cannot use t (variable of type *testing.T) as assert.TestingT value in argument to assert.Nil: wrong type for method Errorf (have func(format string, args ...invalid type), want func(format string, args ...interface{}))
```

**Comment by brackendawson** [comment]
How are you running your build/test? I think this might be a dup of #1138

**Comment by jtagcat** [comment]
Whatever https://github.com/golang/vscode-go does.

Yea,
> I'm sorry for the hasty posting of the issue.

Interesting, that gh issue search did not find any matches, even with wide search termins.

**Comment by jtagcat** [comment]
Whatever https://github.com/golang/vscode-go does. I tested the Nightly version, can reproduce issue.

Yea,
> I'm sorry for the hasty posting of the issue.

Interesting, that gh issue search did not find any matches, even with wide search keywords.
