### ISSUE TITLE
[BUG] assert.New() is broken on go1.8

### ISSUE THREAD

**Issue by tubzby** [stretchr/testify#1167]
```golang
func TestFunc(t *testing.T) {
	assert := assert.New(t)
}
```

Error message:

[compiler InvalidIfaceAssign] [E] cannot use t (variable of type *testing.T) as assert.TestingT value in argument to assert.New: wrong type for method Errorf (have func(format string, args ...invalid type), want func(format string, args ...interface{}))

**Comment by luckytea** [comment]
Same for require require pkg

```
cannot use t (variable of type *testing.T) as require.TestingT value in argument to require.Equal: wrong type for method Errorf (have func(format string, args ...invalid type), want func(format string, args ...interface{}))compiler[InvalidIfaceAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#InvalidIfaceAssign)
```

go version go1.18 darwin/amd64
golang.org/x/tools/gopls v0.8.1

**Comment by Guilospanck** [comment]
Same here.

**Comment by brackendawson** [comment]
Works on 1.18 for me. Are you sure your editors are updated correctly? This looks like #1138 again.

**Comment by Guilospanck** [comment]
Yeah, for me now it's ok. Maybe vscode was taking time to update. But now there are no errors.

**Comment by tubzby** [comment]
After upgrading my gopls to v0.8.1, no more error.

**Comment by jan-xyz** [comment]
you need to re-compile or update gopls with go1.18. If you are using Homebrew to install gopls, run `brew reinstall gopls --install-from-sources`.

**Comment by muzfr7** [comment]
For me, It fixed my `VSCode` using `CMD + SHIFT + P` -> `Go: Install/Update Tools`

**Comment by KEdore** [comment]
I am gettiing a similar type of error when i try to run linters on my code using a pipeline.

**Comment by ckapilla** [comment]
> For me, It fixed my `VSCode` using `CMD + SHIFT + P` -> `Go: Install/Update Tools`

That's my kind of fix: 3k errors to zero errors with one click!

**Comment by dolmen** [comment]
This discussion doesn't seem relevant anymore. Closing.
