### ISSUE TITLE
Can testify suport html report for CI

### ISSUE THREAD

**Issue by jiuhuche120** [stretchr/testify#1170]

**Comment by fugkco** [comment]
Do you mean a coverage report? Please look into go test's coverage and `go tool coverage` e.g.:

```
go test -coverprofile=coverage.out ./...
go tool cover -html=coverage.out
```

This is not something for testify to implement.

**Comment by jiuhuche120** [comment]
Maybe it's similar to allue, I just want an html report to show the results of the test. testify’s test tips are great, but it is better to converge into an html report.

**Comment by brackendawson** [comment]
What do you mean by "testify's test tips"? Testify only uses [`testing.T.Logf`](https://pkg.go.dev/testing#T.Logf) (via several methods). This wouldn't be a testify feature, you could just use any tool that can turn go test output into html reports.
