### ISSUE TITLE
How to mock “os” package function calls in a test case at go

### ISSUE THREAD

**Issue by AaronTrazona** [stretchr/testify#1172]
I imported "os" package I want to mock the error result.

Is this possible?

**Comment by brackendawson** [comment]
No it is not possible, importing a package is not a function call and cannot return an error.

If you mean you want to mock a call to a function in the `os` package, then yes you can do that: https://stackoverflow.com/questions/42952191/is-it-possible-to-mock-a-function-imported-from-a-package-in-golang

**Comment by AaronTrazona** [comment]
Thanks @brackendawson !
