### ISSUE TITLE
Proposal: use go1.18 generics

### ISSUE THREAD

**Issue by OladapoAjala** [stretchr/testify#1176]
I believe a huge section of the code base would benefit from the newly added generics in go 1.18. This would reduce testify's heavy dependency on reflection and empty interfaces.

**Comment by brackendawson** [comment]
This would regress a lot of the assertions, `Equal()` for example currently works on types that aren't comparable. You win a compile time check that expected and actual are the same type, but you would still have to use `any` as the constraint and use reflection to compare things that aren't inherently comparable.

Try converting a few assertions on a branch and keep all the relevant tests passing, I think you'll find yourself performing gymnastics. I could be wrong though.

**Comment by OladapoAjala** [comment]
Weirdly I didn't get a notification for your response. I see what you mean,
