### ISSUE TITLE
assert/require.Contains should work for maps too

### ISSUE THREAD

**Issue by willfaught** [stretchr/testify#118]
`assert/require.Contains` should work for maps too.

For example:

    k := 1
    v := 2
    m := map[int]int{k: v}
    assert.Contains(t, m, k) // true

`assert/require.Contains` should check for map keys and not values because (aside from that obviously making the most sense) Go itself provides a way to test for key membership:

    v, ok := m[k]
    assert.True(ok)

**Comment by oryband** [comment]
:+1:
