### ISSUE TITLE
go-difflib is no longer maintained

### ISSUE THREAD

**Issue by mat285** [stretchr/testify#1187]
It appears that https://github.com/pmezard/go-difflib is no longer maintained, but is still a dependency of this project. Are there any plans to remove it/fork and maintain a copy of it?

**Comment by dolmen** [comment]
Duplicate of #1327.

**Comment by dolmen** [comment]
What are the issues with go-difflib that require fixing?

**Comment by brackendawson** [comment]
Duplicate of #1159
