### ISSUE TITLE
gopkg.in/yaml.v3 has unhandled exception

### ISSUE THREAD

**Issue by benjirewis** [stretchr/testify#1194]
`testify` [requires](https://github.com/stretchr/testify/blob/master/go.mod#L9) a pseudo-version of 3.0.0 for the `yaml.v3` library. That pseudo-version evaluates to < 3.0.0 and therefore triggers this [security advisory](https://github.com/advisories/GHSA-hp87-p4gw-j4gq). Can you upgrade the version of the `yaml.v3` library that you're using?

**Comment by ygworldr** [comment]
https://github.com/stretchr/testify/pull/1192
