### ISSUE TITLE
AssertNotCalled() panics because mutex is nil

### ISSUE THREAD

**Issue by gkdr** [stretchr/testify#1208]
hello,

thank you for your continued work on this library.

i have an issue that for some reason only came up today, but i believe this is a similar issue to #1206. i have one test which only checks that a function was not called using `AssertNotCalled()`, which now fails because the mutex is nil and testify panics.

i instantiate the mock using `new`, is that wrong?

i am willing to prepare a PR for you, but i am not sure what the fix is. in #1207, a check is added:
```go
	if m.mutex == nil {
		m.mutex = &sync.Mutex{}
	}
```

does this need to be added to all of `AssertNotCalled()`, `AssertCalled()`, `AssertNumberOfCalls()`? is that all or are there any other places?

**Comment by PrafulFP** [comment]
I think a fix is also needed for `IsMethodCallable` and `MethodCalled`.

**Comment by Kryvchun** [comment]
The same about `AssertNumberOfCalls`

**Comment by psmarcin** [comment]
Using `yourmock.Test` method before `yourmock.AssertNumberOfCalls` populates `mutex`. It's just temporary workaround because this change looks like breaking change for me.

**Comment by yurishkuro** [comment]
Having a similar issue - upgrading to 1.7.4 causes some tests to panic.

Just curious, what was the motivation for changing mutex to a pointer in #1182 ?  The PR did not provide any reasoning, and considering that the mocks are usually initialized as plain structs, having a pointer is asking for trouble.

**Comment by peczenyj** [comment]
> I think a fix is also needed for `IsMethodCallable` and `MethodCalled`.

Indeed, I have a m.Called() without On on my programs -- the called was not expected, should fail, not panic on nil reference

**Comment by boyan-soubachov** [comment]
Fixed in latest version (1.7.5), please confirm and let me know if all is good :)

**Comment by PrafulFP** [comment]
Working fine now. Thanks 👍🏻

**Comment by gkdr** [comment]
reverting the change to a pointer fixed the issue. thank you!
