### ISSUE TITLE
Incorrect Type: 

### ISSUE THREAD

**Issue by davitdarsalia** [stretchr/testify#1220]
Tried to use "assert" package  for testing Rest api.

Methods of assert package always throw an error message: "Cannot use 't' (type *testing.T) as the type TestingT Type does not implement 'TestingT'".

go 1.16

**Comment by matthiasgubler** [comment]
Can you provide a code example of this issue?

**Comment by davitdarsalia** [comment]
Even a simple example from documentation throws Incompatible type error (*testing.T)

` assert.Equal(t, "Something", object.Value)`

**Comment by matthiasgubler** [comment]
Sorry I wasn‘t clear. Can you provide a code example of a whole file including import statements, the whole test function etc.?

**Comment by davitdarsalia** [comment]
Passing t at assert.New() - `Cannot use 't' (type *testing.T) as the type TestingTType does not implement 'TestingT'need the method: Errorf(format string, args ...interface{})have the method: Errorf(format string, args ...any)`

`package handler

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestRefreshToken(t *testing.T) {
	assert := assert.New(t)

	res := newRefreshToken()

	if n := assert.NotNil(res); !n {
		t.Errorf("Incorrect. Return token is nil")
	}
}
`

**Comment by davitdarsalia** [comment]
`func TestRefreshToken(t *testing.T) {
	assert := assert.New(t)

	res := newRefreshToken()

	if n := assert.NotNil(res); !n {
		t.Errorf("Incorrect. Return token is nil")
	}

}`

**Comment by davitdarsalia** [comment]
Passing t at assert.New() - `Cannot use 't' (type *testing.T) as the type TestingTType does not implement 'TestingT'need the method: Errorf(format string, args ...interface{})have the method: Errorf(format string, args ...any)`

<img width="408" alt="Screenshot 2022-07-03 at 23 10 27" src="https://user-images.githubusercontent.com/79382138/177053973-30105720-a968-4431-ac7b-0f9475f33840.png">

**Comment by matthiasgubler** [comment]
Does this error message only appear in Goland? Have you already tried to run the test using
`go test ./...`?

I reconstructed the case in my local environment with Golang version 1.16 and using 1.17 here: https://go.dev/play/p/9Ju0KVs9vyS?v=goprev
and both are working fine.

Can you also please share your `go.mod` file, to inspect the dependencies and their versions.

**Comment by davitdarsalia** [comment]
I've tried to run  `go test ...` and `go test -v`. 
Test works great.
`github.com/BurntSushi/toml v1.1.0 // indirect
	github.com/fsnotify/fsnotify v1.5.4 // indirect
	github.com/go-playground/validator/v10 v10.11.0 // indirect
	github.com/google/go-cmp v0.5.8 // indirect
	github.com/mitchellh/mapstructure v1.5.0 // indirect
	github.com/pelletier/go-toml v1.9.5 // indirect
	github.com/pelletier/go-toml/v2 v2.0.2 // indirect
	github.com/rs/xid v1.4.0 // indirect
	github.com/sergi/go-diff v1.2.0 // indirect
	github.com/stretchr/testify v1.8.0 // indirect
	golang.org/x/crypto v0.0.0-20220525230936-793ad666bf5e // indirect
	golang.org/x/exp/typeparams v0.0.0-20220613132600-b0d781184e0d // indirect
	golang.org/x/net v0.0.0-20220607020251-c690dde0001d // indirect
	golang.org/x/sync v0.0.0-20220601150217-0de741cfad7f // indirect
	golang.org/x/sys v0.0.0-20220702020025-31831981b65f // indirect
	golang.org/x/tools v0.1.11 // indirect
	golang.org/x/tools/gopls v0.8.4 // indirect
	golang.org/x/vuln v0.0.0-20220701175437-1cec1460acbd // indirect
	honnef.co/go/tools v0.3.2 // indirect
	mvdan.cc/gofumpt v0.3.1 // indirect`

`require (
	github.com/dgrijalva/jwt-go v3.2.0+incompatible
	github.com/gin-contrib/sessions v0.0.5
	github.com/gin-gonic/gin v1.8.1
	github.com/go-redis/redis/v8 v8.11.5
	github.com/jmoiron/sqlx v1.3.5
	github.com/joho/godotenv v1.4.0
	github.com/lib/pq v1.10.5
	github.com/sirupsen/logrus v1.8.1
	github.com/spf13/viper v1.11.0
	github.com/thanhpk/randstr v1.0.4
)`

**Comment by davitdarsalia** [comment]
Only GoLand throws this warning. VsCode is okay with it. Thank you.

**Comment by matthiasgubler** [comment]
Yeah, Goland sometimes doesn't sync properly with the Workspace. It mostly helps to go to build it with `go build ./...` and then in Goland select File -> Invalidate Caches... -> Select all caches/logs/indexes -> Invalidate and Restart.

**Comment by davitdarsalia** [comment]
Invalidate and Restart solved this problem

**Comment by kyleshepherd** [comment]
I'm having this in VSCode currently, does anyone know how to fix it?

**Comment by davitdarsalia** [comment]
This might be related to GoLang extension for VsCode. Try installing a newer version or just reinstall it and restart editor. This might solve your issue.
