### ISSUE TITLE
[ISSUE] mockCall.Unset cause panic

### ISSUE THREAD

**Issue by hieunguyen1809** [stretchr/testify#1236]
Hi team, I'm using testify to testing my method but encounter this issue (It only occur if using matchedBy arg)
When I using mock following by example but got error when using mockCall.Unset().
playground: https://go.dev/play/p/oQ2sGSRCtbR

**Comment by lisitsky** [comment]
I've got the same trouble :(
Could you check and may be vote for my fix for this?
https://github.com/stretchr/testify/pull/1250

**Comment by at-syot** [comment]
For people who face this issue, i use this code 
```
	unset := func(call *mock.Call) {
		if call != nil {
			call.Parent.ExpectedCalls = []*mock.Call{}
		}
	}
	var caller *mock.Call
	unset(caller)
```
as temporary fix. you can try this to

**Comment by gordonlee** [comment]
> 

Just fyi, I put short snippet which only specific method would be deleted based on @at-syot 's code

```go
var unsetFn = func(call *mock.Call) {
	if call != nil {
		var newList []*mock.Call
		for _, c := range call.Parent.ExpectedCalls {
			if c.Method != call.Method {
				newList = append(newList, c)
			}
		}
		call.Parent.ExpectedCalls = newList
	}
}
```

**Comment by hugoboos** [comment]
Running in the same problem. A fix would be ﻿﻿﻿appreciated 😄
