### ISSUE TITLE
Mock Call Return Accepts Any Value

### ISSUE THREAD

**Issue by smarshall-spitzbart** [stretchr/testify#1251]
When [return](https://pkg.go.dev/github.com/stretchr/testify@v1.7.0/mock#Call.Return) is used in my tests to assert a return value to a mocked method, any asserted value is accepted by the tests. Am I using the tool incorrectly, or is this a bug (pretty serious one if so)? Example below, and thank you for the help.

```
type Foo interface {
	Method(int) int
}

type FooMock struct {
	mock.Mock
}

func (f *FooMock) Method() {
	f.OtherMethod(3)
}

// Returns what is given as input and logs a call for the mock handler
func (f *FooMock) OtherMethod(input int) int {
	args := f.Called(input)
	return args.Int(0)
}

func TestStuff(t *testing.T) {
	mockObj := FooMock{}
	mockObj.On("OtherMethod", 3).Return(77979).Once() // this should fail, 77979 is not returned!
	mockObj.Method()
	mockObj.AssertExpectations(t)
}
```
This test passes for me

**Comment by brackendawson** [comment]
`77979` is indeed returned, and then `Method()` swallows it. The value in the call to `Mock.Return()` is not "asserted" it is just what a correctly written mock method will return. I don't know what you are aiming to test with this, but that's definitely not the intended use of mock.

**Comment by smarshall-spitzbart** [comment]
Seems I was using the tool incorrectly, and now understand that ```Mock.Return()``` is specifying a return value. Imo the comment for ```AssertExpectations``` should be adjusted to not mention return values, as nothing related to returned values is ever asserted

**Comment by brackendawson** [comment]
The return value doesn't need to be asserted. If the mock was satisfied and `AssertExpectations()` returns `true` then the return value definitely was returned.
