### ISSUE TITLE
Feature request: jsonpath assertions

### ISSUE THREAD

**Issue by danielbprice** [stretchr/testify#1267]
It's very cumbersome to build asserts around JSON data in some tests, especially when the JSON data is complex and you just want to assert one or two facts about it.  It would be really great if there was a way to
make assertions directly using JSONPath (https://datatracker.ietf.org/doc/draft-ietf-jsonpath-base/).

https://github.com/steinfletcher/apitest-jsonpath shows an example of how one might extend an assertion package to support JSONPath.  However that library has an unknown license and is somewhat limited in scope to its parent "apitest" package.

Perhaps this should be a sub-package of or add-on to testify?  I'm not sure.  Thanks for your thoughts.

**Comment by divmgl** [comment]
Why not just use gjson to access values and then assert on it?

**Comment by dolmen** [comment]
Implementing this in testify itself would require adding dependencies.

This will not happen.

**Comment by twocs** [comment]
Although we might not want to introduce dependencies, it's straightforward to make a helper based on the assert.JSONEq code but swapping the final line from assert.Equal to assert.Subset.

```go
func JSONSubset(t *testing.T, list, subset string, msgAndArgs ...interface{}) (ok bool) {
	t.Helper()
	var expectedJSONAsInterface, actualJSONAsInterface interface{}

	if err := json.Unmarshal([]byte(subset), &expectedJSONAsInterface); err != nil {
		return assert.Fail(t, fmt.Sprintf("Expected value ('%s') is not valid json.\nJSON parsing error: '%s'", subset, err.Error()), msgAndArgs...)
	}

	if err := json.Unmarshal([]byte(list), &actualJSONAsInterface); err != nil {
		return assert.Fail(t, fmt.Sprintf("Input ('%s') needs to be valid json.\nJSON parsing error: '%s'", list, err.Error()), msgAndArgs...)
	}

	return assert.Subset(t, actualJSONAsInterface, expectedJSONAsInterface, msgAndArgs...)
}
```
