### ISSUE TITLE
Why use %#v and not %v?

### ISSUE THREAD

**Issue by Eloff** [stretchr/testify#127]
I find myself frequently comparing enum types and arrays of types, but the error message is a little obtuse:

        Error:          Not equal: []compiler.itemType{0x1, 0x2, 0x9, 0x2, 0x2, 0xa, 0xb, 0x2, 0x3, 0x0, 0x2, 0x3, 0x2, 0x3, 0xc} (expected
                                != []compiler.itemType{0x1, 0x2, 0x9, 0x2, 0x2, 0xa, 0xb, 0x2, 0x0, 0x2, 0x3, 0x2, 0x3, 0xc} (actual)

vs:

        Error:          Not equal: [Keyword Identifier StartOptions Identifier Identifier EndOptions StartFields Identifier AutoValue Identifier AutoValue Identifier AutoValue EndFields] (expected)
                                != [Keyword Identifier StartOptions Identifier Identifier EndOptions StartFields Identifier AutoValue Comment Identifier AutoValue Identifier AutoValue EndFields] (actual)

**Comment by Eloff** [comment]
Actually, one can define GoString() to customize %#v. Still it's interesting to know why %#v was chosen, so I'll leave this open.

**Comment by willfaught** [comment]
I imagine %#v is for cases where you don't know what the underlying type will be, like when dealing with interfaces. Knowing the specific type could help you track down the bug.

Is compiler.itemType a Stringer?

**Comment by Eloff** [comment]
That makes sense. Yeah, it's a Stringer, which puzzled me. Long story short %#v uses GoString() not String(). It's easy enough to define a GoString() method that just calls String().
