### ISSUE TITLE
Verify Interface Compliance

### ISSUE THREAD

**Issue by sekulicd** [stretchr/testify#1271]
Is there option to verify interface compliance like recommended in [here](https://github.com/uber-go/guide/blob/master/style.md#verify-interface-compliance).
Adding this would give compilation error when mocked interface is updated.

**Comment by antichris** [comment]
No. That kind of compile-time check is not something a run-time test framework, such as this project, can or should implement.

<details><summary>Furthermore...</summary>

It really is not that difficult to just add 

```go
var _ TheInterface = (*YourType)(nil)
```

to where you implement `TheInterface` with `YourType`.

That [documentation you linked][docs] is very clear on that. It even explains to use the zero value for non pointer implementations, e.g.:

```go
type MyIntError int

// This would abort compilation if [MyIntError] did not implement error.
var _ error = MyIntError(0)

func (e MyIntError) Error() string {
	return fmt.Sprintf("My int error #%v", int(e))
}
```
or
```go
type MyStringError string

// This would abort compilation if [MyStringError] did not implement error.
var _ error = MyStringError("")

func (e MyStringError) Error() string {
	return fmt.Sprintf("My string error %q", string(e))
}
```

There really is no need for third-party packages or libraries to be able do any of it. Although, there might be a linter/codegen type of tool that could help you with automating it; I have never needed so haven't looked for one.

Either way, all of that is out of the scope of a test framework.
</details>

I believe this issue can be closed.

[docs]: https://github.com/uber-go/guide/blob/master/style.md#verify-interface-compliance
