### ISSUE TITLE
Only check specific field value on struct slice? (contains)

### ISSUE THREAD

**Issue by NinoM4ster** [stretchr/testify#1272]
I'm trying to check if a struct slice contains a struct which has a specific field value, but I don't want to check the **whole** struct/all the fields at once.

This is how I'm currently doing it:

![image](https://user-images.githubusercontent.com/8485761/192843358-9d2341d5-de44-4860-9889-5a2789594be9.png)
(followers is a struct slice of a User struct which has ID among other fields)

I tried doing this but it didn't work:

![image](https://user-images.githubusercontent.com/8485761/192844880-37df38b4-9860-403f-b1ca-d02baac87d2d.png)

Is there a better way to do this? I looked through the entire documentation but couldn't find a function that does this.

Thanks!

**Comment by dolmen** [comment]
Related to #1432.
