### ISSUE TITLE
feature request: in delta assertion with time.Time

### ISSUE THREAD

**Issue by cra1nbow** [stretchr/testify#1277]
```go
assert.InDeltaMapValues(
  t,
  map[int]time.Time{2: now},
  value,
  float64(time.Second),
)
```

when assert like this, testify make error `Parameters must be numerical`.
Please let me know if you want further information.

**Comment by antichris** [comment]
What's the type of your `value`?

**Comment by cra1nbow** [comment]
Oh What I need to do is just converting type. I'll use this method. Thanks.

**Comment by antichris** [comment]
No problem, @cra1nbow. Although, I'm not at all saying it is the right way to do that. What I'm saying is that there are ways to work around testify not having a dedicated assertion for this.

Another, probably, somewhat more semantically correct approach could be

```go
delta := time.Second
want := map[int]time.Time{2: now}
got := value

a := assert.New(t)
if a.Len(got, len(want)) {
	for k, wantT := range want {
		if gotT, ok := got[k]; a.True(ok, `has "%v"`, k) {
			a.WithinDuration(wantT, gotT, delta, `entry "%v"`, k)
		}
	}
}
```
Or, if you're lazy like me (and the conventions of your team permit), you could `require` those conditions instead:
```go
// assignments omitted...

r := require.New(t)
r.Len(got, len(want))
for k, wantT := range want {
	gotT, ok := got[k]
	r.True(ok, `has "%v"`, k)
	r.WithinDuration(wantT, gotT, delta, `entry "%v"`, k)
}
```
Of course, there's like a million different ways to achieve the same effect, you just have to adopt what suits your use case the best.

**Comment by cra1nbow** [comment]
Second one is more attractive for me! Thanks for helps!
