### ISSUE TITLE
Cannot pass a bidirectional channel to a mocked method that's expecting a unidirectional channel argument

### ISSUE THREAD

**Issue by jcass8695** [stretchr/testify#1282]
Example; creating a wrapper interface around `time.Ticker`
```go
type Ticker interface {
	C() <-chan time.Time
	Reset(d time.Duration)
	Stop()
}

```

Then mocking it in the tests, something like:
```go
t.Run("...", func(t *testing.T) {
	c := make(chan time.Time)
	defer close(c)
	mockTicker := &mocks.Ticker{}
	mockTicker.On("C").Return(c)

	cache.Put("", "", time.Millisecond)
	c <- time.Time{}
	_, ok := cache.Get(key)

	assert.False(t, ok)
})
```

I want to test that the cache internally will remove the key once it has expired. The cache runs a cleanup every tick of the ticker. In the test, I need to advance the ticker by writing to the channel `c`. This causes a panic originating from the `mock.Ticker.C` method:

```
panic: interface conversion: interface {} is chan time.Time, not <-chan time.Time
```

The generated mock is:
```go
func (_m *Ticker) C() <-chan time.Time {
	ret := _m.Called()

	var r0 <-chan time.Time
	if rf, ok := ret.Get(0).(func() <-chan time.Time); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan time.Time) // <----- Panic occurs here
		}
	}

	return r0
}
```

I would expect to be able to pass a bidirectional channel as an argument, which is valid, compilable Go as shown [here](https://gobyexample.com/channel-directions)

**Comment by brackendawson** [comment]
I think you are expecting implied conversion to convert your bidirectional channel to a read channel based on the context, but in the code you've posted no such context is apparent for the compiler. `Return()` takes an `interface{}`, `Get()` returns an `interface{}` and `.(<chan time.Time)` is a type assertion, not a conversion.

You just need to explicitly convert the channel in your `Return()` call:
```go
mockTicker.On("C").Return((<-chan time.Time)(c))
```

**Comment by jcass8695** [comment]
Ah yep, the type conversion is what I was missing. Thanks @brackendawson 👍🏻
