### ISSUE TITLE
Asserting equal values yields unexpected result when comparing []string and []interface

### ISSUE THREAD

**Issue by weeco** [stretchr/testify#1286]
I would expect that the following test would succeed with `EqualValues` as the interface can be converted into strings:

```
assert.EqualValues(expectedValidationResult, overrideResult)
```

```
        	            	@@ -2111,3 +2111,3 @@
        	            	     (string) (len=4) "name": (string) (len=24) "source.bootstrap.servers",
        	            	-    (string) (len=18) "recommended_values": ([]interface {}) {
        	            	+    (string) (len=18) "recommended_values": ([]string) {
        	            	     },
```

I wonder whether there's an issue when comparing slices, but the GoDoc for the EqualValues function doesn't mention slices explicitly:

> // EqualValues asserts that two objects are equal or convertable to the same types
// and equal.
//
//    a.EqualValues(uint32(123), int32(123))

**Comment by brackendawson** [comment]
A slice of interface cannot be converted to a slice of string: https://go.dev/play/p/xmtStdIh84X

There are two reasons you can't do that:
1. `interface{}` cannot be converted to the type it contains, it can only be type asserted: https://go.dev/play/p/w6gFtPZvgNy
2. More fundamentally, slices cannot be converted to compatible types at all, you have to iterate over them converting every element: https://go.dev/play/p/mRc7kaXK8np
