### ISSUE TITLE
Add "ConvertableTo" Equals

### ISSUE THREAD

**Issue by pquerna** [stretchr/testify#129]
Related to #128 -- [ffjson](https://github.com/pquerna/ffjson) https://github.com/pquerna/ffjson/issues/85 were *incorrectly* relying upon the automatic type conversion in `assert.Equal`.

Is it reasonable to add a `ConvertableTo` or `SemiKindaEqual` to `assert` and `require`?

**Comment by tylerb** [comment]
Yes, this could be a good thing to add in a separate function to make it explicit.

Naming? `EqualValues`? `EqualNoTypes`?

**Comment by pquerna** [comment]
`EqualValues` sounds reasonable to me

**Comment by tylerb** [comment]
Agreed. Care you submit a PR for this issue?
