### ISSUE TITLE
Exposing the `common` struct as an interface?

### ISSUE THREAD

**Issue by Olshansk** [stretchr/testify#1291]
I recently found myself doing the following in one of our test suites

```go
func Foo[T testing.T | testing.B | testing.F](t *T) *Bar {
   // test prep stuff

	var cleanupFn func(func())
	switch any(t).(type) {
	case *testing.T:
		cleanupFn = any(t).(*testing.T).Cleanup
	case *testing.B:
		cleanupFn = any(t).(*testing.B).Cleanup
	case *testing.F:
		cleanupFn = any(t).(*testing.F).Cleanup
	default:
		log.Fatalf("Error: unsupported type %T", t)
	}
	
	cleanupFn(func(){
      // test cleanup stuff
    })
```

The cleanup function is common to all of these and is part of the `common` struct, which is embedded in each of `testingT`, `testing.B`, and `testing.F`.

![Screen Shot 2022-10-31 at 11 13 18 AM](https://user-images.githubusercontent.com/1892194/199079781-2f6fa4ad-2e9e-4893-9720-92b98670b6a6.png)

I was wondering if `common` could potentially be exposed as an interface?

I'm happy to take a first stab at the PR if this is something the library mainteras would be open to, unless there's a technical reason this shouldn't be the case. Please lmk!

**Comment by brackendawson** [comment]
This is a request for the Go standard library, not for testify.

**Comment by Olshansk** [comment]
@brackendawson You are correct. Here is the link: https://github.com/golang/go/blob/ad5d2f64fbb90dd13c4587aa5bf2ed3c86a6dec2/src/testing/testing.go#L584

I opened the issue at https://github.com/golang/go/issues/56516 and will be closing out this one.
