### ISSUE TITLE
Assertion Library

### ISSUE THREAD

**Issue by khafidprayoga** [stretchr/testify#1303]
testify is a package that is used to simplify assertions in unit testing.
How to use some of these methods
e.g. when checking ```int(1) == int(1)```

in my source code i want to say like this  ```is.Equal(condition, inputCheck)``` with type and value check,
do you have any other library suggestions?

For now, the testify method takes the interface parameter ```(t TestingT)```

**Comment by brackendawson** [comment]
Sure, you can do that: https://go.dev/play/p/4BcL4rYX36-
```go
package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestTestify(t *testing.T) {
	is := assert.New(t)

	is.Equal(int(7), int(7))
	is.Equal(int(7), uint(7))
}
```

**Comment by khafidprayoga** [comment]
@brackendawson  nice example, but how about performance when i check with 
```is.Equal(int(1),int(1)) ```versus ```1 == 1```
