### ISSUE TITLE
Strict Assert Expectations

### ISSUE THREAD

**Issue by Etienne-M** [stretchr/testify#1321]
Somewhat related to https://github.com/stretchr/testify/issues/566

The default behaviour of throwing a panic when a call is not defined is not sufficient in some cases. In our specific use-case, we had to make our code "panic-resilient", so this is not enough to make our tests fail.

At the moment, the only way we can check if our mock was never called is to `AssertNotCalled` on each method one by one. This is undesirable because the test needs to be updated every time a method is added, or the number of arguments changes.

If we could do something like `myMock.StrictAssertExpectations(t)`, that would make the test much more lightweight and easy to maintain. Something that would check if all expectations have a corresponding call, but also that all calls have a corresponding expectation. This way, we could simply declare no calls, and do a `.StrictAssertExpectations(t)` at the end of the test.

**Comment by brackendawson** [comment]
> we had to make our code "panic-resilient"

I doubt you had to, I think you chose to.

Anyway, what you are requesting pretty much already exists, just use [mock.Mock.Test()](https://pkg.go.dev/github.com/stretchr/testify/mock#Mock.Test). If you call `myMock.Test(t)` at the start of each test then unexpected method calls will immediately fail your test.

**Comment by Etienne-M** [comment]
> If you call `myMock.Test(t)` at the start of each test then unexpected method calls will immediately fail your test.

Thanks for sharing! I'll look into it 🙂
