### ISSUE TITLE
Assert ErrorIs(): failure message shows identical strings when errors differ only by memory address.

### ISSUE THREAD

**Issue by tscales** [stretchr/testify#1323]
#### context
the Assert.ErrorIs() method seems to expect that if the errors are not equal that the error chain will differ. This however is not the case when the errors are identical but differ in memory address.  

##### current result

```
Error:      	Target error should be in err chain:
                 expected: "ERROR"
        	 in chain: "ERROR"
Test:       	TestAssertIs
```

##### expected result
the scenario described should still fail, but since the chains are identical, It might be helpful to have a different message.

##### files affected
https://github.com/stretchr/testify/blob/v1.8.1/assert/assertions.go#L1794-L1813

##### reproduce

```Go
type A struct {
	Value bool
}

func (a *A) Error() string {
	return "ERROR"
}

var aErr = A{}

func returnErr() error {
	return &aErr
}
func TestAssertIs(t *testing.T) {
	err := returnErr()
	target := A{}
	assert.ErrorIs(t, err, &target)
}

```

**Comment by zalgonoise** [comment]
You're able to reproduce this assertion without `testify`, where you will find the same outcome.

In reality, this would not be an appropriate use of `errors.Is()` in the first place, as the error is a pointer. You will find situations like this on `encoding/json` errors, `net` errors and many others.

For these, the best course of action is to use `errors.As` however possible, and then match the contents of the error (if required).

See: https://go.dev/play/p/hkLGhfNZ2w9

With `errors.Is()` the check still fails, while with `errors.As` you're able to cast the error into the target value, where you're also able to match / verify its elements if exported.

Regarding `testify`, I would suggest trying out the same approach as above, with `require.ErrorAs`

**Comment by dolmen** [comment]
I confirm what @zalgonoise wrote above.
