### ISSUE TITLE
Allow to set a name for Suite

### ISSUE THREAD

**Issue by d3nnxs** [stretchr/testify#1326]
Hi,

Maybe I'm wrong with it but it would be very nice to have a possibility to change or decorate the suite name. If I see it correctly suite name is automatically selecting the function name.  For example, I have a Test struct which is used several times with different attribute content. 

golden.go
```go
type TemplateGoldenTest struct {
	suite.Suite
	Release         string
	Namespace       string
}


func (s *TemplateGoldenTest) TestContainerGoldenTestDefaults() {
	...
}
``` 

chart_test.go
```go
for _, template := range listTemplates {
			suite.Run(t, &golden.TemplateGoldenTest{
				Release:        template.name,
				Namespace:      template.namespace,
			})
		}
```

In test output its hard to differentiate between the different tests.

![image](https://user-images.githubusercontent.com/116011093/212773035-8d1d8fad-6ecc-4282-900a-2fc62aab6d99.png)

I appreciate any feedback. Thanks.

**Comment by kulti** [comment]
`suite.Run` is a top-level call for test. So it have the same name as Test-function.

If you want to run several suites inside one test just wrap it with `t.Run` with suitable names. Like this:
```
for _, template := range listTemplates {
	t.Run(template.name, func(t *testing.T) {
		suite.Run(t, &golden.TemplateGoldenTest{
			Release:        template.name,
			Namespace:      template.namespace,
		})
	})
}		
```

**Comment by dolmen** [comment]
The workaround suggested above seems good enough.
