### ISSUE TITLE
deps: go-difflib is EOL

### ISSUE THREAD

**Issue by satish-suradkar** [stretchr/testify#1327]
`github.com/pmezard/go-difflib v1.0.0` is an EOL.

Any plan to use an alternative for this?

**Comment by brackendawson** [comment]
Probably something else that go-cmp would be suitable for. Ref #535 

For this issue it's not a breaking change.

**Comment by dolmen** [comment]
A project not maintained doesn't mean the code doesn't work as is.

Do you see any issue that are relevant to testify?

**Comment by brackendawson** [comment]
Duplicate of #1159
