### ISSUE TITLE
assert: add ErrorRegexp

### ISSUE THREAD

**Issue by ybrustin** [stretchr/testify#1328]
Similar to `ErrorContains` (#1022), there would be great to have the ability to specify error message as regexp
e.g. `"value .+ too low"`.
If you agree it's useful, I can create a PR.

**Comment by dolmen** [comment]
I personnally think that tests that enforce the error message are generally a bad practice. Tests should either check for a particular error value (`ErrorIs`) or an error type (`ErrorAs`). 

I don't want that testify makes easier such bad practice.

**Comment by dolmen** [comment]
`assert.ErrorRegexp(t, pattern, err, msgAndArgs...)` can be written like this in user code:
```go
if err != nil {
    assert.Regexp(t, pattern, err.Error(), msgAndArgs...)
}
```

I don't think it is worth extending testify for this case which is a bad practice.

**Comment by ybrustin** [comment]
The proposition was to generalize _existing_ ErrorContains, without adding any _new_ bad practices.
But OK 🙂

**Comment by prashantv** [comment]
+1 to adding `ErrorRegex`, I was looking for exactly the same method. While it is preferable to use `ErrorAs` or `ErrorIs`, it's not enough, especially when errors are generated by external systems (e.g., a HTTP 400 with a body that's returned as an error).
