### ISSUE TITLE
EqualValues panics when second arg is nil

### ISSUE THREAD

**Issue by willfaught** [stretchr/testify#135]
`assert.EqualValues(t, b, nil)` (b not nil) panics:

    panic: reflect: nil type passed to Type.ConvertibleTo [recovered]
	    panic: reflect: nil type passed to Type.ConvertibleTo

I'm guessing TypeOf(nil) returns nil?

**Comment by sivagollapalli** [comment]
It panics when we do `assert.EqualValues(t, nil, b)`. I have handled both conditions on my PR.
