### ISSUE TITLE
matchedBy called multiple times during the test execution

### ISSUE THREAD

**Issue by karakanb** [stretchr/testify#1364]
I have the following simple test to demonstrate the behavior:
```golang
package main

import (
	"testing"

	"github.com/stretchr/testify/mock"
)

type myMock struct {
	mock.Mock
}

func TestFoo(t *testing.T) {
	m := &myMock{}

	m.On("test", mock.MatchedBy(func(value int) bool {
		println("matching for", value)
		return value == 1
	}))

	m.MethodCalled("test", 1)
	m.AssertExpectations(t)
}
```

https://go.dev/play/p/JjZqBDdSelo

The output of this test is this:
```
=== RUN   TestFoo
matching for 1
matching for 1
    prog_test.go:24: PASS:	test(mock.argumentMatcher)
--- PASS: TestFoo (0.00s)
PASS
```

as you can see for some reason the matching function is called twice. this means for tests that are asserting external side effects, relying on the number of matches becomes unreliable. 

in my case, I have a scenario where a bunch of goroutines are supposed to call the function, and I need to be able to change some additional state somewhere to simulate specific scenarios; however, because the argument matcher function is invoked multiple times with the same input this requires additional mechanisms to tackle this, effectively introducing more logic to the tests.

is this the expected behavior?

**Comment by brackendawson** [comment]
This is expected behaviour, the job of your MatchedBy function is to indicate to the test harness whether the call matches or not only. It is not safe to use to emulate side-effects of the call, for that you should use [Run](https://pkg.go.dev/github.com/stretchr/testify/mock#Call.Run).

**Comment by mikegleasonjr** [comment]
> I don't understand :(
> 
> Where is the emulation of the side-effect of the call ?

For posterity, let's say you read an `io.Reader` in a `mock.MatchedBy` handler, then on the next call you won't have the same result (the reader would likely return an `EOF` error). Hence the side effect.

The way I understand `mock.MatchedBy` is that it is called every time the mock is actually called and then a final time when `AssertExpectations` is called. Hence the "multiple times".
