### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Seklfreak** [stretchr/testify#1374]
Hello,

it would be great if we could create a new release version/tag to include the latest commit https://github.com/stretchr/testify/commit/c5fc9d6b6b21ea89be8480c0dc35e2977ab988f6.
The change can be very useful for some testing scenarios.

Thank you.

**Comment by HaraldNordgren** [comment]
Agreed. I think we should make a new release!

Ping @boyan-soubachov

**Comment by boyan-soubachov** [comment]
I just tagged with v1.8.3 :)

**Comment by Seklfreak** [comment]
Thank you!!! 🙏
