### ISSUE TITLE
AssertExpectations(t) vs On() panic.

### ISSUE THREAD

**Issue by lromor** [stretchr/testify#1402]
Hi, 

I would like to check if I'm misusing the library.  This is the mock snippet you provided.
```
  // setup expectations
  testObj.On("DoSomething", 123).Return(true, nil)

  // call the code we are testing
  targetFuncThatDoesSomethingWithObj(testObj)

  // assert that the expectations were met
  testObj.AssertExpectations(t)
```

Without any  testObj.AssertExpectations(t), given a wrong mock setup, for instance On("DoSomething", 456)
If 456 was never used as argument, testify Mock panics.

What is the reason then of running AssertExpectations(t) if the expectations are already [checked automatically](https://github.com/stretchr/testify/blob/v1.8.4/mock/mock.go#L492) ?

**Comment by brackendawson** [comment]
You can now also have unexpected calls not panic by first doing `testObj.Test(t)`, so that mock has a reference to `t` and can fail the test rather than causing a panic.

**Comment by lromor** [comment]
That's good to know! Thank for clarifying! :)
