### ISSUE TITLE
TestEventuallyIssue805: flaky test

### ISSUE THREAD

**Issue by dolmen** [stretchr/testify#1411]
We still have flaky tests. It looks like #865 did not fix everything related to #805 and #835.
```console
$ go test -race -failfast -count 100 -run TestEventuallyIssue805 ./assert 
--- FAIL: TestEventuallyIssue805 (0.00s)
    assertions_test.go:2815: 
        	Error Trace:	
        	Error:      	Should be false
        	Test:       	TestEventuallyIssue805
FAIL
FAIL	github.com/stretchr/testify/assert	0.451s
FAIL
```

Cc: @snebel29

**Comment by dolmen** [comment]
The test uses `time.After(time.Millisecond)`. 🤦 

But [time is not a synchronization primitive](https://xeiaso.net/blog/nosleep).

**Comment by brackendawson** [comment]
This dinged us in this PR too: https://github.com/stretchr/testify/actions/runs/5596433158/jobs/10233448218#step:4:1567
