### ISSUE TITLE
Feature request: assert: Add flag to call t.FailNow() upon any assertion failure.

### ISSUE THREAD

**Issue by phemmer** [stretchr/testify#142]
Occasionally when writing tests, I run across a scenario where I'm testing multiple conditions, and each test depends on the success of the previous test. Right now I basically have to look at the return value of each `assert.*` call, and `return` if false.

I think it would be nice to be able to create an `assert.Assertions` object with a `FailImmediately` flag, so that when any assertion fails, `t.FailNow()` is called.

**Comment by nelsam** [comment]
See the [require](http://godoc.org/github.com/stretchr/testify/require) sub-package

**Comment by phemmer** [comment]
Doh! sorry, I completely missed that package.
Just curious, how come that was implemented as a separate package, and not just a flag on `Assertions`? Seems like a flag would be a lot simpler.

**Comment by nelsam** [comment]
Eh, they both require similar logic; the flag would probably have been more intuitive.  I think the reason for the separate package is that the recommended method of using this library involves overriding an import with a variable:

```go
assert := assert.New(t)
require := require.New(t)
```

As opposed to:

```go
require := assert.NewFailImmediately(t) // this line *must* come first, because the next line
                                        // overrides the package name with a variable.
assert := assert.New(t)
```

**Comment by willfaught** [comment]
I would say the require package reads better and makes the intent clear:

    require.Equal(t, a, b)

vs

    assert.Equal(t, a, b) // what does this do?
