### ISSUE TITLE
Clarify documentation of `assert.Eventually`/`assert.EventuallyWithT`

### ISSUE THREAD

**Issue by cszczepaniak** [stretchr/testify#1443]
The documentation states:

```go
// Eventually asserts that given condition will be met in waitFor time,
// periodically checking target function each tick.
```

This is a bit ambiguous: does it call the condition function every tick, regardless of whether the previous one finished, or does it wait for the tick _between_ executions of the condition function? (It's actually neither of these)

Conditions cannot overlap as shown in [this test](https://go.dev/play/p/pfPEiQ-6um7). Based on the behavior of the implementation, it would be more precise to say the following:

```go
// Eventually asserts that the given condition will be met in waitFor time. The given condition 
// func is checked periodically. It will be checked every tick unless the execution of the condition 
// takes longer than one tick. If so, it will be called again on the next multiple of tick after it returns.
```

**Comment by st3penta** [comment]
Based on the discussion in [this PR](https://github.com/stretchr/testify/pull/1534) i think this issue could be closed, right?

**Comment by arjunmahishi** [comment]
Yes. Thanks for helping close this @st3penta!
