### ISSUE TITLE
assert: EqualValues does not check for overflows

### ISSUE THREAD

**Issue by vispariana** [stretchr/testify#1462]
When asserting two numeric values with EqualValues, it passes if one is the overflowed value of the other.

example: https://go.dev/play/p/KZsFh7FnBVc

```go
func TestEqualValues(t *testing.T) {
	var a int8 = 14
	var b int = 270
	assert.Equal(t, b, a)       // fails because of type mismatch
	assert.EqualValues(t, b, a) // passes
}
```

**Comment by tscales** [comment]
https://github.com/stretchr/testify/blob/882382d845cd9780bd93c1acc8e1fa2ffe266ca1/assert/assertions.go#L161

Go Allows for Ints to converted to Int8s, hence the `ConvertibleTo` method returns true. A check would probably needed to be added that the Value of Expected > maxSize of the actual type before doing the DeepEqual call.

**Comment by vispariana** [comment]
> https://github.com/stretchr/testify/blob/882382d845cd9780bd93c1acc8e1fa2ffe266ca1/assert/assertions.go#L161
> 
> Go Allows for Ints to be converted to Int8s, hence the `ConvertibleTo` method returns true. A check would probably needed to be added that the Value of Expected > maxSize of the actual type before doing the DeepEqual call.

How about checking it both ways instead of looking at max size?

assume we have `var a A` and `var b B`. if `A` is convertible to `B` then `B` is also convertible to `A`. So maybe we can just check if: 
`reflect.DeepEqual(expectedValue.Convert(actualType).Interface(), actual) && reflect.DeepEqual(actual.Convert(expectedValue.Type()).Interface(), expectedValue)`

**Comment by tscales** [comment]
> assume we have `var a A` and `var b B`. if `A` is convertible to `B` then `B` is also convertible to `A`. So maybe we can just check if: `B(a) == b && A(b) == a`

var b can't be assumed convertible in all cases. For example: when `a` is an `int` and `b` is a `string`

https://go.dev/play/p/BKML-vPu4l_N

**Comment by vispariana** [comment]
I didn't know that conversion existed. Thank you!
I still believe that's the way to go though. If a and b are not convertible to each other, they are not "EqualValues". That's testify/assert's the current approach, because no order is implied on the two parameters, and there is some inconsistency here:

https://go.dev/play/p/XaCM39GdJum

So I think we'd be fine with adding a reverse convertibility check to prevent the panic you mentioned.
