### ISSUE TITLE
[Bug] assert.Same returns incorrect result when any type is an empty struct

### ISSUE THREAD

**Issue by cemkurulay** [stretchr/testify#1463]
For example the code below returns `false` where instead it should return `true`

```
func TestFoo(t *testing.T) {
	c := context.Background()
	require.Same(t, c, c)
}
```

context.Background() is an empty struct

**Comment by tscales** [comment]
`assert.Same` expect pointer values. 
https://github.com/stretchr/testify/blob/master/require/require.go#L1848-L1862

specifically, this is where the code is returning false. 
https://github.com/stretchr/testify/blob/master/assert/assertions.go#L482-L484

If you update your example with `require.Same(t, &c, &c)` your test should pass.
