### ISSUE TITLE
[Feature Request] Assert Type Only

### ISSUE THREAD

**Issue by saurabh-kushwah** [stretchr/testify#1472]
It's good to have an assert method that only checks for type. One scenario is when we want to check if unwrapped error types are the same.

```go
// current
func AssertError(t *testing.T, wantErr bool, expected, actual error) {
	require.Equal(t, wantErr, actual != nil, "error: %+v", actual)

	if !wantErr {
		return
	}

	var apiErr smithy.APIError

	if errors.As(actual, &apiErr) {
		switch exp := apiErr.(type) {
		case *types.ConditionalCheckFailedException:
			act, ok := expected.(*types.ConditionalCheckFailedException)
			require.True(t, ok, "error type mismatch")
		}
	} else {
		t.Fatalf("error not aws error: %+v", actual)
	}
}


// proposal
require.ErrorTypeEqual(t, err, &types.ConditionalCheckFailedException{})
```

Mostly, this method can be introduced for error types only, which would unwrap the error and match the underlying type.

I'm happy to raise a pull request if it makes sense.

**Comment by tscales** [comment]
Unless I'm misunderstanding your request: you can already use `errors.As` with a wrapped error against an unwrapped target.

https://go.dev/play/p/JPCVMrapuhz

**Comment by saurabh-kushwah** [comment]
thanks @tscales!

the linked code snippet make sense, i got the second parameter wrong.

```go
type AwsError struct {
	code int32
}

func (se *AwsError) Error() string {
	return "aws error"
}

func Test_Custom(t *testing.T) {
	err := errors.Wrap(&AwsError{}, "wrapper")

	var se error = &AwsError{}
	require.ErrorAs(t, err, &se)
}
```
