### ISSUE TITLE
How do I make tests coverage?

### ISSUE THREAD

**Issue by abdyek** [stretchr/testify#1475]
Hi everyone,

I want to show my tests coverage for codes. But -cover flag doesn't work correctly. It return:

```sh
$ go test ./tests/lib -cover -count=1

ok  	e.com/e/tests/lib	0.003s	coverage: [no statements]
```

Is there any way to show test coverage with Testify library ?

**Comment by damiensedgwick** [comment]
Hey @abdyek

Are you able to show any code that would help reproduce what you are experiencing?

I went ahead and created a [Demo Repo](https://github.com/damiensedgwick/go-code-cove) showing how you can use code cove and how to see your reports in the browser.

From what you have shared, it looks like there are no statements to be tested within your project but this could obviously be wrong. It is hard to tell without seeing anything else.

Lastly, I don't believe that this is a bug within the testify module (if you are indeed experiencing a bug) but maybe with the code testing module within Go itself.

Happy to try and help you out further should you need it 🙂

**Comment by abdyek** [comment]
Hi @damiensedgwick ,

Firstly, Thank you for reply

I give some information of my project structure.

Below codes is an example to show my project directory structure.

```bash
$ tree
.
├── go.mod
├── go.sum
├── lib
│   └── sum.go
├── main.go
└── tests
    └── lib
        └── sum_test.go

3 directories, 5 files
```

lib/sum.go
```go
package lib

func Sum(x int, y int) int {
    return x + y
}

func Dif(x int, y int) int {
    return x - y
}
```
tests/lib/sum_test.go
```go
package lib

import (
    "testing"

    "e.com/e/lib"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/suite"
)

type SumTestSuite struct {
    suite.Suite
}

func (suite *SumTestSuite) TestSum() {
    num1 := 5
    num2 := 6

    assert.Equal(suite.T(), 11, lib.Sum(num1, num2))
}

func TestSumTestSuite(t *testing.T) {
    suite.Run(t, new(SumTestSuite))
}
```

```bash
go test -cover ./...
?       e.com/e    [no test files]
?       e.com/e/lib    [no test files]
=== RUN   TestSumTestSuite
=== RUN   TestSumTestSuite/TestSum
--- PASS: TestSumTestSuite (0.00s)
    --- PASS: TestSumTestSuite/TestSum (0.00s)
PASS
coverage: [no statements]
ok      e.com/e/tests/lib    0.002s    coverage: [no statements]
```

Must I storage test files with them code files on same path for using coverage?

**Comment by damiensedgwick** [comment]
Hi @abdyek 

I think your project structure may have something to so with it.

If I copy your structure and run the tests I get the following output:

```
go test -cover ./...
?   	github.com/damiensedgwick/code-cov/lib	[no test files]
ok  	github.com/damiensedgwick/code-cov	(cached)	coverage: 66.7% of statements
ok  	github.com/damiensedgwick/code-cov/tests/lib	(cached)	coverage: [no statements]
```

However, I've I change the structure so that it now looks like this:

```
tree
.
├── README.md
├── cover.out
├── go.mod
├── go.sum
├── image.png
├── lib
│   ├── sum.go
│   └── sum_test.go
├── main.go
└── main_test.go

2 directories, 9 files
```

Note I have moved the test file to be collocated with `sum.go`

Then when I run the tests I get the following output:

```
go test -cover ./...
ok  	github.com/damiensedgwick/code-cov	(cached)	coverage: 66.7% of statements
ok  	github.com/damiensedgwick/code-cov/lib	0.285s	coverage: 50.0% of statements
```

I think if you move your test file so that it is within your lib directory, it should then pick up your tests, statements and coverage correctly.

**Comment by dolmen** [comment]
This question doesn't seem to be specific to Testify, and be more about Go testing in general. Please spare the limited time of Testify maintainers.

So please ask on Stackoverflow, on Reddit (r/golang) or on Gophers Slack (channel #testing).

**Comment by dolmen** [comment]
This question doesn't seem to be specific to Testify, and be more about Go testing in general. Please spare the limited time of Testify maintainers.

So please ask on Stackoverflow, on Reddit (r/golang) or on Gophers Slack (channel #testing).

**Comment by damiensedgwick** [comment]
@dolmen I get your frustration but saying things like

> Please spare the limited time of Testify maintainers. This project already has 260 issues opened. Do your think that adding a 261th not specific to Testify helps?

Is slightly passive aggressive when someone is simply looking for help. They may not have understood that it was not Testify specific to begin with.
