### ISSUE TITLE
Error message on Len() assumes string 

### ISSUE THREAD

**Issue by kevinburkesegment** [stretchr/testify#1482]
This error message in `assert.Len` assumes that whatever you are asserting a length about can be formatted with the `%s` format string. 

```go
	if l != length {
		return Fail(t, fmt.Sprintf("\"%s\" should have %d item(s), but has %d", object, length, l), msgAndArgs...)
	}
```

If you look at the failure in e.g. https://drone.grafana.net/grafana/dskit/3189/1/4, I believe this is a []uint32, which is being formatted as `"[%!s(uint32=2452015680) %!s(uint32=2476020736)]"`. 

I think the `%v` format string might be a better fit.

**Comment by dolmen** [comment]
@kevinburkesegment Could you submit a patch?

If you submit an MR I will be able to merge it.
However if I do the MR myself I will not be able to merge it because, despites being a maintainer, I need another maintainer to validate it, but all other maintainers are not responsive.

**Comment by dolmen** [comment]
Reproducer: https://go.dev/play/p/xH-RSrn8HP6

```go
func Test(t *testing.T) {
	assert.Len(t, [...]int{1, 2, 3}, 1)
}
```

```
=== RUN   Test
    prog_test.go:10: 
        	Error Trace:	/tmp/sandbox2682030218/prog_test.go:10
        	Error:      	"[%!s(int=1) %!s(int=2) %!s(int=3)]" should have 1 item(s), but has 3
        	Test:       	Test
--- FAIL: Test (0.00s)
FAIL
```

**Comment by fgimian** [comment]
An interesting issue I'm experiencing due to this issue is that no error is printed at all when the string representation of the slice is too long:

```
=== RUN   TestGetProducts
    products_test.go:48:
                Error Trace:    C:/Users/Fots/source/downloads/api/products_test.go:48
                Error:
                Test:           TestGetProducts
--- FAIL: TestGetProducts (0.01s)
```

In my case, the string representation had 248,649 characters.

Cheers
Fotis
