### ISSUE TITLE
assert: add `ContainsFunc` to check a slice by func assertion

### ISSUE THREAD

**Issue by SirSova** [stretchr/testify#1486]
The function removes additional complexity (`for`) and works as Find element by passed callback.
In my case, I can't use regular `Contains` assertion because I need to check only several fields and the others are generated randomly. Usually, I bypass the problem by iterating elements and `if`-s + calling `assert.Fail`/ `testing.T.Error()` manually. The new assertion allows writing the comparison function outside and avoiding nesting.
The suggested name: `ContainsFunc` / `MatchFunc` / `ElementMatch` / `ExistsFunc`
Example:
```go
func ContainsFunc(t, list interface{}, comp /*func(element interface{}) bool*/ interface{}, msgAngArgs ...interface{})

// simple example:
assert.ContainsFunc(t, []string{"Hello", "World"}, func(word string) { return len(word) == 3 }, "should contain the word with length 3")

// complex example:
type FooBar struct {
    foo string
    bar int
}
assert.ContainsFunc(t, 
    []FooBar{
        { foo: "One", bar: 1 },
        { foo: "Two", bar: 3 },
    },
    func (el FooBar) bool { return len(el.foo) == el.bar },
    "should contain element with \"foo\" length equal \"bar\"",
)
```

**Comment by dolmen** [comment]
Go 1.21 has the `slices` package with the `ContainsFunc` function. It uses generics, so it does full type matching of the slices elements with the func signature.

It is easy and very readable to rewrite your use case with `slices.ContainsFunc`:

See https://go.dev/play/p/WZYIFM7biaK

```go
	assert.True(t,
		slices.ContainsFunc(
			[]FooBar{
				{foo: "One", bar: 1},
				{foo: "Two", bar: 3},
			},
			func(el FooBar) bool { return len(el.foo) == el.bar },
		),
		"should contain element with \"foo\" length equal \"bar\"",
	)
```

So I don't think we do not need to add a `ContainsFunc` in Testify.

**Comment by dolmen** [comment]
Rejected.
