### ISSUE TITLE
How to assert pointers?

### ISSUE THREAD

**Issue by ifraixedes** [stretchr/testify#150]
I cannot find how to assert memory addresses (pointers).
I'm wondering if it has been done intentionally because to compare two pointers is that easy as using an if statement.

**Comment by ernesto-jimenez** [comment]
@ifraixedes `assert.Equal` should work. If you were looking for something different please let me know :)

**Comment by ifraixedes** [comment]
@ernesto-jimenez  thanks, I think that I realised about it long time ago, but I forgot that I had opened this issue.
