### ISSUE TITLE
Assert: go test output shows subtests that fail as PASS

### ISSUE THREAD

**Issue by Anacardo89** [stretchr/testify#1521]
When running a test with various subtests with t.Run(), set to fail, the test itself fails, but the substests all show as passed in the end, so there's no quick way of checking which subtest failed, apart from checking the line  in the editor.

This doesn't happen if using the std library instead of assert

![image](https://github.com/stretchr/testify/assets/20592598/01b7305e-4ff5-468e-ab9e-75f1e11fb84f)

![image](https://github.com/stretchr/testify/assets/20592598/81396091-2c57-42ff-ab32-344b3c6ac99e)

Without t.Parallel() it gets easier to tell which subtest failed, since they fail as they're called, but that's a strenuous limitation.

![image](https://github.com/stretchr/testify/assets/20592598/81e75cd5-bdb1-49df-b264-1b46f65e725a)

**Comment by tscales** [comment]
You're basically on the right track. The top level `testing.T` that you pass in to `assert.New` and the testing.T created when invoking `t.Run` are different. In your first example, no assertions are made against your subtest so its reports passing. You would basically have to do something like this. 

```Go
func TestNotNil(t *testing.T) {
	a := assert.New(t)
	t.Run("Test Not Empty", func(t *testing.T) {
	    passed := a.NotNil(t)
                if !passed {
                    t.Fail()
                }
	})
}
```

but as you discovered, you can skip using `assert.New` all together.
