### ISSUE TITLE
`YAMLEq` does not validate YAML

### ISSUE THREAD

**Issue by pauhull** [stretchr/testify#1522]
`YAMLEq` does not check if passed strings have valid YAML syntax. This leads to the following test passing:
```go
func TestYAML(t *testing.T) {
	json := `{ "foo": "bar", "baz": 42 }`
	assert.YAMLEq(t, json, json)
}
```

This is useful for the `expected` parameter, because it allows to check against JSON schemas, but IMO `actual` should be validated.

**Comment by hendrywiranto** [comment]
Hi!

as far as I know json is a valid yaml syntax [reference](https://www.redhat.com/en/topics/automation/what-is-yaml#:~:text=YAML%20is%20also%20a%20superset,the%20structure%20and%20indicate%20nesting.)

and for the [code](https://github.com/stretchr/testify/blob/master/assert/assertions.go#L1748) itself, it use `yaml` library and it return error when `actual` or `expected` is not a valid yaml based on the lib

so your case here is expected, hope this helps... cheers!
