### ISSUE TITLE
Is it possible to assert for multiple allowed values?

### ISSUE THREAD

**Issue by red8888** [stretchr/testify#1523]
I have a test that is semi-nondeterministic. I know thats generally bad but I just want to allow 2 possible values. Does testify support this?

Ie I'm looking for something like: `testSuite.Equal(<ALLOWED_VALUE_ONE> | <ALLOWED_VALUE_TWO>, <ACTUAL_VALUE>)`

Is there support for this?

**Comment by hendrywiranto** [comment]
Hi!
can you use `assert.Contains` ?
https://github.com/stretchr/testify/blob/master/assert/assertions.go#L886

**Comment by brackendawson** [comment]
If this suggestion doesn't work for you, please do comment again or start a discussion (tab up top).
