### ISSUE TITLE
ObjectsAreEqual: Remove the sprintf-based equality check

### ISSUE THREAD

**Issue by benma** [stretchr/testify#154]
To be specific, remove this piece of code: https://github.com/stretchr/testify/blob/master/assert/assertions.go#L39-L42

It is unexpected behavior to have this check. It is also buggy, see this issue, which was closed without resolution: https://github.com/stretchr/testify/issues/143.

@DAddYE reverted a commit that fixed this: https://github.com/stretchr/testify/commit/842aeb8181a59ae6d0fac42eaef90ca01ba59c53

Downstream projects might rely on this behavior, but that only means that their tests are broken. There are a couple of solutions to that (in order of my preference):

1. Introduce tags. Downstream projects can stick to the last tag before this change and fix their code before upgrading.
1. Just go through with this and let downstream projects fix their tests. 
1. Make the behavior configurable somehow. Default to the new, correct way. This means very little effort on downstream projects.
1. Add a new Equals function with a new name, implementing the correct way.

Just keeping the buggy code because of backwards compatibility seems like the wrong move. This issue is going to come back again and again.

**Comment by teknico** [comment]
Agreed. This is a practical problem now, and people should not be encouraged to write non-deterministic tests.

Solutions 3. and 4. increase bloat and unneeded complexity. I'd just go for 2., or possibly 1. if the developers feel it's worth it (I don't).

**Comment by matryer** [comment]
Agreed. I'll make this change now.
