### ISSUE TITLE
Return a proper error message when we have type mismatching

### ISSUE THREAD

**Issue by kostyantyn** [stretchr/testify#155]
It took a lot of time to understand this broken test
```
--- FAIL: TestClickEvent (0.00s)
	Location:	click_test.go:70
	Error:		Not equal: 2 (expected)
			        != 2 (actual)
```

and the reason was that those values had different types: `int32` and `int`.

Would be really good to return a proper error message.

**Comment by matryer** [comment]
Maybe if both values are the same, we include the type? Or include the type always?

**Comment by jonahkagan** [comment]
:+1: this behavior changed recently and caused very confusing test failures

**Comment by mpictor** [comment]
Making it more strict about types is good, but doing so without printing types is bad!

:+1:  on this creating confusing test failures and needing to be fixed
