### ISSUE TITLE
error while importing github.com/stretchr/testify/suite: read C:\Program Files\Go\src\math\huge_test.go: unexpected NUL in input

### ISSUE THREAD

**Issue by mauljurassicia** [stretchr/testify#1557]
## Description

It is maybe not a bug or a bug from go standard library. But this thing make me cannot import this package in my machine

**Comment by arjunmahishi** [comment]
This doesn't look like an import error. Especially while importing `testify/suite`. 

There is a [stackoverflow thread](https://stackoverflow.com/questions/47347191/go-error-unexpected-nul-in-input) addressing something similar. This looks like a generic windows specific issue. Maybe the thread has something that helps.

Closing this issue for now.
