### ISSUE TITLE
Regexp accepts interface{}

### ISSUE THREAD

**Issue by kevinburkesegment** [stretchr/testify#1585]
The signature for [`assert.Regexp`](https://pkg.go.dev/github.com/stretchr/testify/assert#Regexp) (and associated methods) is:

```go
func Regexp(t TestingT, rx interface{}, str interface{}, msgAndArgs ...interface{}) bool {
```

However, these methods immediately call `matchRegexp`, which is this:

```go
func matchRegexp(rx interface{}, str interface{}) bool {

	var r *regexp.Regexp
	if rr, ok := rx.(*regexp.Regexp); ok {
		r = rr
	} else {
		r = regexp.MustCompile(fmt.Sprint(rx))
	}

	return (r.FindStringIndex(fmt.Sprint(str)) != nil)

}
```

Given this - wouldn't it make more sense for the signature to just be `*regexp.Regexp` and `string` ? The latter cast would likely help prevent unexpected behavior around the `fmt.Sprint` call.

**Comment by dolmen** [comment]
Changing the signature of `assert.Regexp`, `assert.NotRegexp` (...) with stricter types would break compatibility. At this point detecting usage errors can only be made via a linter like testifylint.

**Comment by ccoVeille** [comment]
> Changing the signature of `assert.Regexp`, `assert.NotRegexp` (...) with stricter types would break compatibility. At this point detecting usage errors can only be made via a linter like testifylint.

I agree with you about the compatibility issue if it was chanted, but what about changing the signature for testify v2?

Would it be acceptable?

**Comment by ccoVeille** [comment]
For record, I noticed by myself the way to solve this in testify is way more complex than I thought

I'm talking about it here

https://github.com/Antonboom/testifylint/issues/81#issuecomment-2060642389
