### ISSUE TITLE
Drop outdated/abandoned dependencies

### ISSUE THREAD

**Issue by remycx** [stretchr/testify#1589]
## Description

https://github.com/pmezard/go-difflib : as quoted, "THIS PACKAGE IS NO LONGER MAINTAINED." ; code hasn't evolved in 9 years.
https://github.com/davecgh/go-spew : hasn't been touched in 6 years.

Removing old & dangerous code would lead to a cleaner codebase.

## Use case

Reduce the dependency on outdated & abandoned repositories, to improve the safety of the library, and the potential supply chain attacks.

**Comment by dolmen** [comment]
Easy to say. But what concrete solution do you suggest? Did you had a look at existing issues?

**Comment by dolmen** [comment]
@remycx Note also that I have proposed #1579 to unlink Testify from [`gopkg.in/yaml.v3`](https://pkg.go.dev/gopkg.in/yaml.v3) (which is as unmaintained as the 2 other dependencies mentioned here, and is, in my opinion, a much higher security risk, not for Testify but for the Go ecosystem in general). Your opinion and review of that PR would be welcome.

**Comment by dolmen** [comment]
@remycx  Dropping abandonned issue.

**Comment by pohly** [comment]
Is https://github.com/google/go-cmp perhaps a viable replacement for https://github.com/pmezard/go-difflib?

**Comment by pohly** [comment]
`go-cmp` might be overkill. A simple diff implementation for two sequences of a comparable type like strings in https://github.com/stretchr/testify/blob/b074924938f86d417f1c9a845c7e8b0784d7f937/assert/assertions.go#L1883-L1891 isn't hard to write - I'll have a look.

**Comment by eero-t** [comment]
> `go-cmp` might be overkill. A simple diff implementation for two sequences of a comparable type like strings in
> ...
> isn't hard to write - I'll have a look.

@pohly Did anything come out of this?  According to https://github.com/stretchr/testify/issues/736, there were 2 functions used from `go-difflib`.

**Comment by pohly** [comment]
No. I dropped the idea after a discussion on Slack, see https://gophers.slack.com/archives/C92321HDJ/p1727454579279159.
