### ISSUE TITLE
Proposal: assert.NotElementsMatch()

### ISSUE THREAD

**Issue by jdycaico** [stretchr/testify#1594]
## Description
As per https://github.com/stretchr/testify/discussions/1592#discussioncomment-9261557:
A method that does the opposite of `assert.ElementsMatch()`

## Use case
It would appear that there are no stable workarounds, and I have been suggested to make a FR

**Comment by hendrywiranto** [comment]
hello @jdycaico do you plan to work on this and make a PR eventually? I can try to open a PR if you won't work on this, thanks

**Comment by hendrywiranto** [comment]
fyi @jdycaico this has been merged https://github.com/stretchr/testify/pull/1600

**Comment by hendrywiranto** [comment]
btw this can be closed right? @brackendawson

**Comment by brackendawson** [comment]
Yes :-)
