### ISSUE TITLE
Feature request: add BeforeSetupTest and AfterTearDownTest

### ISSUE THREAD

**Issue by sirzooro** [stretchr/testify#1604]
## Description
Methods of existing `BeforeTest` and `AfterTest` interfaces are called after `SetupTest` and before `TearDownTest` ones. I need ones which are called before and after them, i.e. "wrap" whole test with its Setup and TestDown parts. Please add new interfaces `BeforeSetupTest` and `AfterTearDownTest` for this.

## Use case
I have custom Suite type which wraps `suite.Suite`. I want to do extra things before and after each test, like printing custom start/end messages and checking for goroutine leaks. For subtests I was able to provide my own `Run` method which internally calls one from `suite.Suite`. For tests there is no easy way to do this.

**Comment by hendrywiranto** [comment]
hi @sirzooro 

I'm no expert for the `suite` interfaces, but can you use `SetupSuite` and `TearDownSuite`? 
- https://github.com/stretchr/testify/blob/master/suite/interfaces.go#L16
- https://github.com/stretchr/testify/blob/master/suite/interfaces.go#L27

I looked for more doc of the ordering but I still can't find the complete docs

**Comment by sirzooro** [comment]
`SetupSuite` and `TearDownSuite` are called before 1st test and after last one, respectively. They are useful to perform some costly global initialization and teardown for whole test suite, e.g. setup test DB before all tests and shut it down after all tests are completed. So no, they do not satisfy my needs.

And yes, docs does not specify ordering, one has to check this in the code. It would be good to add this to the docs.

**Comment by hendrywiranto** [comment]
I see, thank you for explaining.

I was thinking of just adding your operations that you want to be before `SetupTest` just on the start of the `SetupTest` itself, so no need to add another wrapper for this since both `SetupTest` and your suggested feature is executed in order on each tests.
does that make sense to you?

**Comment by brackendawson** [comment]
We currently seem to have this order:

* [SetupAllSuite](https://pkg.go.dev/github.com/stretchr/testify/suite#SetupAllSuite)
    * [SetupTestSuite](https://pkg.go.dev/github.com/stretchr/testify/suite#SetupTestSuite)
    * [BeforeTest](https://pkg.go.dev/github.com/stretchr/testify/suite#BeforeTest)
        * [SetupSubTest](https://pkg.go.dev/github.com/stretchr/testify/suite#SetupSubTest)
        * [TearDownSubTest](https://pkg.go.dev/github.com/stretchr/testify/suite#TearDownSubTest)
    * [AfterTest](https://pkg.go.dev/github.com/stretchr/testify/suite#AfterTest)
    * [TearDownTestSuite](https://pkg.go.dev/github.com/stretchr/testify/suite#TearDownTestSuite)
* [TearDownAllSuite](https://pkg.go.dev/github.com/stretchr/testify/suite#TearDownAllSuite)

Not sure why we have both SetupTestSuite which sets up a test *and* Before Test, perhaps that added the name arguments that someone needed?

We also have some annoying parts like the method in `SetupAllSuite` is actually `SetupSuite`, the latter is a way better name. This could do with a lot of cleanup, but not without breaking changes. If someone wants to open a PR to improve the documentation that would be welcome.

We're certainly not adding more before and after any of these, if you want code before BeforeTest then put it at the top of BeforeTest.
