### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by imortimer-pivotal** [stretchr/testify#161]
# github.com/stretchr/testify/assert
/usr/local/go/src/pkg/github.com/stretchr/testify/assert/assertions.go:52: expectedValue.Type().ConvertibleTo undefined (type reflect.Type has no field or method ConvertibleTo)
/usr/local/go/src/pkg/github.com/stretchr/testify/assert/assertions.go:54: expectedValue.Convert undefined (type reflect.Value has no field or method Convert)
/usr/local/go/src/pkg/github.com/stretchr/testify/assert/assertions.go:123: undefined: bufio.NewScanner

**Comment by vdemario** [comment]
@imortimer-pivotal it looks like you have problems on your `golang` setup, all of those errors are about not finding parts of the standard library.

It may seem simplistic but take a look at `$GOPATH`, workspace setup, that kind of thing: https://golang.org/doc/code.html

**Comment by ernesto-jimenez** [comment]
@imortimer-pivotal what version of Go are you using?

You can check the version with `go version`

If you are using a version prior to Go 1.1, that might be the issue. The package is currently only tested in Go 1.1 and up.

**Comment by imortimer-pivotal** [comment]
Guys, thanks. Was the version. Have a great weekend.
