### ISSUE TITLE
go-difflib library v1.0.0 reached End Of Life

### ISSUE THREAD

**Issue by vlbarou** [stretchr/testify#1618]
## Description
Latest version depends on `github.com/pmezard/go-difflib v1.0.0` that reached EOL

## Step To Reproduce
1) download master branch
2) grep command will give the following output:

```
go.mod:	github.com/pmezard/go-difflib v1.0.0
mock/mock.go:	"github.com/pmezard/go-difflib/difflib"
go.sum:github.com/pmezard/go-difflib v1.0.0 h1:4DBwDE0NGyQoBHbLQYPwSUPoCMWR5BEzIk/f1lZbAQM=
go.sum:github.com/pmezard/go-difflib v1.0.0/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZNVY4sRDYZ/4=
assert/assertions.go:	"github.com/pmezard/go-difflib/difflib"
```

## Expected behavior
testify should not depend on EOL libraries

**Comment by brackendawson** [comment]
Duplicate of #1159

**Comment by ccoVeille** [comment]
Resolved by vendoring go-difflib

- https://github.com/stretchr/testify/pull/1708

See https://github.com/stretchr/testify/issues/1159#issuecomment-3281982413
