### ISSUE TITLE
Functions which check for string matching got "non-library standard" signature

### ISSUE THREAD

**Issue by megalepozy** [stretchr/testify#1625]
## Description
`ErrorContainsf(t TestingT, theError error, contains string, msg string, args ...interface{})` and other string matching functions require a `msg string` while most of the functions in the library request `msgAndArgs ...interface{} ` which give you the option to supply one if wanted
This is making the usage of the library a bit confusing (wasted few minutes on it so it's not terrible...)

## Proposed solution
Instead of requesting for `msg string` they should ask for `msgAndArgs ...interface{} `as the majority of the functions (I admit  I didn't count but it seems to be the rule)

**Comment by Antonboom** [comment]
Looks like you are confusing by f-funcs and not formatted funcs.

Please, read the historical reference here https://github.com/Antonboom/testifylint#formatter

**Comment by megalepozy** [comment]
I wasn't confusing but the link u gave was spot on.
I close the issue
