### ISSUE TITLE
Can't assert a panic from a sub goroutine ?

### ISSUE THREAD

**Issue by kuchaguangjie** [stretchr/testify#1632]
```
package error_learn

import (
	"fmt"
	"github.com/stretchr/testify/assert"
	"testing"
	"time"
)

// panic in sub goroutine, recover in main goroutine,
func panicInSubGoroutine() {
	// recover,  in main goroutine,
	defer func() {
		if r := recover(); r != nil {
			fmt.Printf("recover from panic: %v\n", r)
		}
	}()

	go func() {
		// panic, in sub goroutine,
		panic("panic occurred!")
	}()

	time.Sleep(1 * time.Second)
}

func TestPanicInSubGoroutine(t *testing.T) {
	assert.Panics(t, panicInSubGoroutine)
}
```

Sub goroutine panic, assert the main goroutine, the test still fail with:
> panic: panic occurred!

Does that means `assert.Panics()` can't assert a panic from sub goroutine ?

**Comment by Antonboom** [comment]
This is not `testify` issue, this is Golang panic-recover design.

- https://go.dev/blog/defer-panic-and-recover
- https://go.dev/wiki/PanicAndRecover

> A panic cannot be recovered by a different goroutine.

P.S. Also, look at [testifylint#go-require](https://github.com/Antonboom/testifylint?tab=readme-ov-file#go-require)

**Comment by Antonboom** [comment]
Duplicate of https://github.com/stretchr/testify/discussions/1617

**Comment by brackendawson** [comment]
Thank you @Antonboom, quite correct.
