### ISSUE TITLE
Address Dependency Operational Risks

### ISSUE THREAD

**Issue by Krunal-Thakkar** [stretchr/testify#1638]
Hi Team,

We've identified a few dependencies in your project that might benefit from an update:

- **go-spew v1.1.1:** This version was released on August 22, 2018(2219 days ago)
- **kr/pretty v0.3.1:** This version was released on OCT 08, 2022(712 days ago)
- **stretchr/objx v0.5.2 :** This version was released on FEB 29, 2024(202 days ago)

Updating to a newer version could potentially address compatibility issues or security vulnerabilities with newer systems or frameworks.

Updating these dependencies could improve overall security and compatibility.

Would you be open to discussing potential upgrade paths for these dependencies? Please let us know if you have any questions or require further information.

Thanks,

**Comment by brackendawson** [comment]
Both go-spew and objx are imported at the latest version. We do not depend on kr/pretty.
