### ISSUE TITLE
the testing package may cause a crash

### ISSUE THREAD

**Issue by daocoder2** [stretchr/testify#1676]
You can refer to the details of the problem here [the testing package may cause a crash](https://github.com/golang/go/issues/70218), I am not sure if you would consider changing the implementation.
This should happen after go 1.18.

**Comment by brackendawson** [comment]
Doesn't recreate when using the testing.T passed to a test.

From the docs:
> Assertions allow you to easily write test code, and are global funcs in the `assert` package. All assertion functions take, as the first argument, the `*testing.T` object provided by the testing framework. This allows the assertion funcs to write the failings and other details to the correct place.
