### ISSUE TITLE
Improve the way FAIL and PASS is presented in the terminal

### ISSUE THREAD

**Issue by odeta939** [stretchr/testify#1682]
## Description

I find the console output of this library very hard to read, sometimes it is hard to see where is the actual problem cause it is buried in a long list of bytes.

1. Make this output optional with a flag :

  `    Error:          Not equal:
                                  expected: []byte{0x7b, 0x22, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3a, 0x7b, 0x22, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x22, 0x4e, 0x4f......}
                                  actual  : []byte{0x7b, 0x22, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3a, 0x7b, 0x22, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x22, 0x4e, 0x4f, 0x54........}`
                               

_Disclaimer: It might be a skill issue from my part and it might be that I just don't appreciate a good thing ( so please explain to me if I am wrong and missing something here)_ 

2. Improve the way PASS and FAIL is displayed with a colour schema or Emojies like ❌ and ✅

## Proposed solution
 Right now I use this command to make my output a bit more pleasant to look at :
1. to get the emojies next to PASS and FAIL instead of `-----` 

 `go test -v ./... | sed ''/---\ PASS:/s//"$(printf "\033[32m✅--- PASS:\033[0m")"/'' | sed ''/---\ FAIL:/s//"$(printf "\033[31m❌--- FAIL:\033[0m")"/''` 
 
2.  the package diffmatchpatch which colours the missmatch of the output. So I see the mistake coloured in red and the expectation in green.
 
 maybe these features could be somehow incorporated in this library or add with a flag for optional 

## Use case

Workarounds mentioned above. 

Usecase: people like me(borderline dyslexic) who often miss-types words and has difficulties finding the important information in a soup of white text on a black background, would benefit from this greatly. 
Not only it would improve usability of your library but also bring some life and fun to testing (who doesn't like to see all tests go green in their terminal?)

**Comment by brackendawson** [comment]
Go itself reports on failed Vs passed tests and it does not use colour or emoji. I don't think testify should do so either. Asides from all the terminal compatibility concerns you have to get right a test could fail by calling t.FailNow() and it would *not* get a red emoji in the sea of green ones.

**Comment by odeta939** [comment]
I don't see why testify should not improve DX just because Go itself is not doing it. Reducing cognitive load with simple things like that would improve quality of life for many people, in my opinion. But of course it's up to the core team to implement these changes.

**Comment by dolmen** [comment]
This is just formatting. This task should be left to another tool that should process the output of `go test -json`. See also `go doc test2json`.
