### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by TechnotronicOz** [stretchr/testify#169]
Versioning is an important thing. It would be nice to see something like gopkg.in be used to semver Testify.

**Comment by DAddYE** [comment]
Yes, I agree with that.

we can use gopkg.in or just make a `v1` folder and `v2` etc... 

I'm fine with both

**Comment by ernesto-jimenez** [comment]
IMHO, gopkg.in should be ok, since you just need to tag the repository and, AFAIK, people can still go get github.com/stretchr/testify

:-1: to having different folders

**Comment by TechnotronicOz** [comment]
I opened a PR (https://github.com/stretchr/testify/pull/170) to use Gopkg.in for versioning. That way people can still grab the package and get latest or they can specify a specific version. I also added version history into the README in hopes that it is maintained and the change log can be helpful for somebody. If you could create a tag named `v1.0` off of that it should be good to go.
