### ISSUE TITLE
Use Fatalf instead of Errorf in assert

### ISSUE THREAD

**Issue by markbates** [stretchr/testify#172]
I'm opening this, instead of a PR, to start a discussion on this subject. I'm happy to implement the PR, but I want to discuss why I think `Fail` should switch to using `Fatalf` instead of `Errorf`, and potential ways to preserve current functionality, if that's desired.

Let's take this fairly contrived test:

``` go
func Test_Panic(t *testing.T) {
    a := assert.New(t)

    array := []string{"foo"}

    a.Equal(2, array)
    a.Equal("bar", array[1])
}
```

When run instead of stopping at the first error, `a.Equal(2, array)`, the test continues to run and then panics on the next line:

```
--- FAIL: Test_Panic (0.00s)
        Location:       token_test.go:17
    Error:      Not equal: 2 (expected)
                    != []string{"foo"} (actual)

panic: runtime error: index out of range [recovered]
    panic: runtime error: index out of range

goroutine 10 [running]:
testing.func·006()
    /usr/local/go/src/testing/testing.go:441 +0x181
foo_test.Test_Panic(0xc208056cf0)
    foo_test.go:18 +0x2d0
testing.tRunner(0xc208056cf0, 0x474cac8)
    /usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
    /usr/local/go/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x461e7b8, 0x474ca80, 0x5, 0x5, 0xc20800b501)
    /usr/local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc208050460, 0x476dee0)
    /usr/local/go/src/testing/testing.go:485 +0x6c
main.main()
    foo/_test/_testmain.go:62 +0x1d5

goroutine 6 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208070280)
    /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:452 +0x31c
FAIL    gitlafoo.099s
```

If we use `Fatalf` instead of `Errorf` to report failed assertions tests no longer panic, and instead produce more sane results:

```
--- FAIL: Test_Panic (0.00s)
        Location:       token_test.go:17
    Error:      Not equal: 2 (expected)
                    != []string{"foo"} (actual)

FAIL
FAIL    gitlabfoo0.089s
```

This change is a simple enough one to make, and doesn't change the public API of `assert` at all. Instead, I believe, it actually produces the behavior people actually expect.

If desired, it would be easy to add some sort of boolean flag on `assert` to indicate whether the package should use `Fatalf` or `Errorf`, although, personally, I don't think this is really necessary, but it could be done the code is pretty well encapsulated.

I'm happy to write up the PR for this, but wanted to get the buy in on it first. Thoughts?

**Comment by paulshir** [comment]
I think you can just import and use `github.com/stretchr/testify/require` instead of `github.com/stretchr/testify/assert` to achieve this. It implements the same assertion interface but fails the test straightaway without continuing.

**Comment by markbates** [comment]
That looks like it'll do the trick. I can use that.

With that said, I've talked to a lot of folks who, like me, having been using `assert` for a long time and just didn't know about `require` and are constantly complaining about `assert` using `Errorf`, hence this issue.

I still wonder if it would be worth it to either add a switch to `assert` or to just have it use `Fatalf` instead, which I do think a lot of people would prefer as the default. This would also save you the effort of having to maintain two almost identical packages.

Thoughts?

**Comment by paulshir** [comment]
I don't have any ownership with this package. Just had seen the issue and knew about the other package so added the comment.

**Comment by ernesto-jimenez** [comment]
@markbates, assert also allows you to do the following:

```go
func Test_Panic(t *testing.T) {
    a := assert.New(t)

    array := []string{"foo"}

    if a.Equal(2, array) {
        a.Equal("bar", array[1])
    }
}
```

**Comment by nhooyr** [comment]
@ernesto-jimenez why couldn't you do that with `require`? In fact, using `require` there would also mean no need for the if statement.

**Comment by markbates** [comment]
I’m closing this since I meant to close it 3 years ago. :)

I opened this before I knew about the require package, so there is no need for this proposal.
