### ISSUE TITLE
assert.Equal() not work on functions

### ISSUE THREAD

**Issue by redforks** [stretchr/testify#182]
I want compare two functions are the same function, but failed:

fn := func() {}
assert.Equal(t, fn, fn) // expected passed, but failed

In go, functions are not comparable, but can testify do some special treatment on function type, such as
compare there pointer address, like reflect.Value(fn).Pointer(). Or add a new function like EqualFunc() not slow down Equal() function.

**Comment by ernesto-jimenez** [comment]
@redforks I'm afraid it's not possible right now.

See https://github.com/stretchr/testify/issues/159#issuecomment-99557398

**Comment by redforks** [comment]
Thanks, I didn't read the Pointer() document very carefully. So there is no
way to compare func equality except nil, that is odd.

**Comment by justinas** [comment]
Yet, this only broke @ e22aedd, probably due to "last ditch effort" being removed. These errors look really funny now:
```
	Error:		Not equal: (alice.Constructor)(0x63200) (expected)
			        != (alice.Constructor)(0x63200) (actual)
```

**Comment by ernesto-jimenez** [comment]
@justinas the project should not break existing behaviour.

With that being said, that work around wasn't reliable anyway, since function comparison guaranteed in Go is comparing to nil.

We should definitely fix assert.Equal to error when trying to compare funcs rather than showing that misleading message. Same way we [panic when passing a func to a mock](https://github.com/stretchr/testify/blob/7e4a149930b09fe4c2b134c50ce637457ba6e966/mock/mock.go#L103-L105).

I'll leave this issue open until we fix that.

**Comment by kovetskiy** [comment]
https://golang.org/doc/devel/weekly.html#2011-11-18
> Map and function value comparisons are now disallowed (except for comparison
> with nil) as per the Go 1 plan. Function equality was problematic in some
> contexts and map equality compares pointers, not the maps' content.

**Comment by matryer** [comment]
Does comparing func addresses make sense? Or same problem?

**Comment by ernesto-jimenez** [comment]
@matryer it won't work:

> If v's Kind is Func, the returned pointer is an underlying code pointer, but not necessarily enough to identify a single function uniquely. The only guarantee is that the result is zero if and only if v is a nil func Value.


All the info is in issue #159

**Comment by borgstrom** [comment]
FWIW, for future readers of this issue, here's the work around I've been using for comparing function "equality":

```go
funcName1 := runtime.FuncForPC(reflect.ValueOf(func1).Pointer()).Name()
funcName2 := runtime.FuncForPC(reflect.ValueOf(func2).Pointer()).Name()
assert.Equal(t, funcName1, funcName2)
```

**Comment by boyan-soubachov** [comment]
@georgelesica-wf , @ernesto-jimenez , I agree with the idea of panicking if comparing functions. As Go's current, official behaviour is to disallow (or discourage) direct function comparisons, I think we should follow that idea.

If we're happy with that approach, I'd be glad to add code to `assert.Equal()` which panics (or Fatals) if we're comparing two functions.

**Comment by glesica** [comment]
Agree, I'd rather not jump through crazy hoops to get something that the Go team doesn't really want to support.

**Comment by nezlobnaya** [comment]
@borgstrom Why are you adding .Name()?
