### ISSUE TITLE
Error trace is incomplete when assertions are in a goroutine

### ISSUE THREAD

**Issue by paulbellamy** [stretchr/testify#183]
Because `runtime.Caller` only returns function invocations on the calling goroutine's stack, if we do:
```Go
func TestFoo(t *testing.T) {
  go func() {
    assert.Fail(t, "Failed!")
  }()
}
```

We get no error trace data.

**Comment by ernesto-jimenez** [comment]
@paulbellamy sorry for the late reply. Do you have a suggestion to address it?

**Comment by paulbellamy** [comment]
Not specifically, no. Not even sure if it can be fixed.

**Comment by ernesto-jimenez** [comment]
@paulbellamy neither do I, that's why I asked :)

Will have to do some research ^_^

**Comment by ernesto-jimenez** [comment]
I believe this might be fixed already with some recent changes.

Do you mind checking?

**Comment by paulbellamy** [comment]
Now:
```
package foo

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestFoo(t *testing.T) {
	done := make(chan bool)
	go func() {
		assert.Fail(t, "Failed!")
		close(done)
	}()
	<-done
}
```

Fails with:
```
--- FAIL: TestFoo (0.00s)
        Error Trace:    foo_test.go:12
			asm_amd64.s:2086
	Error:		Failed!

FAIL
FAIL	command-line-arguments	0.008s
```

So, seems fixed!
