### ISSUE TITLE
`go test -run=X` filtering in a suite

### ISSUE THREAD

**Issue by pkieltyka** [stretchr/testify#184]
Hello, is it possible to use `go test -run=TestSomeSuite.TestCaseInSuite` or something to this effect? that is, to only run the test case of a specific case in a suite?

**Comment by pkieltyka** [comment]
figured it out.. the -m flag. awesome!

**Comment by cryptix** [comment]
I always assumed this wasn't possible at all. Thanks!

**Comment by travisjeffery** [comment]
@pkieltyka what -m flag?

**Comment by pkieltyka** [comment]
try it
