### ISSUE TITLE
EqualError error output swaps the actual and expected values

### ISSUE THREAD

**Issue by willfaught** [stretchr/testify#185]
In my test:

    assert.EqualError(t, err, "missing or invalid currency")

In the output:

    Error Trace:    my_test.go:58
    Error:  	    Not equal: "missing or invalid amount" (expected)
                            != "missing or invalid currency" (actual)
    Messages:	    An error with value "missing or invalid currency" is expected but got "missing or invalid amount".

Note the

    "missing or invalid amount" (expected)

and the

    "missing or invalid currency" is expected

Same for the actual values.

**Comment by sivagollapalli** [comment]
Could we close this issue as PR got merged?

**Comment by matryer** [comment]
Sorry - you were asking the opener :)

**Comment by willfaught** [comment]
Thanks for fixing.
