### ISSUE TITLE
gopkg.in versioning broken

### ISSUE THREAD

**Issue by mgutz** [stretchr/testify#188]
``` go
import (
    "gopkg.in/stretchr/testify.v1/mock"
)
```

results in `go build github.com/stretchr/testify/assert: no buildable Go source files in` because imports still reference github.com

https://github.com/stretchr/testify/blob/master/mock/mock.go#L12

What it basically means is testify.v1, testify.v2 ... testify.vN all reference the same mock package unless imports are also changed to use gopkg.in. This is a known limitation with gopkg.in and subpackages.

**Comment by ernesto-jimenez** [comment]
I would suggest using `dep` rather than gopkg.in
