### ISSUE TITLE
can not mock functions with argument 'os.FileMode'

### ISSUE THREAD

**Issue by galric** [stretchr/testify#193]
Hello, I come across a problem,

I have a func : 
func (m *ISystem) CreateFile(path string, mode os.FileMode) (*os.File, error) {...}

mock it as:
mockSystem.On("CreateFile", lockFile, 0777).Return(testFd, errors.New("abc"))
mockSystem.On("CreateFile", lockFile, os.FileMode(0777)).Return(testFd, errors.New("abc"))

but neither works,

mock: Unexpected Method Call
-----------------------------
 
CreateFile(string,os.FileMode)
                0: some_path
                1: -rwxrwxrwx
 
The closest call I have is:
 
CreateFile(string,int)
                0: some_path
                1: 511
 (PC=0x43C975)

**Comment by ernesto-jimenez** [comment]
@galric did you fix the problem?

I've tested it myself and it works, so I'm closing the issue. If you are still encountering the issue give me a complete code sample and I'll be happy to help you find what's missing.
