### ISSUE TITLE
Unexpected Method Call

### ISSUE THREAD

**Issue by davisford** [stretchr/testify#198]
I'm using `mockery` generated mocks with `testify`.  I'm getting the following error:

```
mock: Unexpected Method Call
-----------------------------

FindAllOrgs(uint64,uint64,[]string)
		0: 25
		1: 0
		2: []

The closest call I have is: 

FindAllOrgs(uint64,uint64,[]string)
		0: 25
		1: 0
		2: []
 [recovered]
	panic: 

```

For this test code: 

```go
	var limit uint64 = 25
	var offset uint64
	var sort = []string{}
	mock.On("FindAllOrgs", limit, offset, sort).Return([]*api.Org{}, nil)
```

This is the interface definition:

```go
FindAllOrgs(limit uint64, offset uint64, sortProps []string) ([]*api.Org, error)
```

The mockery generated implementation:

```go
func (_m *KeyManager) FindAllOrgs(limit uint64, offset uint64, sortProps []string) ([]*api.Org, error) {
	ret := _m.Called(limit, offset, sortProps)

	var r0 []*api.Org
	if rf, ok := ret.Get(0).(func(uint64, uint64, []string) []*api.Org); ok {
		r0 = rf(limit, offset, sortProps)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*api.Org)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64, uint64, []string) error); ok {
		r1 = rf(limit, offset, sortProps)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
```

What am I missing / Why is it complaining -- looks the same to me?

**Comment by ernesto-jimenez** [comment]
@davisford I just tried to generate a mock with `mockery` for the same interface and it worked for me.

Were you using the latest versions of `testify` and `mockery`?

How were you calling the mock?

**Comment by davisford** [comment]
@ernesto-jimenez closing this one.  i was able to move past it -- don't remember exactly the issue.  probably just overlooked something somewhere via a long work day ;)

**Comment by ernesto-jimenez** [comment]
@davisford cool, I get those long days too! thanks :)

**Comment by dfellis** [comment]
For anyone else running across this old issue as the only indicator of their own weird issue with mockery, in my own similar situation I eventually discovered that I had put a `.Once()` on my mock when my code actually called the method with that signature 3 times.

It would be nice if mockery provided a more descriptive error message in this situation. :)

**Comment by grdthh** [comment]
agree with @dfellis , the error message is unclear it should be more descriptive
