### ISSUE TITLE
Provide APIs to add fixtures with setup/teardown hooks

### ISSUE THREAD

**Issue by gsalgado** [stretchr/testify#215]
One thing I used a lot when writing Python tests was https://pypi.python.org/pypi/fixtures. It's basically a way to define fixtures with setup/teardown methods that can be added to a given test suite where the setup/teardown methods are called at the beginning/end of every test. I think that would be a useful addition for testify.Suite

Reusable fixtures like this can be composed to create test suites that match the exact needs of the tests in it. For example, I could have one ~~suite~~ fixture which provides just a NSQ publisher, another with just a postgres DB and a third containing both. Currently there doesn't seem to be a simple way of doing that.

I haven't thought about what would be the best way to implement that, but I'm willing to give it a go if there's desire for it

**Comment by ernesto-jimenez** [comment]
@gsalgado the `suite` package already allows you to define setup and teardown methods.

Are you missing something else specifically?

**Comment by gsalgado** [comment]
I'd like to be able to define the fixtures separate from the Suites themselves, so that I can combine them to create a Suite that has only the fixtures needed for its tests, as in the NSQ/DB example I mentioned in the description. With the current mechanism that's not possible because one has to define the fixture in a Suite (e.g. one suite with a DB fixture and another with NSQ) and then embed them both into a third suite, which doesn't work if they all define their own setup/teardown methods

**Comment by ernesto-jimenez** [comment]
@gsalgado you can define the setup/teardown independently and embed it into whatever suite you want.

Here are some examples:

```go
package main

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/suite"
)

type NSQFixtures struct {
}

func (n NSQFixtures) SetupTest() {
	fmt.Println("setup nsq")
}

func (n NSQFixtures) TearDownTest() {
	fmt.Println("teardown nsq")
}

type Suite struct {
	suite.Suite
	NSQFixtures
}

func (s *Suite) TestFirst() {
	fmt.Println("test first")
	s.T().Error("fail first")
}

func (s *Suite) TestSecond() {
	fmt.Println("test second")
	s.T().Error("fail second")
}

func TestSomething(t *testing.T) {
	s := &Suite{}
	suite.Run(t, s)
}
```

Output:

```
setup nsq
test first
teardown nsq
--- FAIL: TestFirst (0.00s)
	main_test.go:28: fail first
setup nsq
test second
teardown nsq
--- FAIL: TestSecond (0.00s)
	main_test.go:33: fail second
--- FAIL: TestSomething (0.00s)
FAIL
````

You can also set your suite so the Fixture can be injected, if you need some configuration:

```go
package main

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/suite"
)

type NSQFixtures struct {
	queue string
}

func (n NSQFixtures) SetupTest() {
	fmt.Printf("setup nsq: %s\n", n.queue)
}

func (n NSQFixtures) TearDownTest() {
	fmt.Printf("teardown nsq: %s\n", n.queue)
}

type Fixture interface {
	SetupTest()
	TearDownTest()
}

type Suite struct {
	suite.Suite
	Fixture
}

func (s *Suite) TestFirst() {
	fmt.Println("test first")
	s.T().Error("fail first")
}

func (s *Suite) TestSecond() {
	fmt.Println("test second")
	s.T().Error("fail second")
}

func TestSomething(t *testing.T) {
	s := &Suite{Fixture: NSQFixtures{queue: "hey"}}
	suite.Run(t, s)
}
```

Ouput:
```
setup nsq: hey
test first
teardown nsq: hey
--- FAIL: TestFirst (0.00s)
	main_test.go:34: fail first
setup nsq: hey
test second
teardown nsq: hey
--- FAIL: TestSecond (0.00s)
	main_test.go:39: fail second
--- FAIL: TestSomething (0.00s)
FAIL
```

If you want to chain more than one fixture you just need to define your chain:

```go
package main

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/suite"
)

type FixtureChain struct {
	fixtures []Fixture
}

func (f FixtureChain) SetupTest() {
	for _, fixture := range f.fixtures {
		fixture.SetupTest()
	}
}

func (f FixtureChain) TearDownTest() {
	for _, fixture := range f.fixtures {
		defer fixture.TearDownTest()
	}
}

type NSQFixtures struct {
	queue string
}

func (n NSQFixtures) SetupTest() {
	fmt.Printf("setup nsq: %s\n", n.queue)
}

func (n NSQFixtures) TearDownTest() {
	fmt.Printf("teardown nsq: %s\n", n.queue)
}

type Fixture interface {
	SetupTest()
	TearDownTest()
}

type Suite struct {
	suite.Suite
	Fixture
}

func (s *Suite) TestFirst() {
	fmt.Println("test first")
	s.T().Error("fail first")
}

func (s *Suite) TestSecond() {
	fmt.Println("test second")
	s.T().Error("fail second")
}

func TestSomething(t *testing.T) {
	s := &Suite{Fixture: FixtureChain{[]Fixture{
		NSQFixtures{queue: "hey"},
		NSQFixtures{queue: "ok"},
	}}}
	suite.Run(t, s)
}
```

Output:

```
setup nsq: hey
setup nsq: ok
test first
teardown nsq: ok
teardown nsq: hey
--- FAIL: TestFirst (0.00s)
	main_test.go:50: fail first
setup nsq: hey
setup nsq: ok
test second
teardown nsq: ok
teardown nsq: hey
--- FAIL: TestSecond (0.00s)
	main_test.go:55: fail second
--- FAIL: TestSomething (0.00s)
FAIL
```

Is that what you want?

**Comment by ernesto-jimenez** [comment]
@gsalgado is that what you were looking for? :)

**Comment by gsalgado** [comment]
Yes, resource/fixture chaining is what I'm looking for. It'd be nice if the Fixture interface was part of testify and Suite had a []Fixture field, so that a test suite could just declare the fixtures it wants to use and testify would take care of setup/teardown. The Fixture interface could also provide a way of checking if a fixture is clean or dirty, as clean fixtures could be reused across tests

**Comment by ernesto-jimenez** [comment]
> Yes, resource/fixture chaining is what I'm looking for. It'd be nice if the Fixture interface was part of testify

We can add something like the `FixtureChain` struct and the `Fixture` interface.

> and Suite had a []Fixture field, so that a test suite could just declare the fixtures it wants to use and testify would take care of setup/teardown.

You could just embed a `FixtureChain` without having to ad a `[]Fixture` field to `Suite`, like in the example.

> The Fixture interface could also provide a way of checking if a fixture is clean or dirty, as clean fixtures could be reused across tests

I'm inclined to think that's an implementation detail from each Fixture.

**Comment by gsalgado** [comment]
That would be great, but embedding a FixtureChain like you proposed will not work if the Suite struct implements a SetupTest as well because then only the one from the first embedded struct will be called.

Also, I agree that fixture reuse is an implementation detail, but it'd be nice if testify provided a hook so that fixtures could tell testify when it's fine to reuse them.

**Comment by ernesto-jimenez** [comment]
> That would be great, but embedding a FixtureChain like you proposed will not work if the Suite struct implements a SetupTest as well because then only the one from the first embedded struct will be called.

In that case you would just need to call `s.FixtureChain.SetupTest()` within your `(s *Suite) SetupTest()` function. Which would also allow you to decide whether to call the fixture chain before or after your suite setup.

> Also, I agree that fixture reuse is an implementation detail, but it'd be nice if testify provided a hook so that fixtures could tell testify when it's fine to reuse them.

That would imply a different API where testify would be responsible of initialising your fixture and provide hooks to specify whether the fixture is dirty. Do you have a suggestion of such API?

I cannot think of one that would be clear and not subject to any problems.
