### ISSUE TITLE
In README documentation of suite package

### ISSUE THREAD

**Issue by spraveen1112** [stretchr/testify#225]
In README  documentation of suite package : 

ERROR :  
func (suite *ExampleTestSuite) TestExample() {
    assert.Equal(suite.T(), suite.VariableThatShouldStartAtFive, 5)
}
Explanation : In assert.Equal(suite.T(), actual, expected) 

CORRECTION :
func (suite *ExampleTestSuite) TestExample() {
    assert.Equal(suite.T(), 5, suite.VariableThatShouldStartAtFive)
}
Explanation : In assert.Equal(suite.T(), expected, actual)

**Comment by ernesto-jimenez** [comment]
@spraveen1112 are you up for doing a quick pull request? :)

**Comment by spraveen1112** [comment]
@ernesto-jimenez : I made changes in README documentation of suite package and go.doc. Do I have to make changes somewhere else also?

**Comment by spraveen1112** [comment]
@ernesto-jimenez : I raised the pull request can you please have a look ?
