### ISSUE TITLE
suite does not seem to support the -run command line flag

### ISSUE THREAD

**Issue by IvanMalison** [stretchr/testify#236]
I imagine that it may not be possibel to do this, but does anyone know what would be involved in getting this to work. I'm aware that I can run the suite by itself quite easily.

**Comment by ernesto-jimenez** [comment]
Hi @IvanMalison,

Checking the code, you have a `-m` flag to what tests to run within the suites.

Does that work?

**Comment by IvanMalison** [comment]
perfect! Sorry should have looked in to this further.

**Comment by ernesto-jimenez** [comment]
Glad to help :)

Happy hacking!

**Comment by sandro** [comment]
This is great news. I love singling out specific tests, so it's good to know that an alternative to `go test -run` exists for a test suite. 👍

**Comment by kyteague** [comment]
Why is this not documented anywhere? This should be part of the README.
