### ISSUE TITLE
How to assert on mocks that are built within the function being tested

### ISSUE THREAD

**Issue by sjmh** [stretchr/testify#242]
I have a bit of code that does something like this: http://play.golang.org/p/uAE3TtHUaF

```go
package main

import "fmt"

type thingInterface interface {
	do() (string, error)
}

type Foo struct {
	data string
}

func (f *Foo) do() (string, error) {
	return fmt.Sprintf("Hello %s!", f.data), nil
}

type Bar struct {
	data string
}

func (b *Bar) do() (string, error) {
	return fmt.Sprintf("Hola %s!", b.data), nil
}

func newFoo(thing string) thingInterface {
	return &Foo{thing}
}

func newBar(thing string) thingInterface {
	return &Bar{thing}
}

type doer func(string) thingInterface
type myThing struct {
	doers map[string]doer
}

func (m *myThing) doSomeStuff(which, name string) string {
	var thing thingInterface
	thing = m.doers[which](name)
	res, _ := thing.do()
	return res
}

func main() {
	m := &myThing{
		doers: map[string]doer{
			"foo": newFoo,
			"bar": newBar,
		},
	}
	fmt.Println(m.doSomeStuff("foo", "steve"))
	fmt.Println(m.doSomeStuff("bar", "john"))
}

```

The general gist being that depending on some data, I use a different constructor to get the object, which obeys the interface and then I call it.

I want to mock the objects that I'm creating and assert that a) the constructor was called correctly and b) that the interface was called correctly.

Here's what I've got so far:

```go
package main

import (
	"testing"

	"github.com/stretchr/testify/mock"
)

type TestFoo struct {
	mock.Mock
}

func (f *TestFoo) do() (string, error) {
	args := f.Called()
	return args.String(0), args.Error(1)
}

func newTestFoo(thing string) thingInterface {
	m := &TestFoo{}
	m.On("do").Return("Yipee!", nil)
	return m
}

func TestDoSomeStuff(t *testing.T) {
	m := &myThing{
		doers: map[string]doer{"test": newTestFoo},
	}
	m.doSomeStuff("test", "steve")
}
```

But I can't figure out anyway to call the 'AssertExpectations', because I don't have any reference to the object that was created.  I could change the code so that it stores the result of the constructor into a member of the doSomething struct, but that's an interface and it doesn't have the Assert methods.

Is there some way to mock this out and test it? Am I doing something terribly wrong here?

**Comment by ernesto-jimenez** [comment]
Hi @sjmh,

> Is there some way to mock this out and test it?

Yes

> Am I doing something terribly wrong here?

It's hard to say without knowing what you are implementing. There might be a simpler way to structure your program. I'll be commenting on your specific question :)

### One solution

Here's one option to do what you want:

```go
func TestDoSomeStuff(t *testing.T) {
	m := &TestFoo{}
	m.On("do").Return("Yipee!", nil)
	thing := &myThing{
		doers: map[string]doer{"test": func(_ string) thingInterface {
			return m
		}},
	}
	thing.doSomeStuff("test", "steve")
	m.AssertNumberOfCalls(t, "do", 1)
}
```

Does that work?

If you want to avoid defining that inline function over and over again, you can do something like this:

```go
func (m *TestFoo) doer(_ string) thingInterface {
	return m
}

func newTestFoo(thing string) *TestFoo {
    m := &TestFoo{}
    m.On("do").Return("Yipee!", nil)
    return m
}

func TestDoSomeStuff(t *testing.T) {
	m := newTestFoo(xxx)
	thing := &myThing{
		doers: map[string]doer{"test": m.doer},
	}
	thing.doSomeStuff("test", "steve")
	m.AssertNumberOfCalls(t, "do", 1)
}
```

BTW, I would rename `TestFoo` to `mockFoo`. You are defining a monk rather than a test :)
