### ISSUE TITLE
Proposal: Add Mock.MethodCalls(method string)

### ISSUE THREAD

**Issue by dankinder** [stretchr/testify#246]
Hi, one case we hit frequently while using the mock package is when specifying an expectations using `Mock.On(...)` isn't quite flexible enough. For example we may want to know how many calls were made to a specific method, or check an argument that has inexact parameters (like a varying timestamp).

We have used something like the following multiple times:
```
    calls := []mock.Call{}                                                                                            
    for _, c := range mymock.Calls {                                                                                            
        if c.Method == "TheMethod" {                                                                                   
            calls = append(calls, c)                                                                            
        }                                                                                                                   
    }
```
And wondered if this would be an acceptable addition to the Mock struct:
```
    calls := mymock.MethodCalls("TheMethod")
```

Pretty easy to develop... but figured I'd see first whether anyone would want this.

**Comment by ernesto-jimenez** [comment]
Hi @dankinder,

Mock is pretty flexible already:

e.g: you can [assert the number of calls](https://godoc.org/github.com/stretchr/testify/mock#Mock.AssertNumberOfCalls) to a method already:

```go
m.AssertNumberOfCalls(t, "TheMethod", 3)
```

Or use [Times](https://godoc.org/github.com/stretchr/testify/mock#Call.Times) and [AssertExpectations](https://godoc.org/github.com/stretchr/testify/mock#Mock.AssertExpectations)

```go
m.On("TheMethod", arg1, arg2).Return().Times(5)
m.AssertExpectations(t)
```

Or keep a counter with [Run](https://godoc.org/github.com/stretchr/testify/mock#Call.Run)

```go
var calls int
m.On("TheMethod").Return().Run(func (args mock.Arguments) {
  calls++
})
```

For checking arguments that are inexact you can use [AnythingOfType](https://godoc.org/github.com/stretchr/testify/mock#AnythingOfType)

```go
m.On("TheMethod", mock.AnythingOfType("int")).Return()
```

And we'll _soon_ have [custom argument matching](https://github.com/stretchr/testify/pull/227):

```go
m.On("TheMethod", MatchedBy(func(a int) bool {
    return a == 1
}).Return()
```

What else are you missing?

**Comment by dankinder** [comment]
Hi, custom argument matching does seem to be what I was looking for more or less. I forgot that `AssertNumberOfCalls` existed, so that does handle that case, but this particular proposal was motivated mostly by the need to check inexact arguments. For example the mocked method takes a struct as an argument and one field of that struct is a timestamp that we cannot be sure of ahead of time, but the other fields should match our expectation. I think a custom matcher should handle this.

Thanks for the clear response!

**Comment by ernesto-jimenez** [comment]
Thanks :)

FYI, I just merged the custom argument matching: https://godoc.org/github.com/stretchr/testify/mock#MatchedBy
