### ISSUE TITLE
LICENCE.txt file mispelled

### ISSUE THREAD

**Issue by karlkfi** [stretchr/testify#251]
Should be LICENSE.txt (or just LICENSE).

This makes it hard to file the LICENSE file programmatically. ;)

**Comment by matryer** [comment]
Whoops - UK spelling :)

**Comment by karlkfi** [comment]
If not changed, Godep will not include this file when vendoring (unless Godep itself is changed).
https://github.com/tools/godep/blob/master/license.go#L9
