### ISSUE TITLE
When will there be a new release?

### ISSUE THREAD

**Issue by benma** [stretchr/testify#255]
The last tag, v1.0, is 8 months old. I think it's time for a new release/tag :)

**Comment by ernesto-jimenez** [comment]
Hi Benma,


Sorry. Most developers use the github path rather than the version end package.




I'll check if there's any breaking changes and update the tag.

**Comment by benma** [comment]
Thanks. I think with the Go vendor experiment (GO15VENDOREXPERIMENT=1) you might see people picking a specific commit/tag more often.

**Comment by philtay** [comment]
+1 and please vendor the dependencies in /vendor. currently there is no way to have a reproducible build of testify. tnx

**Comment by benma** [comment]
@ernesto-jimenez 

Any progress on this?

**Comment by ernesto-jimenez** [comment]
@benma just released v1.1

@philtay I vendored the dependencies too.

**Comment by exarkun** [comment]
Any thoughts on whether it's really suitable for a library to vendor its dependencies as testify is now doing?  Consider the discussion at https://groups.google.com/forum/#!topic/golang-nuts/liKQ6gtU4hk which seems to come down against this.

**Comment by ernesto-jimenez** [comment]
@exarkun the way testify is vendoring dependencies is fine because the vendored packages are self-contained within testify's internals. Those packages are used just internally and never used in testify's exported APIs.

**Comment by exarkun** [comment]
Okay, thanks.
