### ISSUE TITLE
Mock: Never Called

### ISSUE THREAD

**Issue by jonny-improbable** [stretchr/testify#256]
Is there any demand for adding a `Never` repeatability to allow you to write expectations like this:

```go
s.myMock.On("MyMethod").Never()
```

My use-case if for testing that code does not get executed when returning early from a function (ie: when error handling) - however I am happy to accept this is unnecessary / leads to brittle tests if others feel so inclined.

**Comment by ernesto-jimenez** [comment]
@jonny-improbable right now an unexpected call results in an panic notifying about an unexpected method call. Is that enough?

**Comment by jonny-improbable** [comment]
Yep, that sounds legit :)
