### ISSUE TITLE
require.FailNow() removed from exported interface following codegen merge

### ISSUE THREAD

**Issue by mattheath** [stretchr/testify#261]
As a result of the code generation PR being merged (#241) the `FailNow()` method is no longer exported from the `require` package.

The `FailNow()` method is still present on the `TestingT` interface within the package, but presumably the code generation doesn't have this?

0d5a14c5a477957864f3b747d95255ad4e34bcc0 - `require.FailNow()` exists
efd1b850c1e5df1c539e83f61f7d5e113b6484e9 - first commit on the codegen branch (#241) removes `require.FailNow()`
c92828f29518bc633893affbce12904ba41a7cfa - #241 merged into master

**Comment by ernesto-jimenez** [comment]
Hi @mattheath,

Thanks for the heads up, looking into it right now.
