### ISSUE TITLE
assert.Contains() does not work with maps.

### ISSUE THREAD

**Issue by jfindley** [stretchr/testify#268]
According to the documentation, assert.Contains() supports maps.

However, if I try to actually do this:
```
assert.Contains(t, map[string]string{"Name": "master"}, "Name", "Result should contain Name")
```

I get the error: ```"map[Name:master]" could not be applied builtin len()```

**Comment by ernesto-jimenez** [comment]
@jfindley are you using the latest version of testify?

**Comment by ernesto-jimenez** [comment]
Support for maps in Contains was added last year: https://github.com/stretchr/testify/commit/1e710e53

You might have an older version of testify in your `GOPATH`, make sure you are using a recent version. Updating to the latest one should be 100% backwards compatible.

**Comment by jfindley** [comment]
Hi, apologies for the noise - for some reason my dep update didn't update this package.  It works fine now.
