### ISSUE TITLE
Support TAP (Test Anything Protocol)

### ISSUE THREAD

**Issue by DAddYE** [stretchr/testify#279]
We should add a flag `-tap` so we can use [different reporters](https://github.com/sindresorhus/awesome-tap#reporters)

Other than gaining fancy reporters:

![](https://github.com/axross/tap-diff/raw/master/screenshot1.png)

It's easier to generate json/xml output ... say for jenkins

**Comment by ernesto-jimenez** [comment]
@DAddYE testify works at the assertion level, rather than tests.

Wouldn't it be better to create a command line tool that runs `go test`, parses the output and and enriches it with lines in the tap format?

**Comment by DAddYE** [comment]
@ernesto-jimenez yeah, I'm investigating that
