### ISSUE TITLE
Equals should show msgAndArgs using %v for single-item case

### ISSUE THREAD

**Issue by rickb777** [stretchr/testify#285]
In assertions.go `func messageFromMsgAndArgs` line 153, the middle case is

```Go
if len(msgAndArgs) == 1 {
	return msgAndArgs[0].(string)
}
```

This only works for strings and prevents, for example, a loop index being passed in.

Suggestion: change it to 

```Go
if len(msgAndArgs) == 1 {
	return fmt.Sprintf("%v", msgAndArgs[0])
}
```

**Comment by exjimsk** [comment]
To pass a loop index, why not just write:

    for _, index := range collection {
        assert.NotZero(t, 1, "%v", index)
    }

**Comment by ernesto-jimenez** [comment]
@rickb777 once we do a v2 of testify, we would probably have:

```go
assert.Error(t, err) // without error message
assert.Errorf(t, err, "optional error %d", i) // with message
```

I doubt we will support `assert.Error(t, err, 1)`, so I'm closing this.
