### ISSUE TITLE
Misleading error when trying to compare two functions

### ISSUE THREAD

**Issue by anacrolix** [stretchr/testify#286]
While Go doesn't support comparing functions to each other natively, 

```
invalid operation: time.Now == time.Now (func can only be compared to nil)
```

the current failure message does not reflect this, and probably could support it anyway for the purposes of tests, maybe by comparing the pointer addresses or something.

```
assert.Equal(t, time.Now, time.Now)

Not equal: (func() time.Time)(0xa6c20) (expected)
                != (func() time.Time)(0xa6c20) (actual)

```

**Comment by ernesto-jimenez** [comment]
@anacrolix unfortunately, it's not possible to rely on comparing pointers:

From the stdlib's docs:
> If v's Kind is Func, the returned pointer is an underlying code pointer, but not necessarily enough to identify a single function uniquely. The only guarantee is that the result is zero if and only if v is a nil func Value.

See issue #159 for full details.

I'll rename the issue to change the error message when trying to compare functions.

**Comment by anacrolix** [comment]
Great, thanks.

**Comment by sivagollapalli** [comment]
@ernesto-jimenez `invalid operation: func can only be compared to nil` is this error message good to throw if anyone tries to compare two functions?
