### ISSUE TITLE
Comparing Dates for Sameness

### ISSUE THREAD

**Issue by cmoesel** [stretchr/testify#290]
I often find that I want to assert that `time.Time` values represent the same moment in time, regardless of location / time zone.  For example, _2016-01-01T12:00:00 UTC (+00:00)_ is the same time as _2016-01-01T07:00:00 EDT (-05:00)_.

If I use `assert.Equal`, it fails the above case because the locations are not equal.  If I use `assert.True` with `time.Time.Equal` (which does the type of equality check I want), then the check is right, but when the assertion fails, the default message is not helpful at all.

Is there a recommended way of doing this?  Am I somehow missing it?  If not, then if I were to submit a PR for a `SameTime` assertion, would you consider merging it?

**Comment by ernesto-jimenez** [comment]
@cmoesel you can customise the message of the error. e.g:

```go
assert.True(t, a.Equal(b), "Not equal: %#v (expected) %#v (actual)", a, b)
```

Assertions take an optional message and set of args. e.g:

```go
func True(t TestingT, value bool, msgAndArgs ...interface{}) bool
```

We can definitely consider merging a function `EqualTimes` like:

```go
func EqualTimes(t TestingT, expected time.Time, actual time.Time, msgAndArgs ...interface{}) bool
```

We'll have to make sure it's clearly documented the assertion will pass for times in different locations :)

Thanks!
Ernesto

**Comment by cmoesel** [comment]
Thanks, @ernesto-jimenez.  I'm aware of the customized messages -- it's just that I need to compare dates so often that it would be a lot of duplication.  I suppose I could just create my own date assertion helper method that does this -- or, perhaps, submit a new `EqualTimes` function as a PR.  I'll keep that in mind if/when I get the time.

You've answered my question, so I'm closing the issue.  Thanks again!
