### ISSUE TITLE
Issue with AssertExpectations(...)

### ISSUE THREAD

**Issue by fantyz** [stretchr/testify#293]
Hi,

I've encountered a problem with `github.com/stretchr/testify/mock`. It seems like the `AssertExceptions(...)` aren't correctly checking whether all the calls has been executed correctly if the same struct is used as an argument but with different values set.

The return value is working as expected though.

This is a very common usecase for me when working with the `github.com/aws/aws-sdk-go` package as they are passing complicated structs to their API all over the place that often will be the same except for very small changes.

Sadly I don't have time to help out with a pull request.

```go
package testifybug

import (
	"fmt"
	"github.com/stretchr/testify/mock"
	"testing"
)

var (
	DoItNow Somethinger = &SomeStruct{}
)

type Somethinger interface {
	DoSomething(*Config) int
}

type Config struct {
	Name   string
	Number int
}

type SomeStruct struct{}

func (s *SomeStruct) DoSomething(cfg *Config) int {
	return cfg.Number
}

type MockSomeStruct struct {
	mock.Mock
}

func (m *MockSomeStruct) DoSomething(cfg *Config) int {
	args := m.Called(cfg)
	return args.Int(0)
}

func TestMockNotWorking(t *testing.T) {
	m := new(MockSomeStruct)

	m.On("DoSomething", &Config{Name: "Config", Number: 1}).Return(1)
	m.On("DoSomething", &Config{Name: "Config", Number: 2}).Return(2)

	DoItNow = m

	DoItNotWorking()

	m.AssertExpectations(t)
}

func TestMockWorking(t *testing.T) {
	m := new(MockSomeStruct)

	m.On("DoSomething", &Config{Name: "Config", Number: 1}).Return(1)
	m.On("DoSomething", &Config{Name: "Config", Number: 2}).Return(2)

	DoItNow = m

	DoItWorking()

	m.AssertExpectations(t)
}

func DoItNotWorking() {
	cfg := Config{
		Name:   "Config",
		Number: 1,
	}
	fmt.Println("NotWorking:", DoItNow.DoSomething(&cfg))
	cfg.Number = 2
	fmt.Println("NotWorking:", DoItNow.DoSomething(&cfg))
}

func DoItWorking() {
	cfg := &Config{
		Name:   "Config",
		Number: 1,
	}
	fmt.Println("Working:", DoItNow.DoSomething(cfg))
	cfg = &Config{
		Name:   "Config",
		Number: 2,
	}
	fmt.Println("Working:", DoItNow.DoSomething(cfg))
}
```

Gives me the result:
```
$ go test -v
=== RUN   TestMockNotWorking
NotWorking: 1
NotWorking: 2
--- FAIL: TestMockNotWorking (0.00s)
	mock.go:361: ❌	DoSomething(*testifybug.Config)
	mock.go:368: ✅	DoSomething(*testifybug.Config)
	mock.go:375: FAIL: 1 out of 2 expectation(s) were met.
			The code you are testing needs to make 1 more call(s).
			at: [testifybug_test.go:47]
=== RUN   TestMockWorking
Working: 1
Working: 2
--- PASS: TestMockWorking (0.00s)
	mock.go:368: ✅	DoSomething(*testifybug.Config)
	mock.go:368: ✅	DoSomething(*testifybug.Config)
FAIL
exit status 1
FAIL	playground/testifybug	0.004s

```

**Comment by ernesto-jimenez** [comment]
@fantyz thank you very much for the clear bug, just confirmed the bug.

The issue is `m.Called` stores the arguments and, in this case, a pointer to the same config is stored, which means that after the change `m.methodWasCalled("DoSomething", &Config{Name: "Config", Number: 1})` returns false because both underlying `Call`s have an argument with `Config{Name: "Config", Number: 2}`.

I'm investigating whether fixing this would break any existing correct behaviour.

**Comment by ernesto-jimenez** [comment]
@fantyz can you check PR #294 ? 

Thanks!

**Comment by fantyz** [comment]
@ernesto-jimenez its working nicely :+1:

Thank you.

**Comment by ernesto-jimenez** [comment]
@fantyz :ok_hand:

It can still fail with `AssertCalled` and `AssertNotCalled` due to how they are implemented, but I've added some docs in the meantime.

**Comment by ernesto-jimenez** [comment]
I merged it already, so you should be ready to go :)

I would suggest you take a look at the `MatchedBy` method too, easily defined expectations when complex structs are expected and you just care about a few fields.
