### ISSUE TITLE
Unreadable output from Mock

### ISSUE THREAD

**Issue by stevenh** [stretchr/testify#295]
Seems like Mock adds output to tests for each assert it does and on my console (ansi xterm) this is not readable e.g.

``` shell
--- PASS: TestMonitor (0.08s)
     mock.go:376: â
     SubClient(string) mock.go:376: â
     NewTimer() mock.go:376: â 
```

I'm guessing its assuming a UTF-8 console setup, which is not ideal.

**Comment by ernesto-jimenez** [comment]
Yes, it uses `\u274c` and `\u2705`.

It would be OK to change it to a text output.
