### ISSUE TITLE
Missing AssignableTo

### ISSUE THREAD

**Issue by anacrolix** [stretchr/testify#297]
I can't find a function that checks for assignability. This is used when you don't want exact IsType similarity.

**Comment by ernesto-jimenez** [comment]
@anacrolix do you want to prepare a PR? I'll be happy to review it and answer any questions :)

**Comment by anacrolix** [comment]
Yes I have a PR coming, I'm trialling the new functionality with my use case first.

**Comment by anacrolix** [comment]
#297

**Comment by anacrolix** [comment]
I'm not using the added methods anymore, see the PR for reasons.
