### ISSUE TITLE
Setting default mock expectations that don't need to be called

### ISSUE THREAD

**Issue by dankinder** [stretchr/testify#300]
This concerns a recent commit that has caused our tests to fail: https://github.com/stretchr/testify/commit/096a13e3a4268e2f80f8ddc43a88581be72d5167

The root issue is that this changed behavior in the following scenario:

```go
package main    
    
import (                                     
    "fmt"        
    "testing"           
                                          
    "github.com/stretchr/testify/mock"    
)    
                                       
type MyMock struct {      
    mock.Mock               
}    
                                        
func (m *MyMock) MyMethod() error {    
    args := m.Called()      
    return args.Error(0)    
}                               
                                   
func TestMyMock(t *testing.T) {                                                                         
    m := MyMock{}                                                                                       
    m.On("MyMethod").Return(fmt.Errorf("ouch")).Once()                                                  
    m.On("MyMethod").Return(nil)                                                                        
                                                                                                        
    m.MyMethod()                                                                                        
    m.AssertExpectations(t)                                                                             
}
```

Before the aforementioned commit (for example on on https://github.com/stretchr/testify/commit/0744955171b0b6e1871ff9d7366abc2b7a7fcec0) this code passed:
```
$ go test main_test.go 
ok  	command-line-arguments	0.004s
```
But after checking out https://github.com/stretchr/testify/commit/096a13e3a4268e2f80f8ddc43a88581be72d5167 I get:
```
$ go test main_test.go 
--- FAIL: TestMyMock (0.00s)
	mock.go:376: ✅	MyMethod()
	mock.go:369: ❌	MyMethod()
	mock.go:383: FAIL: 1 out of 2 expectation(s) were met.
			The code you are testing needs to make 1 more call(s).
			at: [main_test.go:25]
FAIL
FAIL	command-line-arguments	0.004s
```

Now, I can understand why the new behavior may be intentional. But the pattern we are using in this particular example is that on the first call we want to return one result and on subsequent calls we want to return some default value, and there may be 0 or more subsequent calls. The tests that are now failing are the ones that don't make any subsequent calls.

Is there a better way now to express what we are going for?

**Comment by ernesto-jimenez** [comment]
@dankinder the mock package has some inconsistencies with expressions in the package from the early days.

e.g: your example worked because you had the same of args, but this would have failed in the previous version:

```                                                                            
    m.On("MyMethod", "a").Return(fmt.Errorf("ouch")).Once()                                                  
    m.On("MyMethod", "b").Return(nil)                                                                        

    m.MyMethod()                                                                                        
    m.AssertExpectations(t)   
```

The semantics and defaults are definitely messed up, which makes keeping backwards compatibility tricky with all the inconsistencies.

I'm looking into how to address this.

Thanks for the heads up!

**Comment by ernesto-jimenez** [comment]
@dankinder backwards compatibility for all the messy behaviour is more important, so I've made a change that will make your code work again.

**Comment by dankinder** [comment]
Hi @ernesto-jimenez, thanks much for the fast response, it's look good on our end now. Keeping backward-compatibility is awesome so we appreciate that (though we're also willing to make changes on our end when the breaking changes make a lot of sense).
