### ISSUE TITLE
Is it possible to provide an option to exit or pause test program while hitting failure?

### ISSUE THREAD

**Issue by thinkhy** [stretchr/testify#301]
I'm a heavy user of testify/assert package, recently I found it's inconvenience to capture first hand debug data by running testcase with assert package, because there is no unique way to have test program exit or pause while hitting failure.  So if possible, please provide a global option to support FFDC(First Failure Data Capture).

**Comment by ernesto-jimenez** [comment]
@thinkhy can you give an example of what you would like to happen and why? It would help me understand what you need :)

Thanks!

**Comment by thinkhy** [comment]
Thanks for your reply.

Take an example, I'm writing a testcase to invoke a restapi following the procedure:
    
     Login
        |
     Invoke RestAPI
       |
     Logout

Test code is simplified as below:

```
import  (
     .   "github.com/stretchr/testify/assert"
)

func TestRestAPI(t *testing.T) {
        // First login
        request, err := http.NewRequest("POST", Config.LoginUrl, reader)
        Nil(t, err, "Failed to invoke http.NewRequest")
        log.Printf("Post a request at URL %s\n", Config.LoginUrl)
        res, err := http.DefaultClient.Do(request)
        Nil(t, err, "Failed to invoke http.DefaultClient.Do")
        Equal(t, http.StatusOK, res.StatusCode, "")

        // Invoke RestAPI 
        log.Println("+++ Invoke RestAPI xxxx ")
        reader = strings.NewReader(requestJson)
        request, err = http.NewRequest("POST", Config.ApiURL, reader)
        Nil(t, err, "Failed to invoke http.NewRequest")
        request.Header.Set(AuthorizationHeader, jwtToken)
        res, err = http.DefaultClient.Do(request)
        Nil(t, err, "Failed to invoke http.DefaultClient.Do")
        Equal(t, http.StatusOK, res.StatusCode, "")

        // Verify response data, ERROR may occur in this phase
        dec = json.NewDecoder(res.Body)
        var r ResponseData
        err = dec.Decode(&r)
        Nil(t, err, "Failed to parse response JSON")  <== Failure occurs at this line
        Equal(t, 0, r.Ret, "Ret should be correct")
        Equal(t, "OK", r.Info, "Info should be correct")
        Equal(t, .... ..)
       
        // Logout
        request, err := http.NewRequest("POST", Config.LogoutUrl, reader)
        Nil(t, err, "Failed to invoke http.NewRequest")
        ... ....
}

```

Now if the case encounters a failure at the line:    Nil(t, err, "Failed to parse response JSON"),
the case will continue to run code after this lin:

        Equal(t, 0, r.Ret, "Ret should be correct")
        Equal(t, "OK", r.Info, "Info should be correct")
        Equal(t, .... ..)
        // Logout
        ... ....

Which can make debugging more difficult because there are too many extra messages generated in the log files of testcase and web server, we need to take some time to locate the messages referring to above failure.

The ideal case is that assert package provides a global option(stopAtFailure), if we enable the option, the testcase will exit or pause after hitting any error. In above example, after hitting the error "Failed to parse response JSON", the testcase will not continue, at this point, we can check log files to capture first failure data and debug ...

**Comment by ernesto-jimenez** [comment]
@thinkhy there's `testify/require`, which has the same assertions as `testify/assert` but will stop the test when an assertion fails.

Is that what you are looking for? :)

**Comment by thinkhy** [comment]
@ernesto-jimenez  testify/require can resolve the problem while debug the single case. But actually it's not what I'm looking for. 

Consider the scenario, when we commit a new version, CI tool like Jenkins drivers hundreds of test cases(in my project, Jenkins will run command 'go test -v' in container for every components ). If any of these cases fails, I want the 'go test' command to stop in time and return non-zero value, then CI tool quits and return unsuccessful result, at this point it's easier for us to locate failure data and debug test case.

Now my workaround is to add code like below at some key points:
  
      if Equal(....) == false {
         os.Exit(-1)
      }

It would be better for testify package to resolve the problem in an unique and elegant way.

Thanks

**Comment by ernesto-jimenez** [comment]
@thinkhy `require` will call `FailNow` on the `require.TestingT` interface, so you can do something like this:

```go
type testingT struct {
  require.TestingT
}

func (t *testingT) FailNow() {
   os.Exit(-1)
}

func TestSomething(t *testing.T) {
  require.Equal(testingT{t}, 1, 2)
}
```

Basically, wrapping `testing.T` in your own struct with a `FailNow` method that will exit the program.

**Comment by thinkhy** [comment]
The solution works in my project, just notice the first parameter of Equal should be a point rather a struct:

      Nil(**&testingT{t}**, err, "Failed to parse response JSON”) 

Thanks

**Comment by updogliu** [comment]
Stopping the whole process is suboptimal because it won't report test statistics.

I think the direct way to support this is：

1. Add a flag -testify.ff (fail fast)
2. [-testify.ff = true] When constructing testing.InternalTest, before handling SetupTest(), check whether the test suite is already failed. If so, just t.SkipNow().

I can try to write an MR if this solution sounds good.

**Comment by updogliu** [comment]
For now, we use a customized implementation of `suite.TestingSuite` as a work around:

```
import "github.com/stretchr/testify/require"

type RequireSuite struct {
	*require.Assertions
	t, mainT *testing.T
}

func (rs *RequireSuite) T() *testing.T {
	return rs.t
}

// SetT sets the current *testing.T context.
func (rs *RequireSuite) SetT(t *testing.T) {
	rs.Assertions = require.New(t)
	if rs.t == nil {
		rs.mainT = t
	}
	rs.t = t
}

// Called at the beginning of each test case.
func (rs *RequireSuite) SetupTest() {
	if rs.mainT.Failed() {
		rs.T().SkipNow() // this goroutine exits at here
	}
}
```
