### ISSUE TITLE
Include vendored dependencies license files with the vendored dependencies

### ISSUE THREAD

**Issue by exarkun** [stretchr/testify#307]
The dependencies vendored into `vendor`, `github.com/davecgh/go-spew`, `github.com/pmezard/go-difflib`, and `github.com/stretchr/objx` are all missing their top-level license files.

Whether this is technically allowed by the licenses or not might be a non-trivial question to answer.  However, the current state does at least makes license compatibility / validation for downstream users of testify more complicated.  It'd be great if testify could include the licenses of its dependencies alongside those dependencies.

**Comment by ernesto-jimenez** [comment]
@exarkun the vendored dependencies do include the license files:
https://github.com/stretchr/testify/blob/master/vendor/github.com/pmezard/go-difflib/LICENSE
https://github.com/stretchr/testify/blob/master/vendor/github.com/davecgh/go-spew/LICENSE
https://github.com/stretchr/testify/blob/master/vendor/github.com/stretchr/objx/LICENSE.md

**Comment by exarkun** [comment]
So they do.  I don't understand how my checkout ended up missing these files. :(  Sorry for the noise.

**Comment by ernesto-jimenez** [comment]
Did you fetch the dependency with `go get` or with some vendoring tool?

Some vendoring tools will just vendor the code for the package, excluding tests and assets. `godep` (the tool we used to vendor the dependencies) does that, but keeps the LICENSE files.

**Comment by exarkun** [comment]
I used gvt.  It did fetch the testify (@ v1.1.3) license file and it has fetched the license files for a couple other packages I've vendored with it.  Most likely explanation at this point seems like user error but I don't have any guesses about how I could have screwed up in a way to cause license files to be missing for these three packages but everything else to be fine.
