### ISSUE TITLE
Question: mock object from external package

### ISSUE THREAD

**Issue by blacked** [stretchr/testify#310]
Hi guys,

I'm not an expert in go, could you please point me to right way to test function like this:

```go
func fetchProfiles() ([]string, error) {
	filename := filepath.Join(os.Getenv("HOME"), ".aws", CredentialsFileName)

	// Parse credentials file
	f, err := ini.LoadFile(filename)
	if err != nil {
		return []string{}, LoadProfilesList
	}

	// Fill profiles slice with list of profiles
	profiles := []string{}
	for profile := range f {
		profiles = append(profiles, profile)
	}

	return profiles, nil
}
```

Basically, I'm stuck in the beginning, on mocking this line:
```
filename := filepath.Join(os.Getenv("HOME"), ".aws", CredentialsFileName)
```

**Comment by eliquious** [comment]
@blacked Using interfaces makes testing and mocking _much_ easier. You can also use function types that can be used as a poor man's dependency injection. Personally, I would also move all `ENV` operations into `main` and report an error if not found or are empty. If you use an interface for loading the INI file, you can then mock it via [mockery](https://github.com/vektra/mockery) and then test `fetchProfiles` for error conditions.

Hope that helps.

**Comment by blacked** [comment]
@eliquious Thanks! I will refactor it with interfaces.
