### ISSUE TITLE
assert.NoError fails to detect nil interface gotcha

### ISSUE THREAD

**Issue by timstclair** [stretchr/testify#311]
`{assert,require}.{,No}Error` should not use the `isNil` method to check whether errors are nil, as it fails to detect nil interface problems.

Explanation:

Idiomatic error checking in go looks like this:
```go
if err != nil {
  handleError(err)
}
```
Due to the way go handles `nil` interfaces, the following will still trigger the `err != nil` check:
```go
type MyCustomError struct{}
func (e *MyCustomError) Error() string { return "fail"; }

func main() {
	if err := get(); err != nil {  // err is not nil here!
		log.Fatalf("Error: %v", err)
	}
}

func get() error {
	var err *MyCustomError
	if err != nil {  // err IS nil here.
		log.Printf("Not nil: %v", err)
	}
	return err
}
```

However, `assert.NoError` or `require.NoError` would not detect this case:
```go
require.NoError(t, get()) // This passes.
if err := get(); err != nil { t.Fail() } // This fails.
```

**Comment by ernesto-jimenez** [comment]
@timstclair thanks for pointing that out and sorry for the late reply.

I just pushed a fix

**Comment by ernesto-jimenez** [comment]
for reference, here's the commit fixing the issue: d77da35

**Comment by timstclair** [comment]
Thanks for fixing this!
