### ISSUE TITLE
Mock call with struct argument causes "unexpected method call"

### ISSUE THREAD

**Issue by trayo** [stretchr/testify#313]
We are trying to setup a mock for a method that takes a struct as an argument. The only differentiator is what data is contained within the Event struct. We think it might have something to do with our `defer` block, but we aren't certain if it's a problem with our code or a problem with the library here.

This is the mock setup we are doing in our tests:
```
event := S.Event{
  Data: deployEventData,
  Type: "deploy.start",
}
eventManager.On("Emit", event).Return(nil)

eventError := S.Event{
  Data: errors.New("bork"),
  Type: "deploy.error",
}
eventManager.On("Emit", eventError).Return(nil)
```

This is the error we are receiving:
```
mock: Unexpected Method Call
  -----------------------------

  Emit(structs.Event)
          0: structs.Event{Type:"deploy.error", Data:(*errors.Error)(0xc8202becd0)}

  The closest call I have is:

  Emit(structs.Event)
          0: structs.Event{Type:"deploy.start", Data:structs.DeployEventData{Writer:(*bytes.Buffer)(0xc82031cd20), DeploymentInfo:(*structs.DeploymentInfo)(0xc8200f2a80)}}
```

This is the code where the error is occurring:
```
defer func() {
  if err == nil {
    deployFinishEvent := S.Event{
      Type: "deploy.finish",
      Data: deployEventData,
    }
    newErr := d.EventManager.Emit(deployFinishEvent)
    err = newErr
  } else {
    deployErrorEvent := S.Event{
      Type: "deploy.error",
      Data: err,
    }
    newErr := d.EventManager.Emit(deployErrorEvent)
    err = newErr
  }
  fmt.Fprint(out, err)
}()
```

This is the line number from the stack trace of where the error occurred:
`github.com/stretchr/testify/mock/mock.go:302`

(cc @melissanoelle)

**Comment by ernesto-jimenez** [comment]
@trayo @melissanoelle, can you share your complete test and the `%#v` of the value you send to `On` and the one you send to `Emit`?

**Comment by melissanoelle** [comment]
We've have since made a few name changes but the problem still exists. Here is the test:
```
FIt("emits deploy.finish event", func() {
  event = S.Event{
    Data: S.DeployEventData{
      Writer:         &bytes.Buffer{},
      DeploymentInfo: &deploymentInfo,
    },
    Type: "deploy.finish",
  }

  println(fmt.Sprintf("%#v", event))
  eventManager.On("Emit", event).Return(nil).Times(1)

  err := deployer.Deploy(deploymentInfo, buffer)
  Expect(err).ToNot(HaveOccurred())
})
```

And the values, the first is from the test and the second from the code:
```
structs.Event{Type:"deploy.finish", Data:structs.DeployEventData{Writer:(*bytes.Buffer)(0xc8203285b0), DeploymentInfo:(*structs.DeploymentInfo)(0xc8200cca80), RequestBody:io.Reader(nil)}}
structs.Event{Type:"deploy.finish", Data:structs.DeployEventData{Writer:(*bytes.Buffer)(0xc820328620), DeploymentInfo:(*structs.DeploymentInfo)(0xc8200ccc40), RequestBody:io.Reader(nil)}}
```

Thanks for your help @ernesto-jimenez

**Comment by trayo** [comment]
We figured out the problem, but have since switched to hand rolled mocks. The issue was with writing to the buffer in one location and it not being exactly reflected in the other location. This caused the memory addresses to be different and thus the tests to not know what call was supposed to be made.
