### ISSUE TITLE
Assert.Equal panics when asserting byte slices

### ISSUE THREAD

**Issue by thejasbabu** [stretchr/testify#314]
It works fine when i assert same byte slices, but I try to assert 2 different byte slices I get a panic.

func TestByteArray(t *testing.T) {
    a := []byte("Hello")
    b := []byte("Hey")
    assert.Equal(t, a, b)
}

**Comment by ernesto-jimenez** [comment]
@thejasbabu what version of `testify` are you using?

It works properly with the most recent version:

```
--- FAIL: TestByteArray (0.00s)
        Error Trace:    main_test.go:52
        Error:          Not equal: []byte{0x48, 0x65, 0x6c, 0x6c, 0x6f} (expected)
                                != []byte{0x48, 0x65, 0x79} (actual)

                        Diff:
                        --- Expected
                        +++ Actual
                        @@ -1,3 +1,3 @@
                        -([]uint8) (len=5 cap=8) {
                        - 00000000  48 65 6c 6c 6f                                    |Hello|
                        +([]uint8) (len=3 cap=8) {
                        + 00000000  48 65 79                                          |Hey|
                         }

FAIL
FAIL    github.com/ernesto-jimenez/test 0.014s
```

**Comment by jordanorelli** [comment]
this error occurs on version 1.1.13, which is the latest tagged version. This bug occurs for everyone following the project using semver. Afaik, tagging a new patch or minor version will close this issue.

**Comment by georgelesica-wf** [comment]
There have been releases since this issue was updated. If this problem still exists, please re-open and provide additional details. Thanks!
