### ISSUE TITLE
Can assert.Contains be useful for error type as well?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [stretchr/testify#323]
Can we make `assert.Contains` to support `error` types as well. This way, when a long error message is returned, I don't have to use `assert.EqualError`, which requires me to provide the full error message?

Alternatively there can be something like [gocheck](http://labix.org/gocheck)'s wildcards which gives the same option to match to a portion of the error message:

        c.Assert(io.ErrClosedPipe, ErrorMatches, "io: .*on closed pipe")

it's just something cool to have.

**Comment by ernesto-jimenez** [comment]
@ahmetalpbalkan you can already do:

```go
assert.Regexp(t, "io: .*on closed pipe", io.ErrClosedPipe)
```

**Comment by ernesto-jimenez** [comment]
Isn't that enough? :)

**Comment by ahmetalpbalkan** [comment]
@ernesto-jimenez no, because you need to check if `err` is nil first otherwise this will panic:

    assert.Regexp(t, "io: .*on closed pipe", err.Error())

so it becomes

    assert.NotNil(t, err)
    assert.Regexp(t, "io: .*on closed pipe", err.Error())

**Comment by ernesto-jimenez** [comment]
@ahmetalpbalkan I'm inclined to say an extra line is fine.

It is an anti-pattern to parse the contents of `Error()` and adding an assertion to match on errors might be supporting bad practices.

I know it is sometimes unavoidable. In those rare cases, I believe it is fine to have people to do a bit of extra work :)
