### ISSUE TITLE
Add default message to assertion failures

### ISSUE THREAD

**Issue by ggerritsen** [stretchr/testify#329]
There could be an `assert.SetDescription()` (naming to be discussed) with which you could set default output for every assertion failure.

Example:

Instead of doing the following, where the `desc` is passed to every assert call:
```go
func testProperties(p Properties, desc string, t *testing.T) {
	assert := assert.New(t)

	assert.NoError(p.Connect(u, c1), desc)
	conns, err := p.Conn("f")
	if assert.NoError(err, desc) {
		assert.Equal(conns, []string{c1}, desc)
	}
	assert.Equal(p.User(c1), u, desc)
	assert.True(p.Alive(c1), desc)
}
```

We could do this, where we pass the `desc` just once:
```go
func testProperties(p Properties, desc string, t *testing.T) {
	assert := assert.New(t)
	assert.SetDescription(desc)

	assert.NoError(p.Connect(u, c1))
	conns, err := p.Conn("f")
	if assert.NoError(err) {
		assert.Equal(conns, []string{c1})
	}
	assert.Equal(p.User(c1), u)
	assert.True(p.Alive(c1))
}
```

Which would make the test more readable.

Thoughts?

**Comment by sivagollapalli** [comment]
+1 . @ernesto-jimenez Let me your thoughts on this. I would like to give a shot on this.

**Comment by ernesto-jimenez** [comment]
@ggerritsen @sivagollapalli sorry for the late reply. I have had a crazy busy summer.

What the use case for this?

When I need to give general context around a test, I would use [`t.Log`](https://godoc.org/testing#T.Log):

```go
t.Log("some information about the test that will only be seen with `go test -v` or when the test fails")
```

Alternatively, you can use Go 1.7's [`t.Run`](https://godoc.org/testing#T.Run):

```go
func testProperties(p Properties, desc string, t *testing.T) {
    t.Run(desc, func(t *testing.T) {
        assert := assert.New(t)

        assert.NoError(p.Connect(u, c1))
        conns, err := p.Conn("f")
        if assert.NoError(err) {
            assert.Equal(conns, []string{c1})
        }
        assert.Equal(p.User(c1), u)
        assert.True(p.Alive(c1))
    })
}
```

**Comment by ggerritsen** [comment]
@ernesto-jimenez @sivagollapalli no problem! 
The alternative solutions you propose look good, exactly what I need. I just don't want to repeat `desc` in every assert.

Thanks!

**Comment by ernesto-jimenez** [comment]
:+1: Perfect

Closing the issue then :)

Thanks!

**Comment by ggerritsen** [comment]
👍
