### ISSUE TITLE
Go 1.7 error

### ISSUE THREAD

**Issue by stgleb** [stretchr/testify#340]
I'm using Go 1.7 and it fails when i'm running
`go test -v`

i've got

`# github.com/stretchr/testify/assert
../../go/src/github.com/stretchr/testify/assert/assertion_forward.go:10: import /home/stgleb/go/pkg/linux_amd64/net/http.a: object is [linux amd64 go1.6.2 X:none] expected [linux amd64 go1.7 X:framepointer]`

and also i have the same issue when trying to

`go get https://github.com/stretchr/testify/assert`

**Comment by matryer** [comment]
If you delete your $GOPATH/pkg folder, it’ll rebuild all the dependencies (including Testify) in Go 1.7.

Hope that helps

Mat

**Comment by stgleb** [comment]
Thanks
