### ISSUE TITLE
AssertExpectationsForObjects: function call copies lock value

### ISSUE THREAD

**Issue by abesto** [stretchr/testify#342]
I'm on version `1.1.3`.

Calling `mock.AssertExpectationsForObjects(t, mock1.Mock, mock2.Mock)` triggers a `function call copies lock value` alert in `go vet`. A simple workaround to get a clean project is to call `AssertExpectations` one by one for each mock object, but it's tedious and error-prone (which, I guess, is the reason this function exists in the first place).

I guess the solution would involve making the `Mock` a pointer. A less intrusive change could be providing another signature of the same function that accepts pointers, and ask users to manually pass in pointers. (Then maybe later deprecate the by-value signature).

**Comment by ernesto-jimenez** [comment]
@abesto you can now do:

```go
mock.AssertExpectationsForObjects(t, mock1, mock2)
```

It should solve the issue :)
