### ISSUE TITLE
Please update to latest go-spew

### ISSUE THREAD

**Issue by flimzy** [stretchr/testify#348]
As of a few days ago, with https://github.com/davecgh/go-spew/pull/51, the latest version of go-spew now works with GopherJS.

Is it possible to update testify to vendor this version of go-spew, so that testify will also work with GopherJS?

**Comment by AlekSi** [comment]
Also please make a new release (tag).

**Comment by ernesto-jimenez** [comment]
@flimzy fixed.

@AlekSi for the new tag, track #336

I'll tag once I triage the rest of the issues and PRs.
