### ISSUE TITLE
Different slice capacity fails in .Equal()

### ISSUE THREAD

**Issue by mnzt** [stretchr/testify#359]
```
-([]*Market) (len=1 cap=4) {
+([]*Market) (len=1 cap=1) {
```

By default, `json.Unmarshal()` pre-allocated a slice with a capacity of four, I'm guessing this is for a performance gain. However, when unmarshalling JSON as to be used as expected, it causes the test case to fail. Working example of JSON slice capacity: https://play.golang.org/p/PEeMemevO0.

I'm wondering whether the `assert` package could ignore the capacity , or provide another function to assert equality whilst ignoring slice capacity.

**Comment by mnzt** [comment]
This may be an issue with the diff tool

**Comment by mnzt** [comment]
It is the diff tool issue described in #317.

**Comment by dbresson** [comment]
This is still an issue.

**Comment by dineshkumar-cse** [comment]
@dbresson could you share the code with those 2 slices which the comparison failed. In order to reproduce it.
