### ISSUE TITLE
JSONEq considers exponential format and integer values equivalent.

### ISSUE THREAD

**Issue by alexcarol** [stretchr/testify#360]
Go will decode numeric values into float64, which can be misleading. My proposal is to have tests fail if the numbers don't "read" the same.

Test:

```
func TestJSONEq_NotEquivalent(t *testing.T) {
    mockT := new(testing.T)
    False(t, JSONEq(mockT, `{"hello": 1476857243}`, `{"hello": 1.476857243e+09}`))
}
```

If I get green light on this proposal i'll be happy to work on it myself.

**Comment by alexcarol** [comment]
@ernesto-jimenez any news on this? (i assume you're the maintainer of this repo, if not, do you know who is?) thanks!

**Comment by ernesto-jimenez** [comment]
Hi @alexcarol,

That is the expected behaviour.

Those two JSON objects represent the same value:

![screenshot 2016-10-27 15 31 23](https://cloud.githubusercontent.com/assets/1005/19771320/74499b68-9c5a-11e6-8fab-e16b5ee4c850.png)

Comparing JSON should never care about how numbers read, but about the values the objects actually represent.

If you want to assert on how it is actually read, you should be comparing the strings with `assert.Equal`.

If you want to make sure a JSON can be decoded into certain struct you should do 
```go
assert.NoError(t, json.Unmarshal(j, &v))
```

**Comment by alexcarol** [comment]
Thanks for the response.
I wanted this change to be able to test properly a code that modified part of a json, but was supposed to leave elements that I didn't want to modify unchanged. For now i'm using JSONEq, but i'm aware that the code is fragile and someone expecting a number to be an integer could run in trouble.

Maybe the problem is not JSONEq and I should make my ad-hoc comparison function, do you have any advice on how to approach this?

**Comment by alexcarol** [comment]
I'll close it, as this seems like it is not an issue for this project, but I would really appreciate input in my question. Thanks!

**Comment by ernesto-jimenez** [comment]
Hey Alex,

Sorry for the late reply, I'm traveling and messages pile up :)

You can test that unmarshalling the generated JSON into a struct with the types you want succeeds without errors.

Regarding the problem, it sounds like you might be unmarshalling into `map[string]interface{}`. I would unmarshal into a struct or at least then use `mapstructure` or `gounmarshalmap` to copy the information into an actual struct with the right types.

**Comment by alexcarol** [comment]
thanks for the response @ernesto-jimenez :), I'm aware this might not be the ideal place for such debate, so feel free to say so or propose a different place.

To prevent unnecessary unmarshalling of arbitrary json parts I already used json.RawMessage, which worked for my particular test. The issue I encounter is on *how to test* that a json that has an element with an arbitrary unknown structure stays the same. Any input will be appreciated.
