### ISSUE TITLE
Assert panics when comparing 1 to nil

### ISSUE THREAD

**Issue by packrat386** [stretchr/testify#366]
I have an example [here](https://gist.github.com/packrat386/4f276d5b47ad4a3f23d0e4cf333f0cce)

It looks like calling [Kind()](https://github.com/stretchr/testify/blob/master/assert/assertions.go#L311) on the type returned by nil doesn't work.

**Comment by caibirdme** [comment]
The same problem
```
assert.Equal(t, 0, nil)
```
