### ISSUE TITLE
[assert] unknown spew.ConfigState field

### ISSUE THREAD

**Issue by mnzt** [stretchr/testify#378]
This morning I vendored master to run my tests and was greeted by this error.

```# github.com/stretchr/testify/assert
assertions.go:1060: unknown spew.ConfigState field 'DisablePointerAddresses' in struct literal
assertions.go:1061: unknown spew.ConfigState field 'DisableCapacities' in struct literal
```

**Comment by atombender** [comment]
You need to install the latest version of go-spew. If you're using Glide, use `glide up`.

**Comment by ernesto-jimenez** [comment]
As @atombender mentioned, you have to update the dependencies too.
