### ISSUE TITLE
assert.Equal panics if you pass it a nil interface

### ISSUE THREAD

**Issue by natefinch** [stretchr/testify#391]
I have a check that does (effectively)

```go 
var m map[string]interface{}
assert.Equal(t, m["bar"], "something")  
```

This causes this panic:

```
github.com/stretchr/testify/assert.isNumericType(0x0, 0x0, 0xda9400)
	/home/nate/src/github.com/stretchr/testify/assert/assertions.go:311 +0x2b
github.com/stretchr/testify/assert.formatUnequalValues(0x0, 0x0, 0x9c0200, 0xc4201e12b0, 0x0, 0x0, 0x0, 0x0)
	/home/nate/src/github.com/stretchr/testify/assert/assertions.go:301 +0x12e
github.com/stretchr/testify/assert.Equal(0xd9e760, 0xc420538240, 0x0, 0x0, 0x9c0200, 0xc4201e12b0, 0x0, 0x0, 0x0, 0x4aeb00)
	/home/nate/src/github.com/stretchr/testify/assert/assertions.go:281 +0x11c
````

Because formatUnequalValue calls reflect.TypeOf on the interface, which returns nil for nil values, and then isNumericType trying to call t.Kind(), which of course panics.

**Comment by ernesto-jimenez** [comment]
@natefinch have you tried updating testify?

**Comment by ernesto-jimenez** [comment]
@natefinch just checked, and that bug had already been fixed. You just need to update testify.

**Comment by natefinch** [comment]
Crud, sorry.  I thought I had just recently redownloaded testify.  My bad.

**Comment by ernesto-jimenez** [comment]
No worries, I added your example to the test suite to make sure there will be no regressions :)

Have a nice day!
