### ISSUE TITLE
Option to always Fatal

### ISSUE THREAD

**Issue by tj** [stretchr/testify#401]
I've hit a lot of cases where the asserts pass through, then cause a panic due to something being nil. It might be nice to have an option to always fatal for a quick exit, I usually find that nicer personally since the cascading failures are usually due to that one issue anyway. Any thoughts?

**Comment by momoneko** [comment]
You could nest your assertions inside `if` blocks. 

Something like:
```go
if assert.Nil(t, possibleNilObject, "Should not be nil") {
    assert.Equal(t, expectedId, possibleNilObject.Id, "Should match")
} 
```

**Comment by matryer** [comment]
Use the `require` package instead. It will fail immediately.
