### ISSUE TITLE
Equal with precision for float values

### ISSUE THREAD

**Issue by the20login** [stretchr/testify#407]
Regular Equal rarely useful when dealing with floating point types due to their unprecise nature.
Standart solution: separated Equal with precision.
Something like `EqualFloat(testing, actual, expected, precision, messageArgs)` or `EqualFloat(testing, actual, expected, delta, messageArgs)`

**Comment by rikvdh** [comment]
Sorry for bumping this, but doesn't the `InDelta` does what you want?

https://godoc.org/github.com/stretchr/testify/assert#InDelta

**Comment by the20login** [comment]
Yeah, it does exactly what i want.
Looks like I didn't notice it then.
