### ISSUE TITLE
How to assert that a mocked method is called exactly N times?

### ISSUE THREAD

**Issue by joelpresence** [stretchr/testify#415]
Thanks for making testify available!  Much appreciated.

Suppose I have the following:
```
type MockRNGAlgorithm struct {
	mock.Mock
}

func (m MockRNGAlgorithm) Int63n(n int64) int64 {
	args := m.Called(n)
	return int64(args.Get(0).(int64))
}

func TestNewRNG(t *testing.T) {
	assert := assert.New(t)

	var mockRNGAlgorithm MockRNGAlgorithm
	var rngState RNGState = RNGState{InitialSeed: 1, Skipped: 2}

        // I know that Int63n will be called exactly 2 times, but how do I assert that?
	mockRNGAlgorithm.On("Int63n", int64(5)).Times(2).Return(int64(1))

       // The following assert would fail if we used it in place of the statement above
      // mockRNGAlgorithm.On("Int63n", int64(5)).Times(3).Return(int64(1))

	rng := NewRNG(rngState, mockRNGAlgorithm)

	assert.NotNil(rng)
}
```

So it seems like `On` basically handles the "at most 2 times" case but not *exactly* 2 times.  In other words, if I use the original test statement above but modify `NewRNG` to invoke `Int63n` only 1 time, then the test still passes even though the line `mockRNGAlgorithm.On("Int63n", int64(5)).Times(2).Return(int64(1))` has `Times(2)`.  So how could I use testitfy to asset `Int63n is invoked exactly 2 times, returns 1 each time, fail the test if Int63n is called a number of times that is not exactly 2.`  In other words, can we make `Times(2)` be *exactly* 2 times, instead of the current meaning which is *up to 2 times* as I understand it.  I'm happy to help with a PR for an `ExactlyTimes` method or similar if you can give me some hints, or maybe point out how to do it with the current implementation if I'm missing it?  :-)

Thanks!

**Comment by luizpericolo** [comment]
I am having the same problem!

**Comment by luizpericolo** [comment]
Hi, @joelpresence !

I started reading the implementation to see if there was something hidden that could help me, since neither the README nor the provided documentation had any explicit information on it, and I found the method you and I were looking for.

The `Mock` struct has a method called `AssertNumberOfCalls` (that can be found at line 400 on the mock.go file). It takes the testing struct, the name of the method and the amount if times the method should be tested.

In your case I guess it would look something like this:

```
type MockRNGAlgorithm struct {
	mock.Mock
}

func (m MockRNGAlgorithm) Int63n(n int64) int64 {
	args := m.Called(n)
	return int64(args.Get(0).(int64))
}

func TestNewRNG(t *testing.T) {
	assert := assert.New(t)

	var mockRNGAlgorithm MockRNGAlgorithm
	var rngState RNGState = RNGState{InitialSeed: 1, Skipped: 2}

	mockRNGAlgorithm.On("Int63n", int64(5)).Return(int64(1))

	rng := NewRNG(rngState, mockRNGAlgorithm)

        mockRNGAlgorithm.AssertNumberOfCalls(t, "Int63n", 2)

	assert.NotNil(rng)
}
```
I too tried to use `Call.Times` to no avail.

Cheers!

**Comment by ernesto-jimenez** [comment]
As @luizpericolo mentioned, you can assert that using `AssertNumberOfCalls`

@luizpericolo you could have found the assertion in [godoc](https://godoc.org/github.com/stretchr/testify/mock#Mock.AssertNumberOfCalls)

**Comment by koolay** [comment]
`Times(number)` is more nice over `AssertNumberOfCalls`.  And what is usage of `Times`  ?

**Comment by wangshiyuan88** [comment]
> `Times(number)` is more fluent over `AssertNumberOfCalls`. And what is usage of `Times` ?

AssertNumberOfCalls indicate you have to call specific number of calls to pass the test, Times indicate your mock function can only return so many times. 
Such as you can set Times to be 3, but no one actually calls it, your test still passes.

**Comment by boyan-soubachov** [comment]
Hmm, sounds rather ambiguous. If that truly is the case maybe we should look at renaming it for `v2` to something along the lines of `AtMost()`?

**Comment by mvdkleijn** [comment]
@wangshiyuan88 was commenting on a 3 year old comment on a closed issue.

Locking this issue. Please open a new issue if you feel the need to continue with the last two comments.
