### ISSUE TITLE
assert Equal with string that contain "%" attempts to resolve it

### ISSUE THREAD

**Issue by ggeorgiev** [stretchr/testify#416]
assert Equal with a string that contains "%" attempts to resolve it

For example: 	`assert.Equal(t, "something %d", "something else %s")` will result in:

	Error:      	Not equal: 
	            	expected: "something %!d(MISSING)"
	            	received: "something else %!s(MISSING)"

**Comment by HaraldNordgren** [comment]
@ggeorgiev Which version of testify are you using? I cannot reproduce this even on v1.0 which was released in 2015.

**Comment by dolmen** [comment]
Here is the full runnable test case on go.dev/play: https://go.dev/play/p/SQgS39IqR-d

This doesn't happen on testify 1.8.4, so I'm closing as invalid.
