### ISSUE TITLE
Add default struct with mock.Mock (syntactic sugar)

### ISSUE THREAD

**Issue by alexbt** [stretchr/testify#420]
When creating mocks, I usually need to define one or more structs as follow:

I was trying to embedded mock.Mock in a repeatable manner, but I can very well do:
type (
	mockWriter mock.Mock
	mockUsername mock.Mock
	elasticSearchMockNoResult mock.Mock
	elasticSearchMockOneResult mock.Mock
)
```
type (
	mockWriter struct {mock.Mock}
	mockUsername struct {mock.Mock}
	elasticSearchMockNoResult struct {mock.Mock}
	elasticSearchMockOneResult struct {mock.Mock}
)
```

What I like to do, is define a Mock struct that I can just reuse (defined in another go file):
```
type Mock struct {mock.Mock}
```

Now, my previous struct declaration looks like this (I just think it looks nicer):
```
type (
	mockWriter test.Mock
	mockUsername test.Mock
	elasticSearchMockNoResult test.Mock
	elasticSearchMockOneResult test.Mock
)
```
 
**It would be nice if this was available in testify's mock package, so I would just do:**

```
type (
	mockWriter mock.MockStruct
	mockUsername mock.MockStruct
	elasticSearchMockNoResult mock.MockStruct
	elasticSearchMockOneResult mock.MockStruct
)
```

**Comment by alexbt** [comment]
PR: https://github.com/stretchr/testify/pull/421

**Comment by alexbt** [comment]
beginner's misuse of go..

**Comment by alexbt** [comment]
PR: https://github.com/stretchr/testify/pull/421

**Comment by ernesto-jimenez** [comment]
The best syntactic sugar is to use `go generate` to automatically generate the whole mock based on an interface

https://blog.gopheracademy.com/advent-2016/how-to-write-good-tests-for-solid-code/
