### ISSUE TITLE
allow mock to record specified method

### ISSUE THREAD

**Issue by yiminc** [stretchr/testify#437]
Current `Mock.Called(args...)` records a method call, but the method name is the calling method. This limits a very useful use case. We are working on a library, where user could register function with a name. Then those registered functions could be invoked by name from some workflow code. The library is using reflect to get the function and passing in arguments to those registered functions.  We don't know the function signature at our library's compile time. In code, it is conceptually like:
```
lib.Register("foo", func(...) {...})
lib.Register("bar", func(...) {...})
```
Then, the workflow code is something conceptually like:
```
result1 := lib.Invoke("foo", args...)
result2 := lib.Invoke("bar", args...)
processResult(result1, result2).
```
Now, we want our test suite to be able to test those workflow code,and allow user to mock any registered function. User's test code would look like:
```
m.On("foo", args...).Return(some_static_result)
m.On("bar", args...).Return(func(...) {...})
```
Then user assign this mock object m to our test suite, and in our library test framework, before we pass the arguments via reflect to the actual registered function, we want to check if a mock is available by:
```
found, _ := m.findExpectedCall(registeredFnName, arguments)
if found {
  retArgs := m.MethodCalled(functionName, args...)
 // deal with the mock call...
} else {
  // no mock call found, call the actual registered function.
}
```

**Comment by mvdkleijn** [comment]
I believe this was already addressed by PR #444
