### ISSUE TITLE
Non-deterministic failure of mocked function

### ISSUE THREAD

**Issue by Willyham** [stretchr/testify#442]
This is a cross-posted issue which I originally raised with `mockery` [here](https://github.com/vektra/mockery/issues/159), but I suspect that the underlying cause is in the `mock` package rather than in the generated mock.

In a new package:

```golang
package mocktest

type Fooer interface {
	Foo(int) error
}

//go:generate mockery -name Fooer -case underscore
```
and test:
```golang
func TestFoo(t *testing.T) {
	mockFoo := &mocks.Fooer{}
	mockFoo.On("Foo", mock.Anything).Return(nil).Twice()
	mockFoo.On("Foo", mock.Anything).Return(assert.AnError).Once()

	errs := 0
	wg := sync.WaitGroup{}
	wg.Add(3)

	for i := range []int{0, 1, 2} {
		go func(idx int) {
			err := mockFoo.Foo(idx)
			if err != nil {
				errs++
			}
			wg.Done()
		}(i)
	}

	wg.Wait()
	assert.Equal(t, errs, 1)
}

```

Run with:
```bash
 $ for i in `seq 1 100`; do go test ./mocktest/ -run TestFoo; done
```
Sometimes fails:

```
--- FAIL: TestFoo (0.00s)
        Error Trace:    foo_test.go:37
	Error:		Not equal: 0 (expected)
			        != 1 (actual)
```

From debugging it looks like `_m.Called` actually returns `nil` 3 times. This leads me to believe that there is a race condition around `Repeatability` at some point. Changing to this:

```golang
	mockFoo.On("Foo", mock.MatchedBy(func(i int) bool { return i < 2 })).Return(nil).Twice()
	mockFoo.On("Foo", 2).Return(assert.AnError).Once()
```

Results in no failures. Being more specific about those matches is probably always recommended anyway, but I didn't expect mockery to cause a fail even in the other case.

**Comment by ernesto-jimenez** [comment]
@Willyham thanks, the race condition is already fixed.
