### ISSUE TITLE
Consideration for extended panic assertion?

### ISSUE THREAD

**Issue by tartale** [stretchr/testify#445]
There might be an interesting use case for a `assert.PanicsWith()` assertion, where the caller could provide a function to be called to assert on the error that was recovered:

Imagine you're testing a function that should panic before it reaches some mocked methods:
```go
func Function(value int, resource Resource) {
  if value > 0 {
    resouce.Use()
  }
  panic(fmt.Errorf("illegal value"))  
}

func TestFunction(...) {
  mockResource := ...
  // don't stub-out Resource.Use() for this test
  assert.Panics(t, func() { Function(0, mockResource) })
}
```

This test case can pass either because it reached the actual `panic` line (good!) or because it reached the unmocked `Resource.Use()` line (bad!)

One could argue that for this test, you can workaround by stubbing-out all possible resource calls, then verifying that they were not called using `resource.AssertNotCalled()`, but this approach seems brittle and heavy-handed.

Alternatively, what if there were support for a panic-checking callback, like so:

```go
assert.PanicsWith(t, func() { Function(0, mockResource) }, 
        func(err error) { assert.Equals(err.Error(), "illegal value") } )
```

Opinions?  Thank you for the consideration

**Comment by ernesto-jimenez** [comment]
@tartale I would be happy with a PR for `assert.PanicsWithValue`

```go
assert.PanicsWithValue(t, "illegal value", func() { Function(0, mockResource) })
```
