### ISSUE TITLE
objx package in testify still uses sha1

### ISSUE THREAD

**Issue by naveenscs** [stretchr/testify#451]
Hi,

SHA1 is obsoleted already,  I am not sure how the objx package could be used for testing purposes but it is better if sha1 usage could be changed to sha2 family.

testify/vendor/github.com/stretchr/objx/security.go:	"crypto/sha1"
testify/vendor/github.com/stretchr/objx/security.go:	hash := sha1.New()

**Comment by mvdkleijn** [comment]
This issue is one for the github.com/stretchr/objx package. Yes, testify does depend on objx (specifically for mocks) but I don't think we use the features of objx related to sha1.

**Comment by mvdkleijn** [comment]
(we'll revisit dependency upgrades later)
