### ISSUE TITLE
Release that includes `.Subset`?

### ISSUE THREAD

**Issue by zbintliff** [stretchr/testify#457]
Can we get a new release that includes this awesome new assertion?

**Comment by HaraldNordgren** [comment]
@zbintliff Considering the sets are not native to Go, how would you like this implemented? Could `assert.Contains` be used instead?

**Comment by brackendawson** [comment]
Is [this](https://github.com/stretchr/testify/pull/1526#issuecomment-1962909498) what you mean?

**Comment by nickajacks1** [comment]
@brackendawson  https://pkg.go.dev/github.com/stretchr/testify@v1.9.0/assert#Subset

I think this issue can be closed.

**Comment by brackendawson** [comment]
OK, thanks, looks like this is just an invalid issue asking for a release.

**Comment by zbintliff** [comment]
Hello! This issue was opened in 2017. It cand definitely be closed

Thanks!
