### ISSUE TITLE
bug in parallel tests

### ISSUE THREAD

**Issue by yiminc** [stretchr/testify#466]
When enable parallel testing, we would expect the TearDownSuite() to be called after all the tests completed. However, after this commit, https://github.com/stretchr/testify/commit/3104bf5483d3fba84f24933949f0533f4467880b
the parallel testing is broken as the TearDownSuite() is called before tests are done.
Here is a simple repro code to repro:
```
type MyTestSuite struct {
	suite.Suite
}
func TestMySuite(t *testing.T) {
	suite.Run(t, new(MyTestSuite))
}
func (s *MyTestSuite) SetupSuite() {
	fmt.Println("SetupSuite")
}
func (s *MyTestSuite) TearDownSuite() {
	fmt.Println("TearDownSuite")
}
func (s *MyTestSuite) SetupTest() {
	s.T().Parallel()
	fmt.Println("SetupTest")
}
func (s *MyTestSuite) TearDownTest() {
	fmt.Println("TearDownTest")
}
func (s *MyTestSuite) Test_A() {
	time.Sleep(time.Second)
}
func (s *MyTestSuite) Test_B() {
	time.Sleep(time.Second * 2)
}

```
The output of above tests is:
```
SetupSuite
TearDownSuite
SetupTest
SetupTest
TearDownTest
TearDownTest
```

**Comment by thaJeztah** [comment]
relates to https://github.com/stretchr/testify/pull/389, https://github.com/stretchr/testify/issues/346

/cc @bayesianmind @ernesto-jimenez PTAL

**Comment by piepmatz** [comment]
The same problem applies to parallel subtests: `TearDownTest()` is run before the test is completed.
