### ISSUE TITLE
What is the difference between Equal and Equalf?

### ISSUE THREAD

**Issue by cskr** [stretchr/testify#471]
Given `Equalf` essentially invokes `Equal`, why do `*f` even exist as separate functions?

**Comment by bits01** [comment]
I was wondering the exact same thing. Maybe some legacy reason?

**Comment by emou** [comment]
It's a fix for `go vet`. See #339

**Comment by cskr** [comment]
@emou In that case Equal must also behave like `fmt.Print`, not like `fmt.Printf`.

**Comment by mvdkleijn** [comment]
I believe this was answered in the past. If you feel this requires further action, please comment.
