### ISSUE TITLE
ObjectsAreEqual: chan vs <-chan

### ISSUE THREAD

**Issue by lukescott** [stretchr/testify#498]
ObjectsAreEqual sees chan and <-chan of the same channel as not equal.
```go
ch := make(chan string)
chro := (<-chan string)(ch)
println(ch == chro) // true
println(assert.ObjectsAreEqual(ch, chro)) // false
```
This may be intended as ObjectsAreEqualValues works. In my particular case I was using assert.Contains, which uses ObjectsAreEqual internally.

Perhaps you could have a `assert.ContainsFunc(t, slice, value, assert.ObjectsAreEqualValues, msg)` version where you can choose the comparison function.

**Comment by devdinu** [comment]
`reflect.DeepEqual(ch, chro)` returns false and not the testify, so we could close this issue.

**Comment by ernesto-jimenez** [comment]
yes, those two values have different types and are intrinsically different.
