### ISSUE TITLE
diff for Equal failures are not showing per-field diffs

### ISSUE THREAD

**Issue by ahmetb** [stretchr/testify#499]
I just got a failure from assert.Equal with **pointers to a complicated struct**, however the diff is not showing per-field differences as it used to do (if I recall correctly), instead, it just prints the whole struct on a single line and therefore the diff is impossible to figure out the difference:

https://gist.github.com/ahmetb/8531fc15b785a7975bf1c5cdb6fb639b

**Comment by ernesto-jimenez** [comment]
@ahmetb can you share a failing test?

**Comment by ahmetb** [comment]
I’m afraid I no longer have this code but it’s probably fairly easy to replicate. Just create a `struct T` and create a pointer to it, pass the pointer variable of type `*T` to testify.

The main point of this is issue is that it’s not showing per-field diffs (i.e. each field on a separate line). It used to do that, if my memory serves me correctly.

**Comment by devdinu** [comment]
I've tested it with a sample test comparing different `*http.Response` and also `http.Response`, and i've got output which shows field specific diffs.

```
func TestStructEqualDiff(t *testing.T) {
	r1 := &http.Response{Status: "Ok", StatusCode: 200}
	r2 := &http.Response{Status: "Ok", StatusCode: 401}
	assert.Equal(t, r1, r2)
}
```


<img width="1438" alt="screen shot 2018-03-15 at 7 09 26 pm" src="https://user-images.githubusercontent.com/5300055/37466866-d59be4ea-2884-11e8-9487-3fdb6eca3d62.png">

@ahmetb If you face the issue of diff again, please share the test code to reproduce it and reopen it.
@ernesto-jimenez  we could close this. it.
