### ISSUE TITLE
require.Equal: Comparing time.Time after marshalling and unmarshalling is not correct

### ISSUE THREAD

**Issue by clebs** [stretchr/testify#502]
When testing sending data that contains a `time.Time` via JSON the sent data and received data are not equal according to `require.Equal`.

Sample unit test:
```go
import (
	"encoding/json"
	"log"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

type event struct {
	What string
	When time.Time
}

func TestIt(t *testing.T) {

	send := event{
		What: "My birthday",
		When: time.Now(),
	}

	//test marshaling and sending data
	data, err := json.Marshal(send)
	if err != nil {
		log.Fatal("Could not marshal event.")
	}

	//sending ommitted

	// unmarshal obtained data
	receive := event{}
	err = json.Unmarshal(data, &receive)

	if err != nil {
		log.Fatal("Could not unmarshal event.")
	}

	require.Equal(t, send, receive, "Comparing marshal and unmarshal of time.Time.")

}
```

Equal diff output:
```
- When: (time.Time) 2017-09-13 14:54:52.119930466 +0200 CEST m=+0.093164966
+ When: (time.Time) 2017-09-13 14:54:52.119930466 +0200 CEST
```

A possible solution would be having a special comparison for `time.Time` fields using for example Unix timestamps.

**Comment by zbindenren** [comment]
Same issue here.

**Comment by fJancsoSzabo** [comment]
See [https://github.com/golang/go/issues/19502](https://github.com/golang/go/issues/19502).

To summarize the link: this isn't a bug in testify, it's how the time package works.  Marshalling the time drops the monotonic clock reading, as that only has meaning within the current process.  Round trip marshalling and unmarshalling of times will produce different structs.

**Comment by ernesto-jimenez** [comment]
We should use `go-cmp` instead of `reflect.DeepEqual`, which would solve this and some other issues.

There's an issue to track that here: https://github.com/stretchr/testify/issues/535

Contributions more than welcome :)

**Comment by posener** [comment]
Since #535 is kind of stuck, maybe we should add a special case to time.Time?

**Comment by ernesto-jimenez** [comment]
@posener unfortunately, that would require implementing our own version of `go-cmp`, since we would have to look for it recursively.

**Comment by gomezjdaniel** [comment]
Any progress on this?

**Comment by Linesmerrill** [comment]
We just used `go-cmp` to do a basic comparison check. Would be nice to have this baked into the assertion library though. 😉 https://godoc.org/github.com/google/go-cmp/cmp

**Comment by leoleoasd** [comment]
Any progress on this?

**Comment by boyan-soubachov** [comment]
`go-cmp` is on the list of possible features for testify v2 (as it would be a breaking change). If there's some way to cleanly fix this problem without breaking backwards compatibility for now, I'd be happy to review and get it merged for v1.7.0. in the mean-time

**Comment by leoleoasd** [comment]
@boyan-soubachov Maybe we can use the solution of #951 on the `require` package as well??

**Comment by boyan-soubachov** [comment]
> @boyan-soubachov Maybe we can use the solution of #951 on the `require` package as well??

The code for `require` is auto-generated from the `assert` code. Once that's merged, the fix will also be available in the `require` package :)

**Comment by seantcanavan** [comment]
a workaround for me was `assert.Equal(t, time1.UnixMillis(), time2.UnixMillis()`
