### ISSUE TITLE
require.Equals can hang when types are different

### ISSUE THREAD

**Issue by markcampanelli-wf** [stretchr/testify#505]
We have seen an issue (apparently new to testify 69483b4bd14f5845b5a1e55bca19e954e827f1d0) where a require.Equal() call does not return when comparing two ints with different types (like int and int64).

**Comment by kdomanski** [comment]
Can you provide some test cases to reproduce?

**Comment by immesys** [comment]
Actually the types are a red herring for me. I submitted #657 instead
