### ISSUE TITLE
Not a bug,but a suggestion:mocking should be overrideable

### ISSUE THREAD

**Issue by AlexLuya** [stretchr/testify#51]
I am using a BDD framework that supports BeforeEach(),so I want to set some default mocking,then override needed mocking in concrete method,but I found mocking same method with same parameters but different returns,only  first mock will work.So hoping mocking will be overrideable,and this will make test more concise for "big" method with many dependencies.

**Comment by ernesto-jimenez** [comment]
@AlexLuya you just need to specify that each of those method calls is expected only once and then it'll work as @matryer described. See: https://github.com/stretchr/testify/blob/master/mock/mock_test.go#L590

If that's not what you need please reopen the issue or open a new one. thanks!

**Comment by yangshun** [comment]
I think the example has since been changed to: https://github.com/stretchr/testify/blob/master/mock/mock_test.go#L651-L657

**Comment by rockuw** [comment]
@ernesto-jimenez Specifying `Once()` may not be enough. See the following case:

```go
m := NewMockModule()
s := NewModule(m)
m.On("Foo").Return(nil).Once()
s.DoSth() // which may call m.Foo() multiple times, even variable times

m.On("Foo").Return(err) // expecting overrideing
s.DoSth()
```

So overriding is still desirable.
