### ISSUE TITLE
Using percentage sign "assert.Equals" screws output.

### ISSUE THREAD

**Issue by bweston92** [stretchr/testify#515]
Take the following test case
```
func Test_formatRemoteProductBalanceTransferOffer_DisplayRateWithPeriodNA(t *testing.T) {
	r := store.ProductRates{}
	r.BalanceTransfer.OfferRate = "5%"
	r.BalanceTransfer.OfferPeriod = "N/A"

	assert.Equal(t, "5% p.a.", formatRemoteProductBalanceTransferOffer(r))
}
```

When `formatUnequalValues` is called from within `assert.Equal` it outputs
```
--- FAIL: Test_formatRemoteProductBalanceTransferOffer_DisplayRateWithPeriod (0.00s)
	assertions.go:226: 
	Error Trace:	format_test.go:39
	Error:      	Not equal: 	
	            	expected: "5%!p(MISSING).a. for 5 mnths"	
	            	received: "5%! (MISSING)mnths"
FAIL
```
Instead of
```
--- FAIL: Test_formatRemoteProductBalanceTransferOffer_DisplayRateWithPeriod (0.00s)
	assertions.go:226: 
	Error Trace:	format_test.go:39
	Error:      	Not equal: 	
	            	expected: "5% p.a. for 5 mnths"	
	            	received: "5% mnths"
FAIL
```

**Comment by dineshkumar-cse** [comment]
@bweston92 i couldn't reproduce the issue, i have tested with 
```
func TestFormatting(t *testing.T) { ....
	assert.Equal(t, "5% p.a.", someFunc())
}

func someFunc() string { return "5 months" }
```

But i'm getting the output as expected.

`Test_formatRemoteProductBalanceTransferOffer_DisplayRateWithPeriodNA` and the errored function `Test_formatRemoteProductBalanceTransferOffer_DisplayRateWithPeriod` is different. I'm guessing you're using `fmt.Sprintf(...)` and missed something. if still happens, share the code of the failed test functions.

**Comment by bweston92** [comment]
@dineshkumar-cse thanks for replying, I can see the example you've provided works so I have no idea what went on. Thanks for your time.
