### ISSUE TITLE
Sub tests are not supported

### ISSUE THREAD

**Issue by bojan-embroker** [stretchr/testify#517]
Error Stack is empty when require or assert are used with testing.T returned from t.Run()

**Comment by devdinu** [comment]
Could you share the test code, with actual and expected output, so we could reproduce. 

when the subtests are run, its gets a new instance 
```
Run("", func(t *testing.T) // t is a new instance
```

When you say error stack, which one are you mentioning specifically?

**Comment by mvdkleijn** [comment]
Closing for lack of information
