### ISSUE TITLE
Some assert.XXXXf methods have no error msg params

### ISSUE THREAD

**Issue by GreenGeorge** [stretchr/testify#528]
Hi,

I was trying to use the `assert.HTTPSuccessf` method and found it's missing the formatted error message functionality and it's implementation signature is different from the docstring

from `assertion_format.go`

```go
// HTTPSuccessf asserts that a specified handler returns a success status code.
//
// assert.HTTPSuccessf(t, myHandler, "POST", "http://www.google.com", nil, "error message %s", "formatted")
// * The above example suggests there is a `msg string` param to output error messages
//
// Returns whether the assertion was successful (true) or not (false).
func HTTPSuccessf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values) bool {
  return HTTPSuccess(t, handler, method, url, values)
}
// * The above implementation accepts no `msg string` param
// * And as I understand it, it makes `HTTPSuccessf` exactly the same as `HTTPSuccess`
```
furthermore, there seems to be several `XXXXf` methods with no error msg param, namely:
`HTTPBodyContainsf`, `HTTPBodyNotContainsf`, `HTTPErrorf`, `HTTPSuccessf`

They seem to only wrap around the non-f methods and pass parameters as is.
If this is an issue and not me having a brainfart, point me and I'll do a PR

**Comment by ernesto-jimenez** [comment]
@GreenGeorge thanks, fixed in #537
