### ISSUE TITLE
Unknown field 'DisablePointerAddresses' in struct literal of type spew.ConfigState

### ISSUE THREAD

**Issue by bxcodec** [stretchr/testify#574]
It seems your third-party library's `github.com/davecgh/go-spew` have a breaking changes

Got Error
```bash
vendor/github.com/stretchr/testify/assert/assertions.go:1253:25: 
unknown field 'DisablePointerAddresses' in struct literal of type spew.ConfigState
```

**Comment by devdinu** [comment]
Can you share more information or test code to reproduce the issue.

**Comment by bxcodec** [comment]
I'm using glide as my package management. 
I'm trying to update some package, and for some reasons, this package `github.com/davecgh/go-spew`  was updated. 

And after finishing the `glide up`, when running the project's test, I got the error 
```vendor/github.com/stretchr/testify/assert/assertions.go:1253:25: 
unknown field 'DisablePointerAddresses' in struct literal of type spew.ConfigState```

After looking for the source code, it seems the `go-spew`  has a few breaking changes.  

For now, to solve my own issue, I just stay back with the old version of `github.com/davecgh/go-spew`

**Comment by devdinu** [comment]
Both [config.go](https://github.com/davecgh/go-spew/blob/master/spew/config.go#L72) in master branch and `v1.1.0` of spew has `DisablePointerAddresses` in ConfigState. i'm surprised how glide update resulted in that change.

**Comment by bxcodec** [comment]
Hmm.. Weird. 
I think this the glide issue then. 
I will close this issue. 
Thank you for your response.
