### ISSUE TITLE
Named tabular tests wrong test log

### ISSUE THREAD

**Issue by rzajac** [stretchr/testify#578]
How do I properly do named tabular tests?

I have tird:

	func (suite *UserTestSuite) TestUser_HasRole() {
	    tt := []struct {
	        Name  string
	        Roles []*Role
	        Role  string
	        Exp   bool
	    }{
	        {
	            "test0", // This one is failing
	            []*Role{{Role: "r2", Aux: "a2"}},
	            "r2:a1",
	            true,
	        },
	        {
	            "test1",
	            []*Role{{Role: "r1", Aux: "a1"}},
	            "r1:a1",
	            true,
	        },
	    }

	    for _, tc := range tt {
	        suite.T().Run(tc.Name, func(t *testing.T) {
	            u := NewEmptyUser()
	            u.Roles = tc.Roles
	            suite.Equal(tc.Exp, u.HasRole(tc.Role))
	        })
	    }
	}

which gives me log like this:

	...
	--- FAIL: TestUserTestSuite (0.00s)
	    --- FAIL: TestUserTestSuite/TestUser_HasRole (0.00s)
	        Error Trace:    user_test.go:198
	    	Error:      	Not equal: 
	    	            	expected: true
	    	            	actual  : false
	    	Test:       	TestUserTestSuite/TestUser_HasRole
	        --- PASS: TestUserTestSuite/TestUser_HasRole/abc0 (0.00s)
	        --- PASS: TestUserTestSuite/TestUser_HasRole/abc1 (0.00s)
	...

It does not mark the failed case correctly. The interesting thing is that if I change the order of tests I get:

	...
	--- FAIL: TestUserTestSuite (0.00s)
	    --- FAIL: TestUserTestSuite/TestUser_HasRole (0.00s)
	        --- PASS: TestUserTestSuite/TestUser_HasRole/abc1 (0.00s)
	        Error Trace:    user_test.go:198
	    	Error:      	Not equal: 
	    	            	expected: true
	    	            	actual  : false
	    	Test:       	TestUserTestSuite/TestUser_HasRole
	        --- PASS: TestUserTestSuite/TestUser_HasRole/abc0 (0.00s)
	...

which also not really correct. 

I'm expecting result to be the same as with build-in testing package:

	--- FAIL: TestUser_HasRole (0.00s)
	    --- FAIL: TestUser_HasRole/abc0 (0.00s)
	        Error Trace:    user_test.go:199
	    	Error:      	Not equal: 
	    	            	expected: true
	    	            	actual  : false
	    	Test:       	TestUser_HasRole/abc0
	    --- PASS: TestUser_HasRole/abc1 (0.00s)

What am I doing wrong?

I'm using the latest 1.2.1 version.

**Comment by devdinu** [comment]
```		
{
	"true test1",
	true,
},
{
	"false test0", // This case fails
	false,
},
``` 
I had a similar suite, and tested with `assert.True(tc.Name, tc.Exp)` which results in the following output. when i reordered the result FAIL: is proper.

![image](https://user-images.githubusercontent.com/5300055/37949068-ab61d736-31b0-11e8-8348-226b4c7cc878.png)

@rzajac The test code you shared is different than the test output. could you be specific and let us know if its still needs some fix, and share the code.

**Comment by rzajac** [comment]
@devdinu My full test looks like this:

    type AUserTestSuite struct {
        suite.Suite
    }

    func TestAUserTestSuite(t *testing.T) {
        suite.Run(t, new(AUserTestSuite))
    }

    func (suite *AUserTestSuite) TestAUser_HasRole() {
        tt := []struct {
            Name  string
            Roles []*Role
            Role  string
            Exp   bool
        }{
            {
                "role aux does not match",
                []*Role{{Role: "r2", Aux: "a2"}},
                "r2:a1",
                true,
            },
            {
                "role matches",
                []*Role{{Role: "r1", Aux: "a1"}},
                "r1:a1",
                true,
            },
            {
                "base role does not match",
                []*Role{{Role: "r1", Aux: "a1"}},
                "r2:a1",
                false,
            },
            {
                "role matches no aux",
                []*Role{{Role: "r2"}},
                "r2",
                true,
            },
            {
                "base role does not exist",
                []*Role{{Role: "r2"}},
                "r1",
                false,
            },
            {
                "empty roles",
                []*Role{},
                "r1",
                false,
            },
        }

        for _, tc := range tt {
            suite.T().Run(tc.Name, func(t *testing.T) {
                u := NewEmptyUser()
                u.Roles = tc.Roles
                suite.Equal(tc.Exp, u.HasRole(tc.Role))
            })
        }
    }

which produces the output:

    === RUN   TestAUserTestSuite
    === RUN   TestAUserTestSuite/TestAUser_HasRole
    === RUN   TestAUserTestSuite/TestAUser_HasRole/role_aux_does_not_match
    === RUN   TestAUserTestSuite/TestAUser_HasRole/role_matches
    === RUN   TestAUserTestSuite/TestAUser_HasRole/base_role_does_not_match
    === RUN   TestAUserTestSuite/TestAUser_HasRole/role_matches_no_aux
    === RUN   TestAUserTestSuite/TestAUser_HasRole/base_role_does_not_exist
    === RUN   TestAUserTestSuite/TestAUser_HasRole/empty_roles
    --- FAIL: TestAUserTestSuite (0.00s)
        --- FAIL: TestAUserTestSuite/TestAUser_HasRole (0.00s)
            Error Trace:    user_test_test.go:66
            Error:          Not equal: 
                            expected: true
                            actual  : false
            Test:           TestAUserTestSuite/TestAUser_HasRole
            --- PASS: TestAUserTestSuite/TestAUser_HasRole/role_aux_does_not_match (0.00s)
            --- PASS: TestAUserTestSuite/TestAUser_HasRole/role_matches (0.00s)
            --- PASS: TestAUserTestSuite/TestAUser_HasRole/base_role_does_not_match (0.00s)
            --- PASS: TestAUserTestSuite/TestAUser_HasRole/role_matches_no_aux (0.00s)
            --- PASS: TestAUserTestSuite/TestAUser_HasRole/base_role_does_not_exist (0.00s)
            --- PASS: TestAUserTestSuite/TestAUser_HasRole/empty_roles (0.00s)
    FAIL
    exit status 1
    FAIL    git.boxdrop.net/go/auth/pkg/auth    0.009s

The test ` --- PASS: TestAUserTestSuite/TestAUser_HasRole/role_aux_does_not_match` should be marked as FAIL but it is not. 

Changing to `suite.True(tc.Exp == u.HasRole(tc.Role))` as you suggested did not help the log is still not accurate.

**Comment by devdinu** [comment]
@rzajac There's still unknowns `NewEmptyUser()` and `u.HasRole` logic, which makes it hard to help. Could you narrow down or share a simple version, where there's no hidden logic (unknowns), and point out what's wrong with testify. some test suite i could run, so we could fix it.

for this case `role_aux_does_not_match` what i could guess is, you're assigning `[]*Role` to user and checking `string` version of a role exist. I'm not sure why `[]*Role{{Role: "r2", Aux: "a2"}}` should result in `r2:a1`, were you supposed to check `r2:a2` ? The logic inside `HasRole` decides it. (The usage of testify is purely `suite.True(true)` or `suite.True(false)` in this case)

**Comment by rzajac** [comment]
@devdinu Below is the full self contained example of the code and test.

code:

    type ARole struct {
        Role string
        Aux  string
    }

    type AUser struct {
        Roles []*ARole
    }

    func (r *ARole) Name() string {
        ra := r.Role
        if r.Aux != "" {
            ra = ra + ":" + r.Aux
        }
        return ra
    }

    func NewAUser() *AUser {
        return &AUser{Roles: make([]*ARole, 0)}
    }

    func (u *AUser) HasRole(role string) bool {
        for _, ur := range u.Roles {
            if ur.Name() == role {
                return true
            }
        }
        return false
    }

 tests:

    import (
        "testing"

        "github.com/stretchr/testify/suite"
    )

    type AUserTestSuite struct {
        suite.Suite
    }

    func TestAUserTestSuite(t *testing.T) {
        suite.Run(t, new(AUserTestSuite))
    }

    func (suite *AUserTestSuite) TestAUser_HasRole() {
        tt := []struct {
            Name  string
            Roles []*ARole
            Role  string
            Exp   bool
        }{
            {
                "role aux does not match",
                []*ARole{{Role: "r2", Aux: "a2"}},
                "r2:a1",
                true, // This should be false. I set it to true to make test fail.
            },
            {
                "role matches",
                []*ARole{{Role: "r1", Aux: "a1"}},
                "r1:a1",
                true,
            },
            {
                "base role does not match",
                []*ARole{{Role: "r1", Aux: "a1"}},
                "r2:a1",
                false,
            },
            {
                "role matches no aux",
                []*ARole{{Role: "r2"}},
                "r2",
                true,
            },
            {
                "base role does not exist",
                []*ARole{{Role: "r2"}},
                "r1",
                false,
            },
            {
                "empty roles",
                []*ARole{},
                "r1",
                false,
            },
        }

        for _, tc := range tt {
            suite.T().Run(tc.Name, func(t *testing.T) {
                u := NewAUser()
                u.Roles = tc.Roles
                suite.True(tc.Exp == u.HasRole(tc.Role)) // a_user_test.go:66 this fails as it should for the case 
    "role aux does not match"            
    })
        }
    }

which results in log:


    === RUN   TestAUserTestSuite
    === RUN   TestAUserTestSuite/TestAUser_HasRole
    === RUN   TestAUserTestSuite/TestAUser_HasRole/role_aux_does_not_match
    === RUN   TestAUserTestSuite/TestAUser_HasRole/role_matches
    === RUN   TestAUserTestSuite/TestAUser_HasRole/base_role_does_not_match
    === RUN   TestAUserTestSuite/TestAUser_HasRole/role_matches_no_aux
    === RUN   TestAUserTestSuite/TestAUser_HasRole/base_role_does_not_exist
    === RUN   TestAUserTestSuite/TestAUser_HasRole/empty_roles
    --- FAIL: TestAUserTestSuite (0.00s)
        --- FAIL: TestAUserTestSuite/TestAUser_HasRole (0.00s)
            Error Trace:    a_user_test.go:66
            Error:          Should be true
            Test:           TestAUserTestSuite/TestAUser_HasRole
            --- PASS: TestAUserTestSuite/TestAUser_HasRole/role_aux_does_not_match (0.00s)
            --- PASS: TestAUserTestSuite/TestAUser_HasRole/role_matches (0.00s)
            --- PASS: TestAUserTestSuite/TestAUser_HasRole/base_role_does_not_match (0.00s)
            --- PASS: TestAUserTestSuite/TestAUser_HasRole/role_matches_no_aux (0.00s)
            --- PASS: TestAUserTestSuite/TestAUser_HasRole/base_role_does_not_exist (0.00s)
            --- PASS: TestAUserTestSuite/TestAUser_HasRole/empty_roles (0.00s)
    FAIL
    exit status 1
    FAIL    git.boxdrop.net/go/auth/pkg/auth    0.010s

Just to clarify the testify assertions work as expected. But the error log doesn't reflect which case in particular failed. SO if you have many tests you just know that something went wrong with one of the cases for `TestAUserTestSuite/TestAUser_HasRole`

The expected result would be at least having line:

     --- PASS: TestAUserTestSuite/TestAUser_HasRole/role_aux_does_not_match (0.00s)

read:
           
     --- FAIL: TestAUserTestSuite/TestAUser_HasRole/role_aux_does_not_match (0.00s)

**Comment by iliacimpoes** [comment]
try instead of:
```go
suite.T().Run(tc.Name, func(t *testing.T) {
            u := NewEmptyUser()
            u.Roles = tc.Roles
            suite.Equal(tc.Exp, u.HasRole(tc.Role))
        })
```
```go
suite.T().Run(tc.Name, func(t *testing.T) {
            u := NewEmptyUser()
            u.Roles = tc.Roles
            assert.Equal(t, tc.Exp, u.HasRole(tc.Role))
        })
```
assertion should be made on `testing.T` not on `suite`

**Comment by rzajac** [comment]
Sorry it took so long. The @iliacimpoes comment solves the issue.
