### ISSUE TITLE
Assert a struct object equals to the other one without some properties？

### ISSUE THREAD

**Issue by tommy-zhouketao** [stretchr/testify#580]
I wish the assertion return true for asserting two object with the same struct are equal even though they have some specified properties with different values.

**Comment by devdinu** [comment]
You could separately assert the properties which you need from the structs.
```
  assert.Equal(t, exp.p1, actual.p1)
  ...
  assert.Equal(t, exp.pN, actual.pN)
```
 we don't have a feature where you could say both struct are same excluding some fields.

**Comment by tommy-zhouketao** [comment]
Ok, thank you very much!
