### ISSUE TITLE
[Question]: Mock.On Usage

### ISSUE THREAD

**Issue by tobilen** [stretchr/testify#583]
i've been trying to implement this mock, and according to the docs it should work. Am i doing something wrong?
Other mock instances work fine.

https://play.golang.org/p/hHMT32CKwtY

test output:
```
Error Trace:    websocket_test.go:89
Error:          Not equal: 
                expected: "expected"
                actual  : "websocket mock implementation"
Test:           TestWebsocket_ReadMessage

Process finished with exit code 1
```

thanks!

**Comment by AlexMarold** [comment]
We've solved this with calling 'Called' and assigning (and casting) the return vars.

https://play.golang.org/p/Afp45gkG7rS
