### ISSUE TITLE
Cannot install testify/mock via dep tool

### ISSUE THREAD

**Issue by cpapidas** [stretchr/testify#604]
Cannot install testify/mock via dep tool

command `dep ensure`

**Comment by ernesto-jimenez** [comment]
@cpapidas can you provide steps to reproduce the issue?

I use `testify/mock` and `dep` in all my projects without issues.

**Comment by cpapidas** [comment]
1. install the lib via dep
2. try to import the testify/mock in tests file
3. cannot find the package

**Comment by devdinu** [comment]
I've used dep to download, and able to resolve `testify` dependency and could write tests with it.

**Comment by medzin** [comment]
@cpapidas did you add `testify` to the toml file with `dep ensure -add` command or did you just call the `dep ensure` command on the project? In the second case only the packages imported in your code will be downloaded.

**Comment by cpapidas** [comment]
I just call dep ensure, I think we should write it in readme.md file
