### ISSUE TITLE
Require doesn't stop test immediately

### ISSUE THREAD

**Issue by mwei0210** [stretchr/testify#605]
So I was using require.NoError(t, err) and an error was returned which means the test should stop immediately, but instead, the next line was executed too, is this a known bug?

**Comment by solarfly73** [comment]
I didn't even know about NoError(), always used require.Nil.  Anyway I tried to reproduce for fun and could not, with the following: 

```
package main

import (
    "fmt"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
)

func evil() error {
    return fmt.Errorf("Blowing up!")
}

func afterTheFact() int {
    return 1
}

func TestEvil(t *testing.T) {
    err := evil()
    require.NoError(t, err)
    after := afterTheFact()
    fmt.Printf("%d\n", after)
    assert.Equal(t, 1, after)
}
```

**Comment by mwei0210** [comment]
I solved it by specifying test to be ran on one thread

**Comment by ernesto-jimenez** [comment]
@mwei0210 cannot reproduce it with the latest version of testify. Please reopen with steps to reproduce if you still encounter the issue.

**Comment by sjindal-arista** [comment]
The same as happened with me while using the function `require.NoError(..) ` 
 the execution doesn't stop when it should have.

Version used: `v1.6.1`
