### ISSUE TITLE
Method call not recognized

### ISSUE THREAD

**Issue by R4c00n** [stretchr/testify#609]
When I try to assert a method call with `.On` I get the following error message when executing my tests:
`The code you are testing needs to make 1 more call(s).`

I'm using go version 1.8.7.

I made up a quick example to demonstrate my setup:

```
package foo

import (
	"testing"
	"github.com/stretchr/testify/mock"
)

type SomeServiceInterface interface {
	DoSomethingInService()
}

type SomeServiceMock struct {
	mock.Mock
}

func (s *SomeServiceMock) DoSomethingInService() {

}

type Sut struct {
	SomeService SomeServiceInterface
}

func (s *Sut) DoSomething() {
	s.SomeService.DoSomethingInService()
}

func TestDoSomething(t *testing.T) {
	someServiceMock := new(SomeServiceMock)
	someServiceMock.On("DoSomethingInService")

	sut := Sut{SomeService: someServiceMock}

	sut.DoSomething()

	someServiceMock.AssertExpectations(t)
}
```

**Comment by devdinu** [comment]
@R4c00n In `func (s *SomeServiceMock) DoSomethingInService() {` you 've to add
`s.Called()` which registers the call in mock, and that's verified later in `AssertExpectations`.

**Comment by R4c00n** [comment]
@devdinu Thanks, works like a charm!
