### ISSUE TITLE
Mocking a function from within a function

### ISSUE THREAD

**Issue by ramzdam** [stretchr/testify#610]
Is there a way to achieve this? I want to Mock the response of a function call from within another function call. Example

```go
// main.go
func TheFunction() int {
   // Some code
   val := ToMockResponse()
   return val
}

func ToMockResponse() int {
    return 123
}
```
and in my test file

```go
// main_test.go
func TestTheFunction(t *testing.T) {
    mockInstance = new(randomMock)
    mockInstance.On("ToMockResponse").Return(456)

    returned := TheFunction()
    assert.Equal(t, 456, returned)
}
```

I'm not sure if what I did is correct. What I'm trying to achieve is that I just want to have a Mock response of **ToMockResponse** whenever it's being called inside **TheFunction**

I have seen and read most of the tutorial but all of them shows a Mock response from a method of a class. But there are no function to function mocking samples. Hope you can provide a solution to this.

**Comment by devdinu** [comment]
When its purely a function you can't do it. What you need to have is a struct injected in TheFunction (with use of struct or closure), then you can mock the response of the ToMockResponse

```
// service mock for TheFunction
type service struct {  mock.Mock }

func (s service) ToMockResponse() int {
    return s.Called().Int(0)
}

func Something(s service) func() int {
   return func() int {
       // TheFunction implementation
       return s.ToMockResponse()
  }
}

```

**Comment by ramzdam** [comment]
func Something(s service) func() int {
   return func() int {
       // TheFunction implementation
       return s.ToMockResponse()
  }
}

What does this function do? Sorry kinda new with Go Lang and testify

**Comment by Kerptastic** [comment]
@ramzdam did you find a suitable solution based on @devdinu response? I am having a similar issue and from a design perspective, don't know how to cleanly wrap initializer functions in an interface/struct.

So I have an initializer, that returns an instance that inherently implements a MongoDatabase interface.

```
func NewMongoDatabaseBasic(dbHost string, dbTimeout uint64) (MongoDatabase, error) {
	mongoClient, err := createBasicClient(dbHost, dbTimeout)
	if err != nil {
		return MongoDatabaseImpl{}, err
	}

	return MongoDatabaseImpl{client: mongoClient}, nil
}
```
And I am trying to test this function using mocks...
```
func NewCandidateDatastore(dbHost string, dbTimeout uint64, dbName string) (Datastore, error) {
	var myDbName string

	if len(dbName) == 0 {
		myDbName = DEFAULT_DB_NAME
	} else {
		myDbName = dbName
	}

	db, err := ds.NewMongoDatabaseBasic(dbHost, dbTimeout)

	if err != nil {
		return nil, err
	}

	return &candidateDatastore{
		db:     db,
		dbName: myDbName,
	}, nil
}
```
Maybe my approach is flawed, but I would figure to mock the `ds.NewMongoDatabaseBasic` function call to return a mocked instance, and then ensure that the returned `&candidateDatastore` has the mocked instance, and the `dbName` string but I cant achieve it, much like your issue.

Thoughts?

**Comment by Kerptastic** [comment]
I guess what I could do, is move the call to `ds.NewMongoDatabaseBasic()` and pass in the instance of the interface. Would abstract out the creation, and allow passing in different implementations, just feels like a bit of overkill. 

Another option I considered was creating a DatabaseFactory interface, and pass the factory in. 

```
type DatabaseFactory interface {
	NewMongoDatabaseBasic(dbHost string, dbTimeout uint64) (mongodb.MongoDatabase, error)
	NewMongoDatabaseSecure(dbHost string, dbTimeout uint64, certPath string) (mongodb.MongoDatabase, error)
}

type DatabaseFactoryImpl struct {
}
```

I would then be able to mock the factory to return my mocked database. Again, doesnt "feel" clean.

```
func NewCandidateDatastore(factory dbFactory.DatabaseFactory, dbHost string, dbTimeout uint64, dbName string) (Datastore, error) {
	var myDbName string

	if len(dbName) == 0 {
		myDbName = DEFAULT_DB_NAME
	} else {
		myDbName = dbName
	}

	db, err := factory.NewMongoDatabaseBasic(dbHost, dbTimeout)

	if err != nil {
		return nil, err
	}

	return &candidateDatastore{
		db:     db,
		dbName: myDbName,
	}, nil
}
```
