### ISSUE TITLE
`vgo vendor` fail

### ISSUE THREAD

**Issue by mwf** [stretchr/testify#615]
Hi guys!

FYI I found an issue regarding vgo usage along with go-spew and testify - golang/go#25871

Any project using testify can't be vendored with `vgo vendor` command.

Could you please subscribe to it?
Maybe it's worth taking part in the discussion in case of any concerns from Go team.

Many thanks :)

**Comment by ernesto-jimenez** [comment]
Hi @mwf,

That right now depends on some `vgo` fixes or us making some breaking changes. See https://github.com/stretchr/testify/pull/607

**Comment by mwf** [comment]
Actually it doesn't depend on you, it's just a bug in vgo and they're going to fix it.

**Comment by mwf** [comment]
vgo is fixed, closing the issue
