### ISSUE TITLE
formatUnequalValues with %v instead of %#v?

### ISSUE THREAD

**Issue by misterikkit** [stretchr/testify#626]
Is there a way to get the default format when assert.Equal fails? Specifically, I am comparing time.Duration values, and getting an int64 of microseconds is not as friendly as Duration.String. ([example](https://play.golang.org/p/vA3xeX5-OEr))

I understand that the current behavior is generally more useful. Rather than changing the default, I am hoping there is some option I can invoke to make my own test output more readable.

Sample output:
```
        assertions.go:256:
                        Error Trace:    integration_test.go:125
                        Error:          Not equal:
                                        expected: 180000000000
                                        actual  : 0
                        Test:           TestDurationFormat
```

Preferred output:
```
        assertions.go:256:
                        Error Trace:    integration_test.go:125
                        Error:          Not equal:
                                        expected: 3m0s
                                        actual  : 0s
                        Test:           TestDurationFormat
```

**Comment by raideus** [comment]
+1 

I'm having the same problem
