### ISSUE TITLE
mock.MatchedBy cannot match against context.Context, always get Unexpected Method Call

### ISSUE THREAD

**Issue by abhinav3295** [stretchr/testify#645]
I am trying to mock a function that has `context.Context` as an argument.
But when I use `mock.Anything` tests run fine, but on using `mock.MatchedBy` I am always getting `Unexpected Method Call`

```
func TestSomeClass_funcA(t *testing.T) {
	helper := MockHelper{}
	helper.On("funcA", mock.MatchedBy(func(ctx context.Context) bool {
		return ctx.Value("foo-bar") != nil
	})).Return(true)
	main := MainClass{
		helper: helper,
	}
	assert.True(t, main.funcMain())
}
```

sample project to reproduce the bug is attached.
[reproduceStrecherBug.zip](https://github.com/stretchr/testify/files/2263605/reproduceStrecherBug.zip)

**Comment by rbtcollins** [comment]
Perhaps this bug should get closed?

**Comment by abhinav3295** [comment]
Thnaks!
