### ISSUE TITLE
SetupTest run remaining tests whether it fails or not

### ISSUE THREAD

**Issue by ugy** [stretchr/testify#649]
Hi !

I might not doing my tests the right way but it seemed normal to me that if the SetupTest function fails the rest of the suite test functions shouldn't be run.

I use SetupTest to initialize a variable used in all my tests of my suite, problem is I can have an error that assign nil to this variable, I used assert.NotNil in SetupTest to check for the error before running the remaining tests but they are run anyway and all segfault.

Maybe I should do my initialization outside my suite and run it after I check everyhting works but I prefer checking with you guys before :)

Thanks

**Comment by itzamna314** [comment]
Try using `require.NotNil()` to fail and abort the test.
`require` methods call [t.FailNow](https://godoc.org/testing#T.FailNow), which should abort the test.  `assert` methods call [t.Fail](https://godoc.org/testing#T.Fail), which explicitly marks the test as failed but continues execution.

**Comment by ugy** [comment]
Thank you ! I read about require and fixed my problems :)
