### ISSUE TITLE
require.Equal hangs

### ISSUE THREAD

**Issue by immesys** [stretchr/testify#657]
This code hangs for me:

```
func TestRequire(t *testing.T) {
	a := 3
	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		b := 0
		fmt.Printf("pre\n")
		require.Equal(t, b, a)
		fmt.Printf("post\n")
		cancel()
	}()
	<-ctx.Done()
}
```

The code prints "pre" but never prints "post". I have no idea why

**Comment by immesys** [comment]
More information: I am on f35b8ab0b5a2cef36673838d662e249dd9c94686 and it is worth noting that the following code works fine (no goroutine):

```
func TestRequire2(t *testing.T) {
	a := 3
	b := 0
	ctx, cancel := context.WithCancel(context.Background())
	func() {
		fmt.Printf("pre\n")
		require.Equal(t, b, a)
		fmt.Printf("post\n")
		cancel()
	}()
	<-ctx.Done()
}
```

so it definitely has something to do with being on a goroutine.

**Comment by immesys** [comment]
I tried bisecting but I can't find anywhere where this doesn't hang. I went back to 2016 commits and then stopped.

**Comment by immesys** [comment]
Is this just user error? I notice that the golang testing.T object requires that certain functions are called from the testing goroutine itself. Does that imply that require must also only be used on the testing goroutine?

**Comment by devdinu** [comment]
@immesys calling FailNow wouldn't stop other gorooutines. Its suggested to call in the actual goroutines `TestRequire` function.

But the main issue is the FailNow exits the goroutines so the cancel func never gets called, hence the main goroutine never ends waiting for `ctx.Done()`



```
FailNow marks the function as having failed and stops its execution
by calling runtime.Goexit (which then runs all deferred calls in the
current goroutine).
Execution will continue at the next test or benchmark.
FailNow must be called from the goroutine running the
test or benchmark function, not from other goroutines
created during the test. Calling FailNow does not stop
those other goroutines.
```

Adding cancel as defer func at the beginning of goroutine, fixes the issue, and terminates properly. 

```
	go func() {
		defer cancel()
		b := 0
		fmt.Printf("pre\n")
		require.Equal(t, b, a)
		fmt.Printf("post\n")
	}()
```

**Comment by immesys** [comment]
Yep, you are completely right. User error indeed!

**Comment by kdomanski** [comment]
Yes, `Require` calls `FailNow`, so you're not allowed to call if from a goroutine different than the main one.
