### ISSUE TITLE
Asserting equality on string vs. string pointer gives panic

### ISSUE THREAD

**Issue by HaraldNordgren** [stretchr/testify#662]
```go
func TestEqual(t *testing.T) {

	mockT := new(testing.T)

	a := "1"
	b := "1"

	if !Equal(mockT, &a, b) {
		t.Error("Error message that will not be reached because of the panic")
	}
}
```

**Comment by devdinu** [comment]
`panic: interface conversion: interface {} is *string, not string` The types are mismatched, so it panics, we can't compare and hence can't return a bool. what's the behaviour you expect ?

**Comment by HaraldNordgren** [comment]
I expect a regular error. Not a panic.

**Comment by HaraldNordgren** [comment]
Besides, most type mismatches do not lead to panics. It seems to be isolated to `string` vs. `*string`. So definitely an anomaly.

**Comment by Melaninneal** [comment]
its not just string and pointer missmatch it also fails on String pointer and string pointer as well! ]https://play.golang.org/p/nwMKxZeDCFr
