### ISSUE TITLE
Asserting equality for Dates

### ISSUE THREAD

**Issue by vrde** [stretchr/testify#666]
I'm a bit puzzled on how `assert.Equal` works with `time.Date`. In the following example I have two dates, one created calling `time.Date` directly, the other one parsed from a string. They represent exactly the same date, time, and timezone, but `assert.Equal` fails.

```go
import (
	"github.com/stretchr/testify/assert"
	"time"
)

func TestDate(t *testing.T) {
	a := time.Date(2018, time.September, 16, 12, 0, 0, 0, time.FixedZone("CEST", 2*60*60))
	b, _ := time.Parse(time.RFC3339, "2018-09-16T12:00:00+02:00")
	assert.True(t, a.Equal(b))
	assert.Equal(t, a, b)
}
```

```
--- FAIL: TestDate (0.00s)
    parser_test.go:38:
                Error Trace:    parser_test.go:38
                Error:          Not equal:
                                expected: time.Time{wall:0x0, ext:63672688800, loc:(*time.Location)(0xc000092480)}
                                actual  : time.Time{wall:0x0, ext:63672688800, loc:(*time.Location)(0x903a40)}

                                Diff:
                Test:           TestDate
FAIL
```

As far as I understand, `assert.Equal`compares the values of the pointers, not their addresses:
https://github.com/stretchr/testify/blob/f35b8ab0b5a2cef36673838d662e249dd9c94686/assert/assertions.go#L321-L327

Why is this test failing?

Edit: to give more context, I have a `struct` like the following:
```go
type Note struct {
        Date time.Time
        Tags []string
        Text string
}
```
and in my tests I check if an instance of `Note` contains the values I expect. I'd like to avoid testing attribute by attribute, like:
```go
assert.True(expected.Date.Equal(n))
assert.Equal(expected.Tags, n.Tags)
assert.Equal(expected.Text, n.Tags)
```

**Comment by brandonbodnar-wk** [comment]
The issue is that the `time.Date` and `time.Parse` calls, while evaluating to times that are equivenlent to each other for [func (Time) Equal](https://godoc.org/time#Time.Equal) purposes (which is location agnostic), are not actually equal referenced values, because they represent times in two different locations (same offset, but location/zone name differs). This is evident with a a few more assertions.

```golang
func TestDate(t *testing.T) {
	a := time.Date(2018, time.September, 16, 12, 0, 0, 0, time.FixedZone("CEST", 2*60*60))
	b, _ := time.Parse(time.RFC3339, "2018-09-16T12:00:00+02:00")

	assert.True(t, a.Equal(b))
	assert.Equal(t, a.Location().String(), b.Location().String())

	aZoneName, aZoneOffset := a.Zone()
	bZoneName, bZoneOffset := b.Zone()
	assert.Equal(t, aZoneName, bZoneName)
	assert.Equal(t, aZoneOffset, bZoneOffset)
	assert.Equal(t, a, b)
}
```
which gives failures

```bash
=== RUN   TestDate
--- FAIL: TestDate (0.00s)
	scratch_test.go:14: 
			Error Trace:	scratch_test.go:14
			Error:      	Not equal: 
			            	expected: "CEST"
			            	actual  : ""
			            	
			            	Diff:
			            	--- Expected
			            	+++ Actual
			            	@@ -1 +1 @@
			            	-CEST
			            	+
			Test:       	TestDate
	scratch_test.go:18: 
			Error Trace:	scratch_test.go:18
			Error:      	Not equal: 
			            	expected: "CEST"
			            	actual  : ""
			            	
			            	Diff:
			            	--- Expected
			            	+++ Actual
			            	@@ -1 +1 @@
			            	-CEST
			            	+
			Test:       	TestDate
	scratch_test.go:20: 
			Error Trace:	scratch_test.go:20
			Error:      	Not equal: 
			            	expected: time.Time{wall:0x0, ext:63672688800, loc:(*time.Location)(0xc4200c42a0)}
			            	actual  : time.Time{wall:0x0, ext:63672688800, loc:(*time.Location)(0xc4200c4360)}
			            	
			            	Diff:
			            	--- Expected
			            	+++ Actual
			            	@@ -1,2 +1,2 @@
			            	-(time.Time) 2018-09-16 12:00:00 +0200 CEST
			            	+(time.Time) 2018-09-16 12:00:00 +0200 +0200
			            	 
			Test:       	TestDate
FAIL
```

To avoid having to do attribute by attribute checks, or having to use the [Condition function on assert](https://godoc.org/github.com/stretchr/testify/assert#Condition), I assume that at least one of your test values is being created as a test expectation. In that case, I would alter the expectation to make sure it is creating a `time.Location` for Note's Date field to have the same name value as your result from the unit under test.

Using the initial test code as an example, if your test expectation uses the `time.Date` function and the unit under test uses `time.Parse`, you can do

```golang
func TestDateSameLocationChangeDate(t *testing.T) {
	// Use empty string for zone name as that is what is parsed out of RFC3339
	a := time.Date(2018, time.September, 16, 12, 0, 0, 0, time.FixedZone("", 2*60*60))
	b, _ := time.Parse(time.RFC3339, "2018-09-16T12:00:00+02:00")
	assert.True(t, a.Equal(b))
	assert.Equal(t, a, b)
}
```

If your test expectation uses the `time.Parse` function and the unit under test uses `time.Date`, you can do

```golang
func TestDateSameLocationChangeParse(t *testing.T) {
	a := time.Date(2018, time.September, 16, 12, 0, 0, 0, time.FixedZone("CEST", 2*60*60))
	// Use the the alternative ParseInLocation and use the same FixedZone values as in time.Date
	b, _ := time.ParseInLocation(time.RFC3339, "2018-09-16T12:00:00+02:00", time.FixedZone("CEST", 2*60*60))
	assert.True(t, a.Equal(b))
	assert.Equal(t, a, b)
}
```

**Comment by vrde** [comment]
@brandonbodnar-wk thanks a lot for your answer, I finally understand what's happening here :)

**Comment by jconti** [comment]
The [example of using Equals](https://cs.opensource.google/go/go/+/go1.23.2:src/time/zoneinfo.go;l=23) on `time.Time` with different time zones I think indicates that at this point, `assert.Equal` should call `time.Equal` which properly handles time zones that are different but that indicate the same time. This is the useful behavior for time values that use time zones.

**Comment by brackendawson** [comment]
Changing `Equal` to call `time.Time.Equal` will break tests like [this](https://github.com/arran4/golang-ical/blob/4b576397768f312e43b566d737aaf5d62fd5a19c/calendar_test.go#L114) which assert the location. We absolutely will not make this change.

What you are asking for is a lesser assertion which compares the instant which `time.Time` values represent. We already have this assertion, use `WithinDuration` with a duration of `0`.

**Comment by jconti** [comment]
The difficulty is that two data structures with time fields are not `Equal`, even though `t1.Equal(t2)` is true. This rationale would make sense if it wasn't that `time.Equal()` is true.

**Comment by brackendawson** [comment]
`time.Time.Equal` being true does not mean the two time values are equal.

**Comment by jconti** [comment]
😯 The least surprise, and therefore the highest utility to the community is to have a test's notion of `Equal()` match the standard library's of `Equal()` (including using the same code, `Equal()` on the type when possible). The time library has chosen the definition of equal to mean "the same instant in time, even if represented with different data". That has a very high utility for doing time/date calculations, before, after, during, etc. To use a different notion in tests is unexpected, counterintuitive and requires different test code for the same functionality in the system under test.

**Comment by jconti** [comment]
> Changing `Equal` to call `time.Time.Equal` will break tests like [this](https://github.com/arran4/golang-ical/blob/4b576397768f312e43b566d737aaf5d62fd5a19c/calendar_test.go#L114) which assert the location. We absolutely will not make this change.

Actually this would not need to change, as it uses a custom assertion.

> What you are asking for is a lesser assertion which compares the instant which `time.Time` values represent. We already have this assertion, use `WithinDuration` with a duration of `0`.

I am advocating for consistency, which is neither "lesser" or more. Just more likely to be of value as a result of being self consistent within the ecosystem.

**Comment by brackendawson** [comment]
> Actually this would not need to change, as it uses a custom assertion.

You're right, that's a fair point. But it is still a breaking change. It will not be changed.
