### ISSUE TITLE
Add support for vgo / modules

### ISSUE THREAD

**Issue by georgelesica-wf** [stretchr/testify#667]
Now that vgo is a thing we should at least plan to support consumption in that manner.

  * https://github.com/golang/go/wiki/vgo
  * https://github.com/golang/go/wiki/Modules

**Comment by devdinu** [comment]
I could pick this up.

**Comment by georgelesica-wf** [comment]
That would be great, thanks!

**Comment by bodnarbm** [comment]
I believe that @leighmcculloch has a PR (#607) that they have been updating to bring in some vgo support.

**Comment by leighmcculloch** [comment]
Yup #607 is it, just waiting for #657 to be merged first. Could someone merge it?

**Comment by georgelesica-wf** [comment]
This has been resolved in https://github.com/stretchr/testify/pull/607.
