### ISSUE TITLE
Post request with body equal comparation bug by reflect.DeepEqual

### ISSUE THREAD

**Issue by everdance** [stretchr/testify#671]
https://play.golang.org/p/k6oD1g_lGeQ
```
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"reflect"
)

func main() {
	req1 := http.Request{}
	req2 := http.Request{}
	fmt.Printf("Empty request equal:%v\n", reflect.DeepEqual(&req1, &req2))
	bodyPayload := []string{"1", "2"}
	p1, _ := json.Marshal(bodyPayload)
	p2, _ := json.Marshal(bodyPayload)
	req3, _ := http.NewRequest("POST", "", bytes.NewBuffer(p1))
	req4, _ := http.NewRequest("POST", "", bytes.NewBuffer(p2))
	fmt.Printf("Body request equal:%v\n", reflect.DeepEqual(req3, req4))
}
```
==>
```
Empty request equal:true
Body request equal:false
```

**Comment by everdance** [comment]
https://github.com/golang/go/pull/27758

**Comment by brandonbodnar-wk** [comment]
Can you update the issue with more information related to what problem you are seeing in testify or your use of testify related to reflect.DeepEqual not handling function equality. Based on your linked PR, I assume there is something you are trying to accomplish with mocks that relates to this.

As was noted in the linked golang/go#27758 issue, function equality presents very tricky edge cases. It seems that function equality is explicitly not dealt with in this library. [For example, see assert.Equal](https://godoc.org/github.com/stretchr/testify/assert#Equal)

**Comment by everdance** [comment]
yup, we hit this edge case when we try to do some mock expectations on `http.Request` parameter, like
```
...
req3, _ := http.NewRequest("POST", "", bytes.NewBuffer(p1))
myMock.On("SomeMethod",  req3).Return(nil).Once()
...
```
would it make sense to get around this in mock by also checking the string diff as in this PR:
https://github.com/stretchr/testify/pull/672/files
if assert.ObjectsAreEqual(expected, Anything) || assert.ObjectsAreEqual(actual, Anything) || assert.ObjectsAreEqual(actual, expected) || `diff(expected, actual) == ""` {

So the mock lib would be saved on comparing http.Request parameters.
