### ISSUE TITLE
How to use AnythingOfType?

### ISSUE THREAD

**Issue by hgfischer** [stretchr/testify#68]
I'm trying to use testify/mock but I'm having the following issue and I'm not even sure If I'm using it right. 

I've put parts of the code I'm using bellow and the test output:

```
func TestMessageSender(t *testing.T) {
        connMock := new(RedisConnMock)
        connMock.On("Close").Return(nil).Once()
        connMock.On("Do", "PSTEX",
                mock.AnythingOfType("string"),
                mock.AnythingOfType("int64"),
                mock.AnythingOfType("string")).
                Return("OK", nil).
                Once()
```

...

```
mock: Unexpected Method Call
-----------------------------

Do(string,string,int64,string)
                0: PSETEX
                1: a1b427e4-f32a-34de-8165-d946c774981d
                2: 259200000
                3: {"uuid":"a1b427e4-f32a-34de-8165-d946c774981d"...}

The closest call I have is: 

Do(string,mock.AnythingOfTypeArgument,mock.AnythingOfTypeArgument,mock.AnythingOfTypeArgument)
                0: PSTEX
                1: string
                2: int64
                3: string
```

Can you please help me?

**Comment by wolfgangmeyers** [comment]
I'm having similar troubles. I tried using mock.AnythingOfType, but the function argument in this case is an interface and I get an error when a concrete type is passed in.

Function signature looks like:
`ListWebUsers(context.Context) ([]*WebUser, error)`

Mock looks like:
```
// ListWebUsers provides a mock function with given fields: _a0
func (_m *WebUserService) ListWebUsers(_a0 context.Context) ([]*inventory.WebUser, error) {
	ret := _m.Called(_a0)

	var r0 []*inventory.WebUser
	if rf, ok := ret.Get(0).(func(context.Context) []*inventory.WebUser); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*inventory.WebUser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
```
Test:
`s.svc.On("ListWebUsers", mock.AnythingOfType("context.Context").Return([]*inventory.WebUser{})`

```
mock: Unexpected Method Call
-----------------------------

ListWebUsers(*context.valueCtx)
		0: &context.valueCtx{Context:(*context.valueCtx)(0xc82036ac90), key:(*string)(0xa62a40), val:(*internal.context)(0xc82027bc80)}

The closest call I have is:

ListWebUsers(mock.AnythingOfTypeArgument)
		0: "context.Context"
```

Tried using mock.Anything, get a completely different error.

Test:
`s.svc.On("ListWebUsers", mock.Anything).Return([]*inventory.WebUser{})`

```
panic: assert: arguments: Cannot call Get(1) because there are 1 argument(s). [recovered]
	panic: assert: arguments: Cannot call Get(1) because there are 1 argument(s).
```

**Comment by wolfgangmeyers** [comment]
This seems to be working for me - I don't know how much work it would be, but it would be nice if mock.AnythingOfType(...) worked for interfaces.

**Comment by ernesto-jimenez** [comment]
@wolfgangmeyers, I'll have to review the code to see wether that would be possible.

In the meantime, you can probably work something out with `MatchedBy`

**Comment by tobiisan** [comment]
I know this is already closed and everything, but I thought I'd point this out if anyone ever looks at this again and is curious.
I believe the original problem is just a typo in parameter 1.

PSTEX - Mock is wanting this
PSETEX - This got passed in
