### ISSUE TITLE
Assert value order comparison.

### ISSUE THREAD

**Issue by alexpantyukhin** [stretchr/testify#710]
I have created a test collection comparisons there https://github.com/alexpantyukhin/assertord . I believe many of them are redundant but it's just for demo. Any thoughts could it be good idea to integrate that functionality into the `testify`? Also I guess it would be good to have `assert.IsGreater`, `assert.IsGreaterOrEqual`, `assert.IsLess`, `assert.IsLessOrEqual` in the `testify`.

**Comment by alexpantyukhin** [comment]
@georgelesica-wf I have added values comparison in this https://github.com/stretchr/testify/pull/713 PR . Could you please review?

**Comment by dmirogin** [comment]
This issue can be closed because of https://github.com/stretchr/testify/pull/713
