### ISSUE TITLE
How Can I Test with fuction that retunrs multiple value

### ISSUE THREAD

**Issue by hero0926** [stretchr/testify#719]
Hello, I do want to make a unit test like

`assert.Panicsf(t, somethingReturnsMultipleValue(arg, arg2), "It sholud occur a panic")`

I do want to occur a panic with func which returns two more values. but I can't put a func which returns multiple values.

How can i test this kind of functions with testify?

**Comment by Saluev** [comment]
Hi @hero0926,

You are using `assert.Panicsf` the wrong way. Refer to docs. The correct code would be
```go
assert.Panicsf(t, func() { somethingReturnsMultipleValue(arg, arg2) }, "It sholud occur a panic")
```

**Comment by hero0926** [comment]
@Saluev I was idiot a f
