### ISSUE TITLE
Remove unmaintained dependency go-difflib

### ISSUE THREAD

**Issue by Crevil** [stretchr/testify#736]
The package `github.com/pmezard/go-difflib` is as of this commit no longer maintained: https://github.com/pmezard/go-difflib/commit/1ef1646f464bff6853dfa4c32750886762dc023a

Maybe we could move the used functionality into this repo and stop depending on the `difflib` package all together?

The functions used are [`difflib.GetUnifiedDiffString()`](https://github.com/pmezard/go-difflib/blob/5d4384ee4fb2527b0a1256a821ebfc92f91efefc/difflib/difflib.go#L635-L639) and [`difflib.SplitLines()`](https://github.com/pmezard/go-difflib/blob/5d4384ee4fb2527b0a1256a821ebfc92f91efefc/difflib/difflib.go#L768-L772).

**Comment by kkaushy** [comment]
Is there any update on this.

**Comment by dolmen** [comment]
Who will maintain that imported code?

What are the issues in difflib code that need fixes?

So far, as a maintainer, I don't see any advantages compared to the status quo.

**Comment by dolmen** [comment]
Duplicate of #1187.
