### ISSUE TITLE
Introduce negated functions to FileExists and DirExists assertions

### ISSUE THREAD

**Issue by bmuschko** [stretchr/testify#740]
The `FileExists` and `DirExists` assertions help a lot. Sometimes you want to assert the opposite:

- This file should not exist.
- This directory should not exist.

I'd love to see functions like `FileNotExists` and `DirNotExists` as you otherwise have to build them yourself. Would you accept a pull request for such functionality? Happy to create one.

**Comment by GiampaoloFalqui** [comment]
Yes please!

**Comment by bmuschko** [comment]
Looks like the PRs are piling up for this project. Before putting in the work, I'd like to ask one of the maintainers if there's a chance that it actually does get merged. Feedback welcome!

**Comment by georgelesica-wf** [comment]
@bmuschko There is a huge backlog, unfortunately, left over from a period of time during which the project wasn't really being actively maintained. This makes it a little difficult to keep track of what's active and relevant and what's not. I have attempted to close old or abandoned PRs and issues but I only have so much time. At this point I would describe the project as "lightly maintained". It is largely "finished", but we merge PRs with a bias toward bug fixes and non-breaking, orthogonal features. It helps if you ping me or reach out in the Gophers Slack.

**Comment by boyan-soubachov** [comment]
Happy to take this one on.

**Comment by glesica** [comment]
That would be awesome, @boyan-soubachov, thanks!
