### ISSUE TITLE
mock.On should be able to return input args

### ISSUE THREAD

**Issue by Naatan** [stretchr/testify#748]
I'd like to be able to use the input arguments that were sent to a mocked function in the response. Sadly this does not appear to be possible because .On() takes a static response. It would be good if there was a version of `.On()` that uses a callback response.

**Comment by HaywardMorihara** [comment]
I'm not sure what exactly you need, but I found that this worked for me when I needed something that sounds similar to what you need:

```
import (
	"testing"

	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
)

type SomeInterface interface {
	SomeFunc(x int) int
}

type SomeMockImpl struct {
	mock.Mock
}

func (_m *SomeMockImpl) SomeFunc(x int) int {
	ret := _m.Called(x)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(x)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

func Test(t *testing.T) {
	mockStruct := &SomeMockImpl{}

	mockStruct.On("SomeFunc",
		mock.Anything).Return(func(x int) int{
			return x + 1
	})

	require.Equal(t, 2, mockStruct.SomeFunc(1))
	require.Equal(t, 3, mockStruct.SomeFunc(2))
	require.Equal(t, 101, mockStruct.SomeFunc(100))
}
```

**Comment by Naatan** [comment]
I did not realize you could pass a function like that, thank you @HaywardMorihara !
