### ISSUE TITLE
PanicsWithValue() should use equality, not ==

### ISSUE THREAD

**Issue by Emptyfruit** [stretchr/testify#749]
Panic with Error instead of string is a valid practice. Asserting the value of a panic using `!=` is not ok, because it results in a funny, but annoying test fails.
 
Example of a fail
```
=== RUN   Test
--- FAIL: Test (0.00s)
    test.go:27: 
        	Error Trace:	test.go:27
        	Error:      	func (assert.PanicTestFunc)(0x128adb0) should panic with value:	&errors.errorString{s:"message"}
        	            		Panic value:	&errors.errorString{s:"message"}
        	Test:       	Test
FAIL
```

The causing code (assertions.go:952):
```
if panicValue != expected {
    return Fail(t, fmt.Sprintf("func %#v should panic with value:\t%#v\n\tPanic value:\t%#v", f, expected, panicValue), msgAndArgs...)
}
```

**Comment by Emptyfruit** [comment]
I think build-in error interface is common enough to have a special treatment in terms of panics in this library. Otherwise, some PanicsWithValue.. method with a callback function on recovered message could also work.

**Comment by leighmcculloch** [comment]
Agreed, it's very difficult to find compatible use cases for the `PanicWithValue` function because most of the time reconstructing the exact error object is too difficult in the test, especially now that wrapped/nested error objects are common place. Most of the time testing the error objects string is sufficient.

I think an additional function like `assert.PanicWithAssertionFunc` so we can then pass in `assert.Equal` or our own custom `ValueAssertionFunc` function would make sense.

@georgelesica-wf Would you welcome a PR that contributes this?

**Comment by georgelesica-wf** [comment]
Yeah, that sounds reasonable, although it would be difficult to generate a truly useful error message when the failure is the result of an arbitrary callback.

**Comment by leighmcculloch** [comment]
@georgelesica-wf I agree, it'd be difficult to make a useful error message. I opened #839 that instead adds `PanicsWithError` that does an error comparison in the same way that `EqualError` does. I think this addresses most of the lacking I've experienced and retains useful error messages.

**Comment by ilius** [comment]
I don't think the type of panic value ever matters.
We just need to check the message (string) in tests.
Just like `EqualError`.

`PanicsWithError` right now is not usable for panics that are raised by Go itself (like invalid memory address or nil pointer dereference)

For keeping compatibility, I would suggest a `PanicsWithMessage` that takes `actual string` as argument.

**Comment by leighmcculloch** [comment]
@ilius See `PanicsWithError` added in #839. It adds a check against the error's string in the way I think you are describing.

**Comment by ilius** [comment]
Thanks.
I would appreciate if you release a tag so that people using `go mod` can use the new changes.
