### ISSUE TITLE
go mod inconsistencies

### ISSUE THREAD

**Issue by AdamSLevy** [stretchr/testify#757]
When updating this package using `go get -u github.com/stretchr/testify` the following is added to the `go.mod` file:

```
require (
        github.com/stretchr/objx v0.2.0 // indirect
        github.com/stretchr/testify v1.3.0
)
```

The indirect dependency is surprising because the go.mod file declared by testify uses objx v0.1.0

More odd is that after running `go mod tidy` I get the following:

```
require (
        github.com/davecgh/go-spew v1.1.1 // indirect
        github.com/stretchr/testify v1.3.0
)
```

I would like to see this repo's go.mod file to be updated using `go mod tidy` so that this indirect dependency won't clutter up other go.mod files that import testify. This will also require a minor version bump.

**Comment by AeroHil** [comment]
I am also inquiring about this. It's been a year, has anyone got a work around for this?

**Comment by boyan-soubachov** [comment]
If I upgrade the dependencies, `go-spew` moves from 1.1.0 to 1.1.1, `objx` moves from `0.1.0` to `0.2.0` and `gopkg.in/yaml.v3` moves from `v3.0.0-20200313102051-9f266ea9e77c` to `v3.0.0-20200506231410-2ff61e1afc86`.

Are there any explicit reasons you would like us to upgrade the dependency versions? We prefer to stick to known versions until/unless an issue has been discovered :) 

I'd be happy to bump the versions up if there are any documented issues causing problems with the repo or other packages depending on us.

**Comment by dolmen** [comment]
Old issue no longer relevant.
