### ISSUE TITLE
`assert.Same` is valuable and should be released

### ISSUE THREAD

**Issue by jeffatgametime** [stretchr/testify#778]
We love this package! But we don't love requiring constraining our dependencies to branches. Just wondering when you'll be releasing the commit below which contains the `assert.Same` assertion?

https://github.com/stretchr/testify/commit/21cb1c2932a2d04c6792d5ad106243c6e36a3a7d

Keep up the good work.

**Comment by halleknast** [comment]
+1 Should also close #597.

**Comment by hsyed** [comment]
Please release this.

**Comment by mvdkleijn** [comment]
Note.. this issue can be close as the feature was released in 1.4.0

**Comment by mvdkleijn** [comment]
Closing issue since it was handled
