### ISSUE TITLE
mock: AssertExpectations - disable log output for "pass"

### ISSUE THREAD

**Issue by AntonStoeckl** [stretchr/testify#782]
Currently there is no way to silence AssertExpectations if all expectations pass.
I find this output "PASS: ....." quite annoying and superfluous.
I assume most people are only interested in failures but don't need output of every passing assertion. It also seems inconsistent with other Assert... methods, which don't report success, only failure.

If this would be my userland code, I'd simply remove the log output for "PASS", but in a lib that's not good style.

I currently don't see a clean, backwards compatible way to optionally disable the logging for success cases. Maybe a new method like AssertFailedExpectations()?

**Comment by jcollum** [comment]
+1 

there's a form for input on Testify v2 but really all I wanted to do was say "stop putting out so many lines of code for a passing test!" instead of filling out a questionnaire (with a lot of mandatory fields that I'm not interested in).
