### ISSUE TITLE
Allow passing argument check function to mock.On()

### ISSUE THREAD

**Issue by dergus** [stretchr/testify#798]
There are times when you can't know exactly what will be values of some struct fields when mocked function gets called. Current solution is to use mock.AnythingOfType() but it makes tests weaker.
I propose to allow passing function to mock.On() method which then would receive and check arguments of called function. 
Something like that:
```Go
type Model struct {
    ID int
    UpdatedAt time.Time
}

type Repo struct {}
func (r *Repo) Update(m *Model) {
   // save updated model in persistent store
}

func TestUpdate(t *testing.T) {
    mockRepo := &mocks.Repo{}
    mockRepo.On("Update", func(arguments ...interface{}) {
    m := arguments[0].(*Model)
    assert.WithinDuration(t, time.Now(), m.UpdateAd, 1 * time.Second)
 })
}
```

**Comment by dthuering** [comment]
How about using `MacthedBy`? 
https://pkg.go.dev/github.com/stretchr/testify@v1.7.0/mock#MatchedBy

**Comment by kirill-lokhmatov** [comment]
> How about using `MacthedBy`? https://pkg.go.dev/github.com/stretchr/testify@v1.7.0/mock#MatchedBy

looks like it doest work with functions with several arguments or i am missing something
