### ISSUE TITLE
Setting expectation that a method is not called

### ISSUE THREAD

**Issue by olvlvl** [stretchr/testify#800]
Hi,

Is there a way to set an expectation that a method has not been called, that I can assert using `AssertExpectations`? This is how I would do it in PHP:

```php
$m->doSomething(123, Argument::any())->shouldNotBeCalled();
```

Currently, `AssertExceptations` only checks for expected calls, could we extend it to check for unexpected calls too? Since `On` assumes expected calls, maybe we could have a `Never` counterpart?

```golang
m.Never("doSomething", 123, mock.Anything)
// ...
m.AssertExpectations(t)
```

**Comment by olvlvl** [comment]
Actually, the PHP equivalent returns `null` for unspecified calls, whereas Testify fails the test, so all is good!

```
panic: 
assert: mock: I don't know what to return because the method call was unexpected.
	Either do Mock.On("Get").Return(...) first, or remove the Get() call.
	This method was unexpected:
		Get(*context.emptyCtx,hf.Country,string,hf.Week)
		0: (*context.emptyCtx)(0xc0000a8000)
		1: "US"
		2: "classic-box"
		3: "2022-W01"
	at: [get_test.go:24 get_test.go:43] [recovered]
	panic: 
```

**Comment by devdinu** [comment]
FYI, To verify a method is not called

```
func (m *Mock) AssertNotCalled(t TestingT, methodName string, arguments ...interface{}) bool
```

**Comment by olvlvl** [comment]
Thanks @devdinu, I noticed this one but I wanted to set an expectation that I could verify with `AssertExpectations`. Turns out I don't need to because contrary to PHP/Propecy, Testify will complain about unexpected calls by default, and that's what I want.
