### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by falzm** [stretchr/testify#801]
Hi,

It's been quite a long time since the [last stable release](https://github.com/stretchr/testify/releases/tag/v1.3.0) (> 6 months), and there are some very useful assertions that have been merged into master – I for one am particularly interested in comparisons, as implemented in 3f658bd5ac42cc0b5de5b427e95a480d5726ea76. Could you please consider releasing a new tagged version? It's really frustrating to waste time trying to figure out why some functions documented in the Godoc API are not found by the compiler when you use Go modules that fetch the latest tagged version and not master...

Thank you in advance!

**Comment by georgelesica-wf** [comment]
Good call. I've been pretty busy but I'll do my best to get a release out in the next couple days.

**Comment by AlekSi** [comment]
That one probably can be closed

**Comment by falzm** [comment]
Yes, thanks @georgelesica-wf!
