### ISSUE TITLE
assert.Eventually with low ticks cause panic: send on closed channel

### ISSUE THREAD

**Issue by pgarneau** [stretchr/testify#805]
# Setup
If you put an:
`assert.Eventually(t, func() bool { return true }, time.Millisecond, 50 * time.Microsecond)` inside your test, you will get flaky results and more often then not, you will get a panic:
`panic: send on closed channel`

# Workaround
Increasing the tick to around `100 * time.Microsecond` removes the flakyness

# Solution
Add a waitgroup potentially so that [this channel close](https://github.com/stretchr/testify/blob/221dbe5ed46703ee255b1da0dec05086f5035f62/assert/assertions.go#L1483) waits for the gofunc writing to the channel completes.

**Comment by zut** [comment]
Same for me. To reproduce:
> `go version`
```
go version go1.13 darwin/amd64
```

> `go.mod`
```
module reqtest

go 1.13

require github.com/stretchr/testify v1.4.0
```

> `req_test.go`
```
package main

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func Test_Eventually(t *testing.T) {
	require.Eventually(t, func() bool { return true }, time.Millisecond, time.Microsecond)
}
```

> `go test req_test.go`
```
--- FAIL: Test_Eventually (0.00s)
panic: send on closed channel
````
