### ISSUE TITLE
How to write benchmarks using testify / suite ?

### ISSUE THREAD

**Issue by msonawane** [stretchr/testify#811]

**Comment by mohanraj-r** [comment]
You should be able to use the `*testing.B` directly with testify. 

```go
func BenchmarkFoo(b *testing.B) {
   require.NoError(b, fmt.Errorf("test error"))
}
```

Testify uses [TestingT](https://www.godoc.org/github.com/stretchr/testify/assert#TestingT) interface which is satisfied by both `testing.B` and `testing.T`

**Comment by mrsndmn** [comment]
But there is no way to run benchmarks with **testify/suite**.
[suite.Run](https://github.com/stretchr/testify/blob/master/suite/suite.go#L83) accepts only `t *testing.T`

**Comment by boyan-soubachov** [comment]
Suite now has an extra `HandleStats()` function. If you have any ideas & code to make it compatible with `testing.B`, I'd be very happy to help you get it merged :)

**Comment by updogliu** [comment]
Do you think we can change
`func Run(t *testing.T, suite TestingSuite)` to
`func Run(t testing.TB, suite TestingSuite)` ?

**Comment by boyan-soubachov** [comment]
We've had that change before and it breaks backwards compatibility. We'd be happy to consider it but it would be implemented in testify v2

**Comment by milosgajdos** [comment]
Doesn https://github.com/stretchr/testify/pull/495 cover this use case?

**Comment by carlcarl** [comment]
Here is an workaround if anyone who has the same problem:
```
type Suite struct {
    suite.Suite
}

BenchmarkExample(b *testing.B) {
    s := new(Suite)
    s.SetT(&testing.T{})
    s.SetupSuite()
    b.ResetTimer()
    for i := 0; i < b.N; i++ {
        s.SetupTest()
        b.StartTimer()
        // Put the function you want to benchmark here.
        b.StopTimer()
        s.TearDownTest()
    }
    s.TearDownSuite()
}
```

**Comment by rmscoal** [comment]
Why does mine shows a `s.SetupSuite undefined`? Any suggestion?

**Comment by rmscoal** [comment]
Ah nvm, it's an interface contract.. Okay thanks

**Comment by pplmx** [comment]
Any progress?

**Comment by msf** [comment]
I'm doing benchmarks w/ Suite and I suggest a small modification to @carlcarl suggestion:
```
func BenchmarkExample(b *testing.B) {
    s := new(Suite)
    s.SetT(&testing.T{})
    s.SetupSuite()
    s.SetupTest()
    // do any additional prep-work for the benchmark here
    b.StartTimer()
    b.ResetTimer()
    for i := 0; i < b.N; i++ {
        // Put the function you want to benchmark here.
    }
    b.StopTimer()
    s.TearDownTest()
    s.TearDownSuite()
}
```
This serves two purposes:
- clearly isolate prepwork from the benchmark
- more conventionally use the benchmark traditional for loop ` for i := 0; i < b.N; i++ {`, tracking its behavior as i progresses to N (can make a diff for mem allocations..etc..)
