### ISSUE TITLE
Feature Request: file path in stack traces

### ISSUE THREAD

**Issue by ravishi** [stretchr/testify#821]
Currently, when a test fails, `testify` will gently print a stack trace of sorts.

That is very useful, one could say even essential, while debugging and or refactoring.

But it also has some limitations. Namely, it doesn't print the complete path to the file, only it's filename. That works very well when all your test code is contained in a single file. But what happens when you use helper functions? And what about when you have files with the same name in different packages? It get's a little confusing.

So I would like to request that we offer a way to print the whole path to the files in that stack trace. Maybe we could only print when tests are called with `-v`?

**Comment by muir** [comment]
This has been the behavior for some time.

**Comment by ravishi** [comment]
Alright, I can attest it is the current behavior. Closing this FR as outdated. Thank you!
