### ISSUE TITLE
Adding HTTPStatusCodeEqual to assert if status code equals to expected value

### ISSUE THREAD

**Issue by shihanng** [stretchr/testify#824]
Currently we have [`HTTPError`](https://godoc.org/github.com/stretchr/testify/assert#HTTPError) which check if the http response contains status code of 400 and above. I am wordering if we can add another function to check for specific status code like something below:

```go
func HTTPStatusCodeEqual(t TestingT, handler http.HandlerFunc, method, url string, values url.Values, statusCode int, msgAndArgs ...interface{}) bool
```

I can send a PR if you think this is something that can be included in the package. Thank you.

**Comment by KrzysztofMadejski** [comment]
@shihanng give this lib a try: https://gitlab.com/gotests/handlertest
