### ISSUE TITLE
Using error in Contains fails with confusing message

### ISSUE THREAD

**Issue by henrahmagix** [stretchr/testify#828]
https://play.golang.org/p/u7Dfo4UnxZ0
```go
assert.Contains(t, "error string", errors.New("error"))
```
```
Error Trace:	prog.go:25
Error:      	"error string" does not contain "error"
Test:       	TestCaseA
```

Whereas this is what's needed to pass:
```diff
-assert.Contains(t, "error string", errors.New("error"))
+assert.Contains(t, "error string", errors.New("error").Error())
```

I would prefer if the failure message explained that it was an error type, otherwise it looks like a string does not contain another string: I've fallen foul to this in the past, and just spent 5-10mins again not realising that I needed to pass a `string` type as the 3rd argument.

It would be really nice to have the type printed here when the value isn't a `Stringer` =)

**Comment by xordspar0** [comment]
I think the current behavior is correct, but I agree that the error message is misleading.

Here's the source of the problem:
https://github.com/stretchr/testify/blob/6be346c1f15898af82c7c86dbad99cc9d7fee6f2/assert/assertions.go#L765-L767

One solution might be to change the `%s` to a `%#v` like this:

```diff
-return Fail(t, fmt.Sprintf("\"%s\" does not contain \"%s\"", s, contains), msgAndArgs...)
+return Fail(t, fmt.Sprintf("%#v does not contain %#v", s, contains), msgAndArgs...)
```

But that might be overly verbose:

```
--- FAIL: TestCaseA (0.00s)
    test.go:25:
                Error Trace:    test.go:25
                Error:          "test" does not contain &errors.errorString{s:"test"}
                Test:           TestCaseA
```

Or maybe it's just the right amount of verbosity. I'm not sure.

**Comment by henrahmagix** [comment]
@xordspar0 I think `%#v` is the _perfect_ amount of verbosity for a Go error message =)

**Comment by boyan-soubachov** [comment]
The docstring of `xxx.Contains()` says:
> Contains asserts that the specified string, list(array, slice...) or map contains the specified substring or element

In its current form, the behaviour matches what is described in the docstring. If we feel the package would serve its stated purpose better by having a more 'intelligent' `Contains()`, I am all for it. It would most likely be a breaking change however and I would appreciate more input from the wider community.

**Comment by boyan-soubachov** [comment]
If we do keep the change to just the error message, I agree it could be better. Though I am also not too sure of the verbosity as @xordspar0 mentioned. 

I think it would make sense to evaluate the different options & ways this error message could be more verbose without being overtly so. Thoughts/suggestions?

**Comment by henrahmagix** [comment]
@boyan-soubachov I think the behaviour is fine =) If it were made more "intelligent" by dealing with `error` contained in `string`, that will perhaps open it up to having to also deal with other cases in the future.

Although, saying that, it's a bit weird how this case ends up working: it resolves to `strings.Contains("error test", "<*errors.errorString Value>")` – see https://play.golang.org/p/JHiQ8KfwZ1Q

So maybe this is a bug after all?

I like that the verbosity of `%#v` is the simplest fix for now =)

**Comment by boyan-soubachov** [comment]
If you're willing to write the PR, I'd be happy to review and help you get it merged

**Comment by xordspar0** [comment]
Ok, let's start with https://github.com/stretchr/testify/pull/913 and see how far that gets us.

**Comment by xordspar0** [comment]
@henrahmagix, nice work with the clear, minimal example code and play.golang.org links. That made this issue easy to understand and experiment with.

**Comment by henrahmagix** [comment]
Thank you both @xordspar0 and @boyan-soubachov! Goodnight from the British Isles 💎
