### ISSUE TITLE
Expect ... toEqual ... Syntax?

### ISSUE THREAD

**Issue by JimTheMan** [stretchr/testify#831]
Hi, is it possible with this library to add a syntax for this:
```
expect [givenThing] toEqual [expectedThing]
```

or is there any other go package that provides this?

Thanks!

**Comment by rliddler** [comment]
[Gomega](https://onsi.github.io/gomega/#making-assertions) allows you to make assertions in that sort of manner. It's a bit more rspec like in it's behaviour.

**Comment by boyan-soubachov** [comment]
I'm afraid that would be a huge change that would be non-compatible with the current version.

If a large majority of the community feels that this would be better, then we'd be happy to help out where we can. Unfortunately for now, we haven't seen many of these requests.

I would be happy to discuss this further if you wish.
