### ISSUE TITLE
Go 1.13 and github.com/stretchr/testify/suite issue

### ISSUE THREAD

**Issue by quynhdang-vt** [stretchr/testify#836]
Hello,
My test suite was running fine with 1.11 -- then we decided to go up to 1.13.  Now running the tests keep failing with this

```
go test -timeout 15m -v
flag provided but not defined: -test.timeout
Usage of /tmp/go-build551216735/b001/tests.test:
  -alsologtostderr
    	log to standard error as well as files
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory
  -logtostderr
    	log to standard error instead of files
  -stderrthreshold value
    	logs at or above this threshold go to stderr
  -testify.m string
    	regular expression to select tests of the testify suite to run
  -v value
    	log level for V logs
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
exit status 2
FAIL	github.com/veritone/realtime/modules/engines/tests	0.037s
make: *** [test-playback] Error 1
```

According to this link: https://github.com/microsoft/vscode-go/issues/2734 there may be some conflict in testing.Init and the test suite?

I'm trying to figure out what would be the solution -- but just wondering if this is a known issue here.

Thanks in advance.

**Comment by boyan-soubachov** [comment]
It looks like an issue with the way `go test` is being called rather than this package.

**Comment by boyan-soubachov** [comment]
@quynhdang-vt , please let me know if this is still an issue and I'd be happy to reopen this.
