### ISSUE TITLE
Much Simpler Testify

### ISSUE THREAD

**Issue by tylerb** [stretchr/testify#84]
Greetings, everyone!

I have been thinking for a while about creating a much simpler version of testify.

My goals would be to:

* Make the API much smaller
* Make the output more compact - probably a single line like the standard testing framework
* ~~Use a `require` approach for all functions - abort if a test fails~~
* Maintain the `assert` approach, with a `require` method that allows for a one-off require and fail. This will avoid deep nesting of if statements.
  * `is.Equal(a,b).Require()` or similar  
* Must manually output failure messages in the style of the testing framework, then call t.FailNow()
  * This will allow us to avoid using `\r` and `\b` which is incompatible with various output consoles.
  * Basically we need to duplicate the [decorate](http://golang.org/src/pkg/testing/testing.go#L192) 
function to generate our own output.
* Remain completely dependent on the Go testing framework - testify should be as easy (or easier) to use as it is now... no fanciness.
* Testify must take a `testing.TB` to enable testify usage in benchmark tests.

The reason this has been on my mind is because I usually use a very small subset of the available API in the current testify, and I feel that it may be getting a bit bloated. In addition, I feel that testify may be adding some overhead to the testing process, thus increasing the amount of time it takes to run tests. I really should get some data to back that up. In addition, testify was written a long time ago, when we were still young gophers. I feel it could be much cleaner. :)

I am still not sure this is something I will move forward with. I am hoping to get some feedback from the community to see what you think. Most likely this will live in its own subfolder as a separate package so the current version of testify doesn't just break for people currently using it.

I'd appreciate some feedback from all of you who use testify, if you would be so kind:

* What functionality do you find yourself using the most?
* What functionality could you simply not live without?
* What is missing that you feel should be added?
* What is in testify that you feel should be removed?
* What is in testify that you feel could be improved?
* Anything else?

Thanks in advance, everyone!

**Comment by madhuravi** [comment]
assert seems to accept a Testing.B now. Has this been fixed?

**Comment by DAddYE** [comment]
Yup!
