### ISSUE TITLE
Add support for errors.Is

### ISSUE THREAD

**Issue by cosmonawt** [stretchr/testify#842]
Right now there is no clean way to assert the type of an underlying (wrapped) error.
Two methods do work, namely:
```go
assert.IsType(t, test.error, errors.Unwrap(err))
```
and 
```go
assert.True(t, errors.Is(err, test.error))
```
However, both have their flaws:
- The first way only supports unwrapping one "level" deep. If the underlying error is wrapped multiple (potentially unknown many) times, this becomes unfeasible.
- The second way does not give any additional information on the types that were provided.

What I think would be nice to have is a function 
```go
assert.ErrorIs(t *testing.T, expected, actual error)
```
which calls `errors.Is(expected, actual)` under the hood and returns information on the provided types should the call return `false`.

**Comment by frasercobb** [comment]
Hey @cosmonawt,

I was also looking for this functionality, why was this closed?

**Comment by cosmonawt** [comment]
@frasercobb I noticed, that I miunderstood my actual problem. What I needed was `errors.As` and not `errors.Is`. I still think these features could be added, but I wanted to revisit this with a better understanding of what is actually needed and then open up a new issue.
