### ISSUE TITLE
 Expected nil, but got: (unsafe.Pointer)(nil)

### ISSUE THREAD

**Issue by eloff** [stretchr/testify#863]
Nil/NotNil assertions should work with unsafe.Pointer, since == nil and != nil do.

**Comment by boyan-soubachov** [comment]
Thanks for this @eloff , it's a good point. I'd be happy to look into this or if you'd like, submit a PR which I'd be very glad to review and merge :)

**Comment by dolmen** [comment]
Fixed by #1319.
