### ISSUE TITLE
Feature request: assert.Never

### ISSUE THREAD

**Issue by torkelrogstad** [stretchr/testify#870]
Proposal for new assertion to the API: `assert.Never(*testing.T, func() bool, time.Duration, time.Duration)`. It would be a direct mirror of `assert.Eventually`, checking that the given condition wasn't met within a certain timeframe.

Copying a bunch of code from `assert.Eventually`, the implementation could look like this: 

```go
func Never(t *testing.T, condition func() bool, waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) bool {
	timer := time.NewTimer(waitFor)
	ticker := time.NewTicker(tick)
	checkPassed := make(chan bool)
	defer timer.Stop()
	defer ticker.Stop()
	defer close(checkPassed)
	for {
		select {
		case <-timer.C:
			return true
		case result := <-checkPassed:
			if result {
				return assert.Fail(t, "Condition satisfied", msgAndArgs...)
			}
		case <-ticker.C:
			go func() {
				checkPassed <- condition()
			}()
		}
	}
}
```

If this is something the maintainers would merge, I'd be happy to make a PR with tests and documentation for it.

**Comment by glesica** [comment]
Sure, that sounds useful.
