### ISSUE TITLE
suite.TestingT incompatible with gomock.TestReporter

### ISSUE THREAD

**Issue by shousper** [stretchr/testify#878]
A recent change has broken compatibility with `gomock` when using suites.

The [`gomock.TestReporter`](https://github.com/golang/mock/blob/master/gomock/controller.go#L66) interface requires the `Fatalf` method which is missing from [`suite.TestingT`](https://github.com/stretchr/testify/blob/master/suite/suite.go#L20). This has only become a problem now that the `Suite.T()` method returns this interface instead of `*testing.T`. I believe this was the breaking change: https://github.com/stretchr/testify/pull/867

If the extra method could be added to the interface, that'd be great. I'm honestly not sure otherwise what a good solution would be to avoid breaking compatibility with other libraries. Perhaps just ensuring that the entire public interface of `testing.T` is represented in the return type of `Suite.T()`?

**Comment by phlogistonjohn** [comment]
One might also argue that changing the return type this way is an API breaking change and would call for a 2.x version number according to the go module rules.

**Comment by glesica** [comment]
I'd like to get this into the next release, which is almost certainly going to be 2.0.0. If someone wants to take it on, that'd be great. If not, I'll try to get to it before we cut the release.
