### ISSUE TITLE
How do I use subtests in testify

### ISSUE THREAD

**Issue by nandac** [stretchr/testify#889]
Hi testify team,

Thank you for writing this package.

I have been having issues using the suite.Run() wrapper function for subtest functionality.

Because I am testing out the validity and deployment of AWS resources using Terraform I have the need to order the tests. This is the reason I want to use subtests.

I like the test suite functionality testify has but still want the ordering capability of subtests and was wondering if you could provide an example of how I would do that.

This is what I have so far:

```
import (
	"fmt"
	"os"
	"strings"
	//"testing"

	"github.com/gruntwork-io/terratest/modules/terraform"
	"github.com/stretchr/testify/require"
	"github.com/stretchr/testify/suite"

type TerraformTestSuite struct {
	suite.Suite
}

func (suite *TerraformTestSuite) TestVpc() {
	suite.Run("TestCodeFormatting", suite.TestCodeFormatting)
}

func (suite *TerraformTestSuite) TestCodeFormatting() {
	terraformOptions := &terraform.Options{
		TerraformDir: terraformWorkingDir,
		NoColor:      true,
	}

	out := terraform.RunTerraformCommand(suite.T(), terraformOptions, "fmt", "-check")

	require.Equal(
		suite.T(),
		"", strings.TrimSpace(out),
		"Please correct formatting by running `terraform fmt`",
	)
}
```

I am not sure where the golang `t *testing` should be used in this setup as I keep getting the warning:

```
testing: warning: no tests to run
PASS
ok      test    0.544s 
```

I know I am missing something simple here but I am not able to figure it out.

Thanks in advance.

**Comment by nandac** [comment]
I see a CallOrderSuite in suite_test.go should I be using that to order tests instead of subtests?

**Comment by nandac** [comment]
I have made some progress with this setup for my code:

```
package sharedvpctest

import (
	"fmt"
	"os"
	"strings"
	"testing"

	"github.com/gruntwork-io/terratest/modules/terraform"
	"github.com/stretchr/testify/require"
	"github.com/stretchr/testify/suite"
)

type TerraformTestSuite struct {
	suite.Suite
}

// TestTerraformTestSuite runs the tests in the suite.
func TestTerraformTestSuite(t *testing.T) {
	suite.Run(t, new(TerraformTestSuite))
}

func (suite *TerraformTestSuite) TestModule() {
	for _, testFuncs := range []struct {
		name        string
		testingFunc func()
	}{
		{"TestCodeFormatting", suite.TestCodeFormatting},
	} {
		suite.Run(testFuncs.name, testFuncs.testingFunc)
	}
}

// TestCodeFormatting checks if Terraform code adheres to correct formatting.
func (suite *TerraformTestSuite) TestCodeFormatting() {
	terraformOptions := &terraform.Options{
		TerraformDir: terraformWorkingDir,
		NoColor:      true,
	}

	out := terraform.RunTerraformCommand(suite.T(), terraformOptions, "fmt", "-check")

	require.Equal(
		suite.T(),
		"", strings.TrimSpace(out),
		"Please correct formatting by running `terraform fmt`",
	)
}
```

The only issue now is that the tests run twice once through the call to `suite.Run(t, new(TerraformTestSuite)` and then through subtests when `TestModule()` is called.

I would appreciate some help in understanding this and getting the tests to only run once through subtests and still keep suite functionality. The subtest example in `suite_test.go` is not sufficient for me to extrapolate due to my unfamiliarity with Go.

**Comment by nandac** [comment]
I decided to go ahead and use the native go tests and subtests functionality which does the job just fine instead of using testify's test suite.

You may close this issues unless you would like to give me an answer on how to use subtests in testify.

**Comment by glesica** [comment]
Glad you found a resolution!

**Comment by itzamna314** [comment]
@nandac The problem is that you've running the function as a sub-test with `suite.Run`, but the test itself is prefixed with `TestXxx` and has a `*suite.Suite` as a receiver, so it gets run again by the normal test runner. Just give the test function a name that doesn't start with `Test` and your sample will work.

I typically find it easier to write the sub-tests inline for both native a suite tests, like:

```
func (suite *TerraformTestSuite) TestModule() {
	for _, testFuncs := range []struct {
		name        string
		testingFunc func()
	}{
		{"TestCodeFormatting", suite.TestCodeFormatting},
	} {
		suite.Run(testFuncs.name, func() {
	          terraformOptions := &terraform.Options{
		          TerraformDir: terraformWorkingDir,
		          NoColor:      true,
	          }

	          out := terraform.RunTerraformCommand(suite.T(), terraformOptions, "fmt", "-check")
  
                  // pro tip - a suite has a require instance already attached
                  suite.Require().Equal("", strings.TrimSpace(out),  "Please correct formatting by running `terraform fmt`")
            })
	}
}```
