### ISSUE TITLE
Issues fetching dependencies

### ISSUE THREAD

**Issue by meet2kamaljoshi** [stretchr/testify#905]
third_party/go/src/github.com/stretchr/testify/assert/assertions.go, line 20, column 2: cannot find package "github.com/davecgh/go-spew/spew" 

third_party/go/src/github.com/stretchr/testify/assert/assertions.go, line 21, column 2: cannot find package "github.com/pmezard/go-difflib/difflib"

**Comment by boyan-soubachov** [comment]
Please make sure you either have go modules enabled or if you do not, `go get` the relevant packages.
