### ISSUE TITLE
go get cannot download this pkg

### ISSUE THREAD

**Issue by xiangwangcheng** [stretchr/testify#915]
when I run 
`go get github.com/stretchr/testify/assert`

I got this

![image](https://user-images.githubusercontent.com/8049014/76433140-e09d6880-63ee-11ea-9bcc-0d8be05d3ccb.png)

I am beginner of go...

**Comment by glesica** [comment]
That's a dependency for Testify, it was installed automatically. You should find testify under `stretchr/testify`.

**Comment by boyan-soubachov** [comment]
As stated in the README.md file, you should use `go get github.com/stretchr/testify`

**Comment by xiangwangcheng** [comment]
@boyan-soubachov @glesica  I was using `go get github.com/stretchr/testify`, but I didn't get what I want.
![image](https://user-images.githubusercontent.com/8049014/76535013-2f153a80-64b5-11ea-891b-cfe85be54a2f.png)

**Comment by xiangwangcheng** [comment]
I can get other packages though.
