### ISSUE TITLE
TearDownSuite() not working with -failfast flag

### ISSUE THREAD

**Issue by StepanDalecky** [stretchr/testify#917]
To reproduce the bug, run the test below with `-failfast` flag, it will get stuck.

```go
package testsuite

import (
	"testing"

	"github.com/stretchr/testify/suite"
)

type TestSuite struct {
	suite.Suite
}

func (ts *TestSuite) TestA() {
	ts.Require().True(false)
}

func (ts *TestSuite) TestB() {
	ts.Require().True(true)
}

func (ts *TestSuite) TearDownSuite() {
}

func TestTestSuite(t *testing.T) {
	suite.Run(t, new(TestSuite))
}
```
After removing `-failfast` flag or `TearDownSuite` method, the suite fails correctly.

Versions: testify 1.15.1, go 1.13

**Comment by AdRiley** [comment]
This was introduced with this commit https://github.com/stretchr/testify/commit/0d3c8ce9f8c3be984ccd5d2e3438b173ea722267. I have a PR which I think fixes it.

**Comment by AdRiley** [comment]
Actually I have test failures with my change that I didn't think I was seeing locally. I will investigate and revise.
