### ISSUE TITLE
Documentation errors in assert Equalvaluesf and Exactlyf

### ISSUE THREAD

**Issue by lk16** [stretchr/testify#927]
Hi everyone!

First of all thanks for making and maintaining this great package.

I found a small issue in the docs, it says
`assert.EqualValuesf(t, uint32(123, "error message %s", "formatted"), int32(123))`
which is obviously invalid code. I found it at:
https://github.com/stretchr/testify/blob/master/assert/assertion_format.go#L96

A similar issue can be found here.
https://github.com/stretchr/testify/blob/master/assert/assertion_format.go#L130

I am up for checking any other issues and submitting a PR with fixes myself.
I am writing here so you guys are aware and to check if it hasn't been fixed yet by someone else.
It is present on master and I couldn't find any tickets mentioning this issue.

**Comment by mvdkleijn** [comment]
Hi, don't think anyone reported this before. Feel free to submit a PR. Looks a little like copy-n-paste gone wrong. :smile:

**Comment by mvdkleijn** [comment]
Fixed by #945
