### ISSUE TITLE
github.com/stretchr/testify@v1.5.1: reading github.com/stretchr/testify/go.mod at revision v1.5.1: unknown revision v1.5.1

### ISSUE THREAD

**Issue by jiharal** [stretchr/testify#940]

**Comment by boyan-soubachov** [comment]
Do you mind clarifying what the actual issue is and how one can reproduce it?

**Comment by jiharal** [comment]
hi, i'm just clean my `gomod` cache using using command `go clean --modcache`. and then `go mod tidy`.

this is my go `env`
![image](https://user-images.githubusercontent.com/21150538/81105020-8bd52480-8f3d-11ea-9cfa-f3c5cf456d3e.png)

**Comment by charlieflowers** [comment]
Love to hear what the resolution was. I'm running into this too.
