### ISSUE TITLE
bug: `TestResponseWriter` returns `ErrShortWrite` when used with `io.Copy`

### ISSUE THREAD

**Issue by alexec** [stretchr/testify#988]
This code is wrong:

```golang
// Write DEPRECATED: We recommend you use http://golang.org/pkg/net/http/httptest instead.
func (rw *TestResponseWriter) Write(bytes []byte) (int, error) {

	// assume 200 success if no header has been set
	if rw.StatusCode == 0 {
		rw.WriteHeader(200)
	}

	// add these bytes to the output string
	rw.Output += string(bytes)

	// return normal values
	return 0, nil //<-- should be len(bytes)
}
```

**Comment by mvdkleijn** [comment]
I understand your point but since it's deprecated I'm tempted to just rip it out.

Since I'm a relatively new maintainer... @glesica @boyan-soubachov do you know in which release this was supposed to be removed?

**Comment by boyan-soubachov** [comment]
> I understand your point but since it's deprecated I'm tempted to just rip it out.
> 
> Since I'm a relatively new maintainer... @glesica @boyan-soubachov do you know in which release this was supposed to be removed?

+1. For backwards compatibility, we can't remove/change it but we're not maintaining deprecated code.

**Comment by alexec** [comment]
My solution was the change library to http://golang.org/pkg/net/http/httptest - obviously.
